In [1]:
import pandas as pd
import numpy as np

import warnings

warnings.filterwarnings('ignore')

In [2]:
file_name = 'COTA_KINGElvis (3).xlsx'

old_combine_df=pd.read_excel(file_name,sheet_name='Elvis_Review')

new_combine_df=pd.read_csv("Merged Checks.csv")

In [3]:
old_combine_df.shape,new_combine_df.shape

((8026, 44), (7054, 43))

In [4]:
old_combine_df=old_combine_df[old_combine_df['1st Cleaner']!='Test/No 5 MIN']

In [5]:
old_combine_df.head(5)

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO
16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
18,2023-11-03,5636,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
19,2023-11-03,5639,HereAPI,"T A Divya, Brian, Regina",Remove,Round trip,,Elvis_Review,Elvis_Review,NaN,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
24,2023-11-03,5646,HereAPI,"T A Divya, Brian, Regina",Use,NaN,,Elvis_Review,Elvis_Review,"o= home = E Main St & Wilson Ave, Columbus, OH...",...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [6]:
new_combine_df=new_combine_df[new_combine_df['1st Cleaner']!='Test/No 5 MIN']

In [7]:
new_combine_df.head(5)

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO,2X_REVIEW_CHECK
16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
18,2023-11-03,5636,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
19,2023-11-03,5639,HereAPI,"T A Divya, Brian, Regina",Remove,Round trip,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
24,2023-11-03,5646,HereAPI,"T A Divya, Brian, Regina",Use,NaN,,Elvis_Review,Elvis_Review,"o= home = E Main St & Wilson Ave, Columbus, OH...",...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0

In [8]:
old_combine_df.head(2)

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO
16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [9]:
new_combine_df.head(2)

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO,2X_REVIEW_CHECK
16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0

In [10]:
old_combine_df.shape[0],new_combine_df.shape[0]

(6495, 5679)

In [11]:
if old_combine_df.shape[0] > new_combine_df.shape[0]:
    old_combine_df = pd.merge(old_combine_df, new_combine_df[['id']], on='id', how='inner')


elif old_combine_df.shape[0] < new_combine_df.shape[0]:
    new_combine_df = pd.merge(new_combine_df, old_combine_df[['id']], on='id', how='inner')
    
old_combine_df.drop_duplicates(subset=['id'],inplace=True)
new_combine_df.drop_duplicates(subset=['id'],inplace=True)
# 'else' case is not needed as you are not performing any operation

# If you want to drop the '_merge' and 'Available IDs' columns (if present)
old_combine_df.drop(columns=['_merge'], inplace=True, errors='ignore')
new_combine_df.drop(columns=['_merge'], inplace=True, errors='ignore')

In [12]:
common_ids = set(old_combine_df['id']).intersection(new_combine_df['id'])
print("Common IDs:", len(common_ids))

Common IDs: 5679

In [13]:
old_combine_df.shape[0],new_combine_df.shape[0]

(5679, 5679)

In [14]:
new_combine_df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO,2X_REVIEW_CHECK
16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
18,2023-11-03,5636,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
19,2023-11-03,5639,HereAPI,"T A Divya, Brian, Regina",Remove,Round trip,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
24,2023-11-03,5646,HereAPI,"T A Divya, Brian, Regina",Use,NaN,,Elvis_Review,Elvis_Review,"o= home = E Main St & Wilson Ave, Columbus, OH...",...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0

In [15]:
new_combine_df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO,2X_REVIEW_CHECK
16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
18,2023-11-03,5636,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
19,2023-11-03,5639,HereAPI,"T A Divya, Brian, Regina",Remove,Round trip,,Elvis_Review,Elvis_Review,NaN,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
24,2023-11-03,5646,HereAPI,"T A Divya, Brian, Regina",Use,NaN,,Elvis_Review,Elvis_Review,"o= home = E Main St & Wilson Ave, Columbus, OH...",...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0

In [16]:
new_combine_df['2X_REVIEW_CHECK']

16      0
17      0
18      0
19      0
24      0
       ..
7049    0
7050    0
7051    0
7052    0
7053    0
Name: 2X_REVIEW_CHECK, Length: 5679, dtype: int64

In [17]:
old_combine_df = old_combine_df.sort_values(by='id')
new_combine_df = new_combine_df.sort_values(by='id')

In [18]:
old_combine_df.reset_index(inplace=True)
new_combine_df.reset_index(inplace=True)

In [19]:
old_combine_df.head()

,index,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO
0,0,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1,1,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,2,2023-11-03,5636,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,3,2023-11-03,5639,HereAPI,"T A Divya, Brian, Regina",Remove,Round trip,,Elvis_Review,Elvis_Review,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,4,2023-11-03,5646,HereAPI,"T A Divya, Brian, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN

In [20]:
new_combine_df.head()

,index,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,...,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO,2X_REVIEW_CHECK
0,16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
1,17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
2,18,2023-11-03,5636,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
3,19,2023-11-03,5639,HereAPI,"T A Divya, Brian, Regina",Remove,Round trip,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
4,24,2023-11-03,5646,HereAPI,"T A Divya, Brian, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0

In [21]:
new_combine_df.loc[0, '2X_REVIEW_CHECK']

0

In [22]:
for index , row in old_combine_df.iterrows():
    old_value = row['2X_REVIEW_CHECK']
    new_value = new_combine_df.loc[index, '2X_REVIEW_CHECK']
    
    if old_value != new_value:
        old_combine_df.at[index, '2x_REVIEWED_FLAG'] = new_value
    else:
        old_combine_df.at[index, '2x_REVIEWED_FLAG'] = old_value

In [23]:
new_combine_df.head()

,index,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,...,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,RECORD_INFO,2X_REVIEW_CHECK
0,16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
1,17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
2,18,2023-11-03,5636,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
3,19,2023-11-03,5639,HereAPI,"T A Divya, Brian, Regina",Remove,Round trip,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0
4,24,2023-11-03,5646,HereAPI,"T A Divya, Brian, Regina",Use,NaN,,Elvis_Review,Elvis_Review,...,Regina,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0