In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
wkday_route_direction_df=pd.read_excel('reviewtool_20250108_VTA_RouteLevelComparison(Wkday & WkEnd)_Latest_01.xlsx',sheet_name='WkDAY Route DIR Comparison')
wkday_comparison_df=pd.read_excel('reviewtool_20250108_VTA_RouteLevelComparison(Wkday & WkEnd)_Latest_01.xlsx',sheet_name='WkDAY Route Comparison')

In [3]:
detail_df_stops=pd.read_excel('details_vta_CA_od_excel.xlsx',sheet_name='STOPS')
detail_df_xfers=pd.read_excel('details_vta_CA_od_excel.xlsx',sheet_name='XFERS')

In [4]:
wkday_comparison_df.head(2)

,ROUTE_SURVEYEDCode,Route Level Goal,(0) Goal,(1) Goal,(2) Goal,(3) Goal,(4) Goal,(5) Goal,(0) Collect,(1) Collect,...,(4) Collect,(5) Collect,# of Surveys,(0) Remain,(1) Remain,(2) Remain,(3) Remain,(4) Remain,(5) Remain,Remaining
0,VTA_2_20,79.625,0,0,16,32,31,4,1,0,...,13,0,64,0,0,0,3,18,4,16
1,VTA_2_21,148.875,0,0,42,58,44,9,1,0,...,33,16,144,0,0,6,0,11,0,5

In [5]:
wkday_route_direction_df

,ROUTE_SURVEYEDCode,(0) Goal,(1) Goal,(2) Goal,(3) Goal,(4) Goal,(5) Goal,(0) Collect,(1) Collect,(2) Collect,(3) Collect,(4) Collect,(5) Collect,(0) Remain,(1) Remain,(2) Remain,(3) Remain,(4) Remain,(5) Remain
0,VTA_2_20_00,0,0,6,16,19,2,1,0,5,13,8,0,0,0,1,3,11,2
1,VTA_2_20_01,0,0,10,16,12,2,0,0,16,16,5,0,0,0,0,0,7,2
2,VTA_2_21_00,0,0,19,33,23,3,0,0,22,37,17,10,0,0,0,0,6,0
3,VTA_2_21_01,0,0,23,25,21,6,1,0,14,21,16,6,0,0,9,4,5,0
4,VTA_2_22_00,13,6,75,125,93,25,0,0,55,130,108,46,13,6,20,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,VTA_2_BlueLine_01,2,3,58,103,114,56,2,1,82,84,64,45,0,2,0,19,50,11
109,VTA_2_GreenLine_00,2,3,70,86,77,36,0,2,57,54,55,21,2,1,13,32,22,15
110,VTA_2_GreenLine_01,1,2,46,64,76,43,0,1,34,65,54,22,1,1,12,0,22,21
111,VTA_2_OrangeLine_00,1,3,50,71,108,48,1,0,47,59,89,33,0,3,3,12,19,15
112,VTA_2_OrangeLine_01,1,5,70,85,97,37,0,2,49,80,81,26,1,3,21,5,16,11

In [6]:
detail_df_stops[['ETC_ROUTE_ID','ETC_ROUTE_NAME']].head(2)

  ETC_ROUTE_ID                                     ETC_ROUTE_NAME
0  VTA_2_20_00  20 - Milpitas BART - Sunnyvale TC [Eastbound T...
1  VTA_2_20_00  20 - Milpitas BART - Sunnyvale TC [Eastbound T...

In [7]:
detail_df_xfers.head(2)

,agency,ETC_ROUTE_ID,ETC_ROUTE_NAME,NOTES,google_route,TOD_TYPE,AGNECY_TRANSFERS
0,VTA,VTA_2_20,20 - Milpitas BART - Sunnyvale TC,NaN,NaN,NaN,NaN
1,ANC,VTA_2_21,21 - Stanford Shopping Ctr - Santa Clara TC,NaN,NaN,NaN,NaN

In [8]:
detail_df_xfers.columns

Index(['agency', 'ETC_ROUTE_ID', 'ETC_ROUTE_NAME', 'NOTES', 'google_route',
       'TOD_TYPE', 'AGNECY_TRANSFERS'],
      dtype='object')

In [9]:
wkday_comparison_df = wkday_comparison_df.merge(
    detail_df_xfers[['ETC_ROUTE_ID', 'ETC_ROUTE_NAME']],
    left_on='ROUTE_SURVEYEDCode',
    right_on='ETC_ROUTE_ID',
    how='left'
)

# Rename the column as per requirement
wkday_comparison_df.rename(columns={'ETC_ROUTE_NAME': 'ROUTE_SURVEYED'}, inplace=True)

In [10]:
wkday_comparison_df[['ROUTE_SURVEYEDCode','ROUTE_SURVEYED','ETC_ROUTE_ID']]

  ROUTE_SURVEYEDCode                               ROUTE_SURVEYED ETC_ROUTE_ID
0           VTA_2_20            20 - Milpitas BART - Sunnyvale TC     VTA_2_20
1           VTA_2_21  21 - Stanford Shopping Ctr - Santa Clara TC     VTA_2_21

In [11]:
wkday_comparison_df.drop(columns=['ETC_ROUTE_ID'], inplace=True)

In [12]:
for _,row in wkday_route_direction_df.iterrows():
    route_surveyed=detail_df_stops[detail_df_stops['ETC_ROUTE_ID']==row['ROUTE_SURVEYEDCode']]['ETC_ROUTE_NAME'].iloc[0]
    route_surveyed_ID=detail_df_stops[detail_df_stops['ETC_ROUTE_ID']==row['ROUTE_SURVEYEDCode']]['ETC_ROUTE_ID'].iloc[0]
    wkday_route_direction_df.loc[row.name,'ROUTE_SURVEYED']=route_surveyed    
#     wkday_route_direction_df.loc[row.name,'ETC_ROUTE_ID']=route_surveyed_ID

In [14]:
wkday_route_direction_df[['ROUTE_SURVEYEDCode','ROUTE_SURVEYED']]

      ROUTE_SURVEYEDCode                                     ROUTE_SURVEYED
0            VTA_2_20_00  20 - Milpitas BART - Sunnyvale TC [Eastbound T...
1            VTA_2_20_01  20 - Milpitas BART - Sunnyvale TC [Westbound T...
2            VTA_2_21_00  21 - Stanford Shopping Ctr - Santa Clara TC [E...
3            VTA_2_21_01  21 - Stanford Shopping Ctr - Santa Clara TC [W...
4            VTA_2_22_00  22 - Palo Alto TC - Eastridge [Eastbound Towar...
..                   ...                                                ...
108    VTA_2_BlueLine_01  Blue Line - Baypointe - Santa Teresa [Southbou...
109   VTA_2_GreenLine_00  Green Line - Old Ironsides - Winchester [North...
110   VTA_2_GreenLine_01  Green Line - Old Ironsides - Winchester [South...
111  VTA_2_OrangeLine_00  Orange Line - Mountain View - Alum Rock [Eastb...
112  VTA_2_OrangeLine_01  Orange Line - Mountain View - Alum Rock [Westb...

[113 rows x 2 columns]