In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv('reviewtool_20240821_LAGUARDIA_combinedflags.csv')
df.head()

,Elvis_Date,elvis_id,1st Cleaner,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,STOP_ON_LAT,STOP_ON_LONG,STOP_OFF_LAT,...,Stops_Status,Test_Status,Traditional_Check,OD_Distance_Check,Transfer_Distance_Check,Flag Description,2X_REVIEW_CHECK,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED
0,2024-08-21,514,Test,40.726545,-73.941539,40.772924,-73.872198,40.768790,-73.910815,40.772924,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN
1,2024-08-21,522,HereAPI,40.773656,-73.959860,40.772924,-73.872198,40.801818,-73.967642,40.772924,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN
2,2024-08-21,524,Test,40.772924,-73.872198,40.772924,-73.872198,40.772924,-73.872198,40.772924,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN
3,2024-08-21,525,Test,40.772924,-73.872198,40.747929,-73.943983,40.772924,-73.872198,40.773656,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN
4,2024-08-21,528,Test,40.706672,-73.960228,40.772924,-73.872198,40.746543,-73.890686,40.772924,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN

In [3]:
df=df[df['1st Cleaner']=='HereAPI']
df.head()

,Elvis_Date,elvis_id,1st Cleaner,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,STOP_ON_LAT,STOP_ON_LONG,STOP_OFF_LAT,...,Stops_Status,Test_Status,Traditional_Check,OD_Distance_Check,Transfer_Distance_Check,Flag Description,2X_REVIEW_CHECK,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED
1,2024-08-21,522,HereAPI,40.773656,-73.959860,40.772924,-73.872198,40.801818,-73.967642,40.772924,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN
6,2024-08-21,531,HereAPI,40.786494,-73.838960,40.772924,-73.872198,40.770289,-73.864375,40.772924,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN
9,2024-08-21,538,HereAPI,40.747282,-73.926862,40.772924,-73.872198,40.770459,-73.917778,40.772924,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN
20,2024-08-21,600,HereAPI,40.767009,-73.867043,40.772924,-73.872198,40.770289,-73.864375,40.772924,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN
21,2024-08-21,605,HereAPI,40.772924,-73.872198,40.704189,-73.894813,40.772924,-73.872198,40.746543,...,Elvis_Review,Tested,0,0,0,,0,NaN,NaN,NaN

In [5]:
df[df['elvis_id']<650].shape

(54, 46)

In [6]:
df[(df['elvis_id']>=700)&(df['elvis_id']<820)].shape

(89, 46)

In [10]:
df[(df['elvis_id']>=900)&(df['elvis_id']<1051)].shape

(119, 46)

In [8]:
df[(df['elvis_id']>=900)&(df['elvis_id']<1000)].shape

(81, 46)

In [12]:
df[df['elvis_id']<1259].shape

(443, 46)

In [ ]:
df[df['elvis_id']<1259].shape