In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df= pd.read_csv('elvistucson2025obweekday_export_odbc.csv')
df1= pd.read_csv('tucson2025obweekday_export_odbc.csv')

In [3]:
df.shape,df1.shape

((10573, 768), (11395, 768))

In [4]:
df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT',
       ...
       'ELVIS_USER_CHANGE_7_C_DATE', 'ELVIS_USER_CHANGE_7_C_FIELD',
       'ELVIS_USER_CHANGE_7_C_REASON', 'INVITE_EMAIL', 'INVITE_SMS',
       'INVITE_CALL', 'INVITE_TOKEN', 'INVITE_STATUS', '_REVERSE_TRIP',
       'GENERATABLE_TRIPS'],
      dtype='object', length=768)

In [5]:
df1.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT',
       ...
       'ELVIS_USER_CHANGE_7_C_DATE_', 'ELVIS_USER_CHANGE_7_C_FIELD_',
       'ELVIS_USER_CHANGE_7_C_REASON_', 'INVITE_EMAIL', 'INVITE_SMS',
       'INVITE_CALL', 'INVITE_TOKEN', 'INVITE_STATUS', '_REVERSE_TRIP',
       'GENERATABLE_TRIPS'],
      dtype='object', length=768)

In [ ]:
# pd.merge(df1,df,on='id',how='right')

In [6]:
def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [9]:
# Working Code Snippet

In [7]:
def clean_string(s):
    return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()
def check_all_characters_present(df, columns_to_check):
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()
    
    df_columns_lower = [clean_string(column) for column in df.columns]
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]
    return matching_columns

# Create a dictionary to map df1 column names to df column names
column_mapping = {}
for df1_col in df1.columns:
    cleaned_df1_col = clean_string(df1_col)
    for df_col in df.columns:
        if cleaned_df1_col == clean_string(df_col):
            column_mapping[df1_col] = df_col
            break  # Move to next df1 column once we find a match

# Rename df1 columns to match df column names exactly
df2 = df1.rename(columns=column_mapping)

In [10]:
missing_ids = set(df1['id']) - set(df['id'])
missing_ids

{18050,
 18052,
 18053,
 18054,
 18055,
 18056,
 18057,
 18058,
 18059,
 18060,
 18062,
 18064,
 18065,
 18066,
 18070,
 18071,
 18072,
 18073,
 18075,
 18076,
 18077,
 18078,
 18080,
 18081,
 18082,
 18084,
 18092,
 18095,
 18096,
 18097,
 18099,
 18100,
 18101,
 18102,
 18104,
 18105,
 18106,
 18107,
 18109,
 18110,
 18111,
 18113,
 18120,
 18121,
 18125,
 18127,
 18128,
 18131,
 18132,
 18133,
 18136,
 18138,
 18139,
 18140,
 18141,
 18142,
 18144,
 18146,
 18147,
 18149,
 18150,
 18152,
 18153,
 18154,
 18155,
 18156,
 18157,
 18158,
 18159,
 18160,
 18164,
 18165,
 18168,
 18169,
 18172,
 18173,
 18174,
 18177,
 18179,
 18184,
 18187,
 18188,
 18190,
 18193,
 18194,
 18195,
 18200,
 18201,
 18203,
 18205,
 18206,
 18207,
 18210,
 18211,
 18213,
 18218,
 18219,
 18220,
 18223,
 18224,
 18225,
 18226,
 18228,
 18229,
 18230,
 18231,
 18235,
 18236,
 18237,
 18238,
 18239,
 18244,
 18245,
 18248,
 18249,
 18251,
 18254,
 18255,
 18256,
 18257,
 18261,
 18262,
 18263,
 18264,
 18266,
 18267,
 18269,
 18270,
 18272,
 18275,
 18276,
 18277,
 18278,
 18281,
 18282,
 18284,
 18286,
 18288,
 18291,
 18292,
 18293,
 18300,
 18302,
 18304,
 18305,
 18306,
 18308,
 18309,
 18310,
 18314,
 18315,
 18317,
 18318,
 18319,
 18321,
 18322,
 18323,
 18325,
 18326,
 18328,
 18330,
 18331,
 18332,
 18334,
 18335,
 18337,
 18338,
 18339,
 18340,
 18341,
 18347,
 18348,
 18349,
 18351,
 18352,
 18353,
 18354,
 18355,
 18356,
 18357,
 18359,
 18360,
 18362,
 18365,
 18367,
 18372,
 18373,
 18374,
 18380,
 18381,
 18382,
 18383,
 18385,
 18387,
 18388,
 18391,
 18392,
 18393,
 18394,
 18395,
 18396,
 18397,
 18398,
 18399,
 18400,
 18401,
 18402,
 18403,
 18404,
 18405,
 18407,
 18408,
 18410,
 18411,
 18412,
 18413,
 18414,
 18415,
 18416,
 18418,
 18420,
 18421,
 18422,
 18423,
 18424,
 18425,
 18426,
 18427,
 18428,
 18429,
 18430,
 18431,
 18432,
 18433,
 18434,
 18435,
 18436,
 18437,
 18438,
 18439,
 18444,
 18445,
 18446,
 18447,
 18448,
 18449,
 18450,
 18451,
 18454,
 18455,
 18458,
 18459,
 18460,
 18461,
 18462,
 18463,
 18464,
 18465,
 18466,
 18468,
 18469,
 18470,
 18472,
 18473,
 18475,
 18478,
 18480,
 18481,
 18482,
 18484,
 18485,
 18486,
 18487,
 18488,
 18489,
 18493,
 18495,
 18497,
 18499,
 18500,
 18502,
 18503,
 18505,
 18506,
 18507,
 18508,
 18510,
 18512,
 18513,
 18514,
 18515,
 18516,
 18518,
 18520,
 18521,
 18523,
 18524,
 18525,
 18526,
 18528,
 18531,
 18532,
 18533,
 18535,
 18536,
 18539,
 18540,
 18541,
 18542,
 18543,
 18544,
 18545,
 18546,
 18547,
 18550,
 18553,
 18560,
 18561,
 18562,
 18565,
 18568,
 18569,
 18570,
 18571,
 18572,
 18573,
 18574,
 18575,
 18579,
 18581,
 18582,
 18583,
 18584,
 18585,
 18587,
 18588,
 18590,
 18591,
 18593,
 18594,
 18603,
 18604,
 18605,
 18606,
 18607,
 18609,
 18610,
 18611,
 18613,
 18614,
 18619,
 18620,
 18621,
 18622,
 18623,
 18624,
 18625,
 18626,
 18627,
 18628,
 18629,
 18630,
 18634,
 18635,
 18636,
 18638,
 18639,
 18640,
 18646,
 18648,
 18651,
 18652,
 18653,
 18654,
 18656,
 18657,
 18660,
 18661,
 18664,
 18665,
 18666,
 18667,
 18669,
 18670,
 18671,
 18672,
 18675,
 18676,
 18677,
 18678,
 18680,
 18684,
 18685,
 18686,
 18687,
 18688,
 18689,
 18693,
 18696,
 18697,
 18699,
 18701,
 18702,
 18703,
 18704,
 18707,
 18708,
 18710,
 18716,
 18719,
 18722,
 18723,
 18724,
 18726,
 18727,
 18728,
 18730,
 18731,
 18732,
 18734,
 18735,
 18736,
 18737,
 18739,
 18740,
 18744,
 18745,
 18747,
 18748,
 18751,
 18752,
 18753,
 18755,
 18757,
 18758,
 18759,
 18760,
 18761,
 18762,
 18763,
 18765,
 18766,
 18767,
 18768,
 18769,
 18771,
 18772,
 18773,
 18775,
 18776,
 18777,
 18778,
 18779,
 18780,
 18782,
 18783,
 18785,
 18786,
 18789,
 18790,
 18791,
 18793,
 18794,
 18795,
 18796,
 18801,
 18802,
 18803,
 18804,
 18805,
 18808,
 18810,
 18811,
 18812,
 18813,
 18814,
 18815,
 18817,
 18818,
 18820,
 18821,
 18822,
 18823,
 18825,
 18826,
 18830,
 18831,
 18832,
 18833,
 18835,
 18836,
 18837,
 18838,
 18839,
 18842,
 18844,
 18845,
 18846,
 18847,
 18848,
 18849,
 18850,
 18851,
 18852,
 18853,
 18856,
 18858,
 18859,
 18861,
 18862,
 18863,
 18864,
 18865,
 18866,
 18869,
 18870,
 18871,
 18873,
 18874,
 18876,
 18877,
 18878,
 18879,
 18880,
 18881,
 18883,
 18889,
 18890,
 18891,
 18892,
 18894,
 18895,
 18896,
 18897,
 18899,
 18900,
 18903,
 18904,
 18905,
 18906,
 18907,
 18910,
 18911,
 18912,
 18915,
 18917,
 18918,
 18920,
 18923,
 18926,
 18929,
 18932,
 18933,
 18937,
 18938,
 18939,
 18940,
 18941,
 18942,
 18944,
 18947,
 18948,
 18949,
 18950,
 18951,
 18952,
 18953,
 18954,
 18955,
 18956,
 18958,
 18959,
 18960,
 18961,
 18964,
 18965,
 18966,
 18968,
 18969,
 18970,
 18972,
 18974,
 18978,
 18979,
 18981,
 18982,
 18986,
 18987,
 18988,
 18989,
 18990,
 18991,
 18994,
 18997,
 19000,
 19002,
 19003,
 19004,
 19005,
 19006,
 19007,
 19008,
 19009,
 19011,
 19012,
 19016,
 19018,
 19019,
 19020,
 19022,
 19026,
 19027,
 19029,
 19030,
 19031,
 19033,
 19034,
 19035,
 19036,
 19037,
 19038,
 19040,
 19043,
 19044,
 19048,
 19049,
 19051,
 19052,
 19053,
 19057,
 19058,
 19059,
 19060,
 19061,
 19062,
 19063,
 19064,
 19065,
 19066,
 19067,
 19068,
 19069,
 19070,
 19071,
 19072,
 19075,
 19076,
 19077,
 19078,
 19081,
 19082,
 19083,
 19084,
 19088,
 19091,
 19092,
 19107,
 19108,
 19109,
 19110,
 19111,
 19112,
 19115,
 19116,
 19117,
 19118,
 19120,
 19121,
 19122,
 19124,
 19126,
 19128,
 19129,
 19131,
 19132,
 19133,
 19134,
 19135,
 19137,
 19138,
 19141,
 19143,
 19145,
 19147,
 19148,
 19149,
 19151,
 19152,
 19156,
 19157,
 19158,
 19160,
 19162,
 19163,
 19169,
 19170,
 19171,
 19181,
 19182,
 19189,
 19190,
 19191,
 19192,
 19193,
 19194,
 19196,
 19197,
 19198,
 19199,
 19200,
 19201,
 19203,
 19205,
 19207,
 19209,
 19210,
 19212,
 19223,
 19224,
 19226,
 19228,
 19229,
 19232,
 19234,
 19235,
 19236,
 19238,
 19239,
 19240,
 19241,
 19242,
 19243,
 19244,
 19245,
 19248,
 19249,
 19250,
 19251,
 19252,
 19253,
 19256,
 19257,
 19258,
 19260,
 19262,
 19263,
 19265,
 19269,
 19270,
 19271,
 19272,
 19273,
 19275,
 19276,
 19277,
 19279,
 19280,
 19282,
 19288,
 19291,
 19292,
 19293,
 19294,
 19296,
 19298,
 19299,
 19300,
 19302,
 19303,
 19304,
 19310,
 19311,
 19312,
 19313,
 19315,
 19316,
 19317,
 19319,
 19320,
 19323,
 19324,
 19325,
 19326,
 19328,
 19330,
 19331,
 19334,
 19335,
 19343,
 19345,
 19346,
 19347,
 19348,
 19349,
 19350,
 19352,
 19354,
 19356,
 19357,
 19360,
 19362,
 19363,
 19364,
 19365,
 19366,
 19367,
 19371,
 19372,
 19374,
 19375,
 19378,
 19379,
 19380,
 19382,
 19383,
 19384,
 19389,
 19390,
 19392,
 19395,
 19396,
 19400,
 19401,
 19405,
 19409,
 19410,
 19411,
 19412,
 19413,
 19414,
 19415,
 19416,
 19417,
 19418,
 19419,
 19420,
 19421,
 19425,
 19426,
 19427,
 19428,
 19429,
 19432,
 19434,
 19435,
 19436,
 19438,
 19439,
 19441,
 19442,
 19445,
 19446,
 19448,
 19449,
 19450,
 19452,
 19453,
 19454,
 19457,
 19458,
 19459,
 19460,
 19461,
 19462,
 19463,
 19464,
 19465,
 19466,
 19467,
 19468,
 19470,
 19471,
 19472,
 19473,
 19475,
 19476}

In [11]:
df3 = df.copy()

missing_ids = set(df1['id']) - set(df['id'])

# Filter df1 to get only records with missing IDs
df1_new = df1[df1['id'].isin(missing_ids)]

# Concatenate df3 (original df) with the filtered df1_new
df3 = pd.concat([df3, df1_new], ignore_index=True)

# Sort by ID (optional)
df3 = df3.sort_values('id').reset_index(drop=True)

In [12]:
df3.tail()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ELVIS_USER_CHANGE_4_C_REASON_,ELVIS_USER_CHANGE_5_C_DATE_,ELVIS_USER_CHANGE_5_C_FIELD_,ELVIS_USER_CHANGE_5_C_REASON_,ELVIS_USER_CHANGE_6_C_DATE_,ELVIS_USER_CHANGE_6_C_FIELD_,ELVIS_USER_CHANGE_6_C_REASON_,ELVIS_USER_CHANGE_7_C_DATE_,ELVIS_USER_CHANGE_7_C_FIELD_,ELVIS_USER_CHANGE_7_C_REASON_
11444,19472,2025-03-02 15:42:37,75,en,2025-03-02 15:21:45,2025-03-02 15:42:37,172.59.203.57,https://tucson-od.etc-research.com/index.php/s...,-25200,CDM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11445,19473,2025-03-02 15:44:36,75,en,2025-03-02 15:26:36,2025-03-02 15:44:36,172.59.203.14,https://tucson-od.etc-research.com/,-25200,ACS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11446,19475,2025-03-02 16:08:37,75,en,2025-03-02 15:44:42,2025-03-02 16:08:37,172.59.202.170,https://tucson-od.etc-research.com/index.php/s...,-25200,ACS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11447,19476,2025-03-02 16:24:21,75,en,2025-03-02 16:20:06,2025-03-02 16:24:21,172.59.203.242,https://tucson-od.etc-research.com/index.php/s...,-25200,ACS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11448,1000001,2025-01-30 12:43:03,75,en,2025-01-30 12:40:17,2025-01-30 12:43:03,108.167.70.161,NaN,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# df3.to_csv("Updated Columns.csv",index=False)

In [16]:
# df3.drop_duplicates(subset=['id'],inplace=True)

In [17]:
# df3.shape

(11397, 1374)

In [33]:
# # Get matching columns using your function
# matching_cols_df1 = check_all_characters_present(df2, df.columns)
# matching_cols_df = check_all_characters_present(df, df1.columns)

# # Create column mapping without suffixes
# column_mapping_df1_to_df = dict(zip(matching_cols_df1, matching_cols_df))

# # Rename df1 columns to match df where possible
# df1_renamed = df1.rename(columns=column_mapping_df1_to_df)

# # Get all unique columns from both dataframes
# all_columns = list(set(df.columns) | set(df1_renamed.columns))

# # Perform merge without suffixes, prioritizing df1 (left) values
# result_df = pd.merge(
#     df1_renamed,
#     df,
#     on='id',
#     how='outer',  # Keep all records from both
#     suffixes=('', '_temp')  # Temporary suffix for df columns
# )

# # For columns that got a _temp suffix, use the original column values from df1 where available
# for col in all_columns:
#     if col + '_temp' in result_df.columns:
#         # Where df1 had values, use them; otherwise keep df values
#         result_df[col] = result_df[col].fillna(result_df[col + '_temp'])
#         # Drop the temporary suffixed column
#         result_df = result_df.drop(columns=[col + '_temp'])

# # Ensure all columns from both dataframes are present
# for col in all_columns:
#     if col not in result_df.columns:
#         if col in df1_renamed.columns:
#             result_df[col] = df1_renamed[col]
#         elif col in df.columns:
#             result_df[col] = df[col]

In [34]:
# result_df.drop_duplicates(subset=['id'],inplace=True)

In [35]:
# result_df.to_csv('Merged Elvis Non Elvis DF.csv',index=False)

In [13]:
# result_df.shape

(11397, 1377)

In [15]:
# # Get matching columns using your function
# matching_cols_df1 = check_all_characters_present(df1, df.columns)
# matching_cols_df = check_all_characters_present(df, df1.columns)

# # Create column mapping without suffixes
# column_mapping_df1_to_df = dict(zip(matching_cols_df1, matching_cols_df))

# # Rename df1 columns to match df where possible
# df1_renamed = df1.rename(columns=column_mapping_df1_to_df)

# # Get the maximum ID from df
# max_df_id = df['id'].max()

# # Filter df1 to keep only rows where id is less than max_df_id
# df1_filtered = df1_renamed[df1_renamed['id'] < max_df_id]

# # Get all unique columns from both dataframes
# all_columns = list(set(df.columns) | set(df1_filtered.columns))

# # Perform merge without suffixes
# result_df = pd.merge(
#     df,
#     df1_filtered,
#     on='id',
#     how='outer',  # Keep all records from both that match our criteria
#     suffixes=('', '_temp')  # Temporary suffix for df columns
# )

# # For columns that got a _temp suffix, use the original column values from df1 where available
# for col in all_columns:
#     if col + '_temp' in result_df.columns:
#         # Where df1 had values, use them; otherwise keep df values
#         result_df[col] = result_df[col].fillna(result_df[col + '_temp'])
#         # Drop the temporary suffixed column
#         result_df = result_df.drop(columns=[col + '_temp'])

# # Ensure all columns from both dataframes are present
# for col in all_columns:
#     if col not in result_df.columns:
#         if col in df1_filtered.columns:
#             result_df[col] = df1_filtered[col]
#         elif col in df.columns:
#             result_df[col] = df[col]

In [16]:
# result_df

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ELVIS_USER_CHANGE_4_C_REASON_,ELVIS_USER_CHANGE_5_C_DATE_,ELVIS_USER_CHANGE_5_C_FIELD_,ELVIS_USER_CHANGE_5_C_REASON_,ELVIS_USER_CHANGE_6_C_DATE_,ELVIS_USER_CHANGE_6_C_FIELD_,ELVIS_USER_CHANGE_6_C_REASON_,ELVIS_USER_CHANGE_7_C_DATE_,ELVIS_USER_CHANGE_7_C_FIELD_,ELVIS_USER_CHANGE_7_C_REASON_
0,35,2025-01-16 00:06:57,75.0,en,2025-01-16 00:00:05,2025-02-03 01:52:53,110.226.124.133,https://tucson-od.etc-research.com/index.php/a...,-25200.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,35,2025-01-16 00:06:57,75.0,en,2025-01-16 00:00:05,2025-02-03 01:52:53,110.226.124.133,https://tucson-od.etc-research.com/index.php/a...,-25200.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,58,2025-01-17 07:42:29,75.0,en,2025-01-17 07:39:02,2025-01-23 02:50:37,70.113.126.123,https://tucson-od.etc-research.com/,-25200.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,58,2025-01-17 07:42:29,75.0,en,2025-01-17 07:39:02,2025-01-23 02:50:37,70.113.126.123,https://tucson-od.etc-research.com/,-25200.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,150,2025-01-22 07:31:48,75.0,en,2025-01-22 07:17:33,2025-01-22 07:31:48,172.59.203.51,https://tucson-od.etc-research.com/,-25200.0,SLE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11444,19472,2025-03-02 15:42:37,75.0,en,2025-03-02 15:21:45,2025-03-02 15:42:37,172.59.203.57,https://tucson-od.etc-research.com/index.php/s...,-25200.0,CDM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11445,19473,2025-03-02 15:44:36,75.0,en,2025-03-02 15:26:36,2025-03-02 15:44:36,172.59.203.14,https://tucson-od.etc-research.com/,-25200.0,ACS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11446,19475,2025-03-02 16:08:37,75.0,en,2025-03-02 15:44:42,2025-03-02 16:08:37,172.59.202.170,https://tucson-od.etc-research.com/index.php/s...,-25200.0,ACS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11447,19476,2025-03-02 16:24:21,75.0,en,2025-03-02 16:20:06,2025-03-02 16:24:21,172.59.203.242,https://tucson-od.etc-research.com/index.php/s...,-25200.0,ACS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11448,1000001,2025-01-30 12:43:03,75.0,en,2025-01-30 12:40:17,2025-01-30 12:43:03,108.167.70.161,NaN,-25200.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# result_df.drop_duplicates(subset=['id'],inplace=True)

In [18]:
# result_df.shape

(11397, 1377)

In [19]:
# missing_ids = set(result_df['id']) - set(df['id'])

In [20]:
# missing_ids

{18050,
 18052,
 18053,
 18054,
 18055,
 18056,
 18057,
 18058,
 18059,
 18060,
 18062,
 18064,
 18065,
 18066,
 18070,
 18071,
 18072,
 18073,
 18075,
 18076,
 18077,
 18078,
 18080,
 18081,
 18082,
 18084,
 18092,
 18095,
 18096,
 18097,
 18099,
 18100,
 18101,
 18102,
 18104,
 18105,
 18106,
 18107,
 18109,
 18110,
 18111,
 18113,
 18120,
 18121,
 18125,
 18127,
 18128,
 18131,
 18132,
 18133,
 18136,
 18138,
 18139,
 18140,
 18141,
 18142,
 18144,
 18146,
 18147,
 18149,
 18150,
 18152,
 18153,
 18154,
 18155,
 18156,
 18157,
 18158,
 18159,
 18160,
 18164,
 18165,
 18168,
 18169,
 18172,
 18173,
 18174,
 18177,
 18179,
 18184,
 18187,
 18188,
 18190,
 18193,
 18194,
 18195,
 18200,
 18201,
 18203,
 18205,
 18206,
 18207,
 18210,
 18211,
 18213,
 18218,
 18219,
 18220,
 18223,
 18224,
 18225,
 18226,
 18228,
 18229,
 18230,
 18231,
 18235,
 18236,
 18237,
 18238,
 18239,
 18244,
 18245,
 18248,
 18249,
 18251,
 18254,
 18255,
 18256,
 18257,
 18261,
 18262,
 18263,
 18264,
 18266,
 18267,
 18269,
 18270,
 18272,
 18275,
 18276,
 18277,
 18278,
 18281,
 18282,
 18284,
 18286,
 18288,
 18291,
 18292,
 18293,
 18300,
 18302,
 18304,
 18305,
 18306,
 18308,
 18309,
 18310,
 18314,
 18315,
 18317,
 18318,
 18319,
 18321,
 18322,
 18323,
 18325,
 18326,
 18328,
 18330,
 18331,
 18332,
 18334,
 18335,
 18337,
 18338,
 18339,
 18340,
 18341,
 18347,
 18348,
 18349,
 18351,
 18352,
 18353,
 18354,
 18355,
 18356,
 18357,
 18359,
 18360,
 18362,
 18365,
 18367,
 18372,
 18373,
 18374,
 18380,
 18381,
 18382,
 18383,
 18385,
 18387,
 18388,
 18391,
 18392,
 18393,
 18394,
 18395,
 18396,
 18397,
 18398,
 18399,
 18400,
 18401,
 18402,
 18403,
 18404,
 18405,
 18407,
 18408,
 18410,
 18411,
 18412,
 18413,
 18414,
 18415,
 18416,
 18418,
 18420,
 18421,
 18422,
 18423,
 18424,
 18425,
 18426,
 18427,
 18428,
 18429,
 18430,
 18431,
 18432,
 18433,
 18434,
 18435,
 18436,
 18437,
 18438,
 18439,
 18444,
 18445,
 18446,
 18447,
 18448,
 18449,
 18450,
 18451,
 18454,
 18455,
 18458,
 18459,
 18460,
 18461,
 18462,
 18463,
 18464,
 18465,
 18466,
 18468,
 18469,
 18470,
 18472,
 18473,
 18475,
 18478,
 18480,
 18481,
 18482,
 18484,
 18485,
 18486,
 18487,
 18488,
 18489,
 18493,
 18495,
 18497,
 18499,
 18500,
 18502,
 18503,
 18505,
 18506,
 18507,
 18508,
 18510,
 18512,
 18513,
 18514,
 18515,
 18516,
 18518,
 18520,
 18521,
 18523,
 18524,
 18525,
 18526,
 18528,
 18531,
 18532,
 18533,
 18535,
 18536,
 18539,
 18540,
 18541,
 18542,
 18543,
 18544,
 18545,
 18546,
 18547,
 18550,
 18553,
 18560,
 18561,
 18562,
 18565,
 18568,
 18569,
 18570,
 18571,
 18572,
 18573,
 18574,
 18575,
 18579,
 18581,
 18582,
 18583,
 18584,
 18585,
 18587,
 18588,
 18590,
 18591,
 18593,
 18594,
 18603,
 18604,
 18605,
 18606,
 18607,
 18609,
 18610,
 18611,
 18613,
 18614,
 18619,
 18620,
 18621,
 18622,
 18623,
 18624,
 18625,
 18626,
 18627,
 18628,
 18629,
 18630,
 18634,
 18635,
 18636,
 18638,
 18639,
 18640,
 18646,
 18648,
 18651,
 18652,
 18653,
 18654,
 18656,
 18657,
 18660,
 18661,
 18664,
 18665,
 18666,
 18667,
 18669,
 18670,
 18671,
 18672,
 18675,
 18676,
 18677,
 18678,
 18680,
 18684,
 18685,
 18686,
 18687,
 18688,
 18689,
 18693,
 18696,
 18697,
 18699,
 18701,
 18702,
 18703,
 18704,
 18707,
 18708,
 18710,
 18716,
 18719,
 18722,
 18723,
 18724,
 18726,
 18727,
 18728,
 18730,
 18731,
 18732,
 18734,
 18735,
 18736,
 18737,
 18739,
 18740,
 18744,
 18745,
 18747,
 18748,
 18751,
 18752,
 18753,
 18755,
 18757,
 18758,
 18759,
 18760,
 18761,
 18762,
 18763,
 18765,
 18766,
 18767,
 18768,
 18769,
 18771,
 18772,
 18773,
 18775,
 18776,
 18777,
 18778,
 18779,
 18780,
 18782,
 18783,
 18785,
 18786,
 18789,
 18790,
 18791,
 18793,
 18794,
 18795,
 18796,
 18801,
 18802,
 18803,
 18804,
 18805,
 18808,
 18810,
 18811,
 18812,
 18813,
 18814,
 18815,
 18817,
 18818,
 18820,
 18821,
 18822,
 18823,
 18825,
 18826,
 18830,
 18831,
 18832,
 18833,
 18835,
 18836,
 18837,
 18838,
 18839,
 18842,
 18844,
 18845,
 18846,
 18847,
 18848,
 18849,
 18850,
 18851,
 18852,
 18853,
 18856,
 18858,
 18859,
 18861,
 18862,
 18863,
 18864,
 18865,
 18866,
 18869,
 18870,
 18871,
 18873,
 18874,
 18876,
 18877,
 18878,
 18879,
 18880,
 18881,
 18883,
 18889,
 18890,
 18891,
 18892,
 18894,
 18895,
 18896,
 18897,
 18899,
 18900,
 18903,
 18904,
 18905,
 18906,
 18907,
 18910,
 18911,
 18912,
 18915,
 18917,
 18918,
 18920,
 18923,
 18926,
 18929,
 18932,
 18933,
 18937,
 18938,
 18939,
 18940,
 18941,
 18942,
 18944,
 18947,
 18948,
 18949,
 18950,
 18951,
 18952,
 18953,
 18954,
 18955,
 18956,
 18958,
 18959,
 18960,
 18961,
 18964,
 18965,
 18966,
 18968,
 18969,
 18970,
 18972,
 18974,
 18978,
 18979,
 18981,
 18982,
 18986,
 18987,
 18988,
 18989,
 18990,
 18991,
 18994,
 18997,
 19000,
 19002,
 19003,
 19004,
 19005,
 19006,
 19007,
 19008,
 19009,
 19011,
 19012,
 19016,
 19018,
 19019,
 19020,
 19022,
 19026,
 19027,
 19029,
 19030,
 19031,
 19033,
 19034,
 19035,
 19036,
 19037,
 19038,
 19040,
 19043,
 19044,
 19048,
 19049,
 19051,
 19052,
 19053,
 19057,
 19058,
 19059,
 19060,
 19061,
 19062,
 19063,
 19064,
 19065,
 19066,
 19067,
 19068,
 19069,
 19070,
 19071,
 19072,
 19075,
 19076,
 19077,
 19078,
 19081,
 19082,
 19083,
 19084,
 19088,
 19091,
 19092,
 19107,
 19108,
 19109,
 19110,
 19111,
 19112,
 19115,
 19116,
 19117,
 19118,
 19120,
 19121,
 19122,
 19124,
 19126,
 19128,
 19129,
 19131,
 19132,
 19133,
 19134,
 19135,
 19137,
 19138,
 19141,
 19143,
 19145,
 19147,
 19148,
 19149,
 19151,
 19152,
 19156,
 19157,
 19158,
 19160,
 19162,
 19163,
 19169,
 19170,
 19171,
 19181,
 19182,
 19189,
 19190,
 19191,
 19192,
 19193,
 19194,
 19196,
 19197,
 19198,
 19199,
 19200,
 19201,
 19203,
 19205,
 19207,
 19209,
 19210,
 19212,
 19223,
 19224,
 19226,
 19228,
 19229,
 19232,
 19234,
 19235,
 19236,
 19238,
 19239,
 19240,
 19241,
 19242,
 19243,
 19244,
 19245,
 19248,
 19249,
 19250,
 19251,
 19252,
 19253,
 19256,
 19257,
 19258,
 19260,
 19262,
 19263,
 19265,
 19269,
 19270,
 19271,
 19272,
 19273,
 19275,
 19276,
 19277,
 19279,
 19280,
 19282,
 19288,
 19291,
 19292,
 19293,
 19294,
 19296,
 19298,
 19299,
 19300,
 19302,
 19303,
 19304,
 19310,
 19311,
 19312,
 19313,
 19315,
 19316,
 19317,
 19319,
 19320,
 19323,
 19324,
 19325,
 19326,
 19328,
 19330,
 19331,
 19334,
 19335,
 19343,
 19345,
 19346,
 19347,
 19348,
 19349,
 19350,
 19352,
 19354,
 19356,
 19357,
 19360,
 19362,
 19363,
 19364,
 19365,
 19366,
 19367,
 19371,
 19372,
 19374,
 19375,
 19378,
 19379,
 19380,
 19382,
 19383,
 19384,
 19389,
 19390,
 19392,
 19395,
 19396,
 19400,
 19401,
 19405,
 19409,
 19410,
 19411,
 19412,
 19413,
 19414,
 19415,
 19416,
 19417,
 19418,
 19419,
 19420,
 19421,
 19425,
 19426,
 19427,
 19428,
 19429,
 19432,
 19434,
 19435,
 19436,
 19438,
 19439,
 19441,
 19442,
 19445,
 19446,
 19448,
 19449,
 19450,
 19452,
 19453,
 19454,
 19457,
 19458,
 19459,
 19460,
 19461,
 19462,
 19463,
 19464,
 19465,
 19466,
 19467,
 19468,
 19470,
 19471,
 19472,
 19473,
 19475,
 19476}

In [21]:
# missing_ids = set(df['id']) - set(result_df['id'])

In [22]:
# missing_ids

set()

In [23]:
# result_df.to_csv('Merged Databases Data2.csv',index=False)

In [24]:
# def clean_string(s):
#     return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()
# def check_all_characters_present(df, columns_to_check):
#     def clean_string(s):
#         return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()
    
#     df_columns_lower = [clean_string(column) for column in df.columns]
#     columns_to_check_lower = [clean_string(column) for column in columns_to_check]
#     matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]
#     return matching_columns

# # Create a dictionary to map df1 column names to df column names
# column_mapping = {}
# for df1_col in df1.columns:
#     cleaned_df1_col = clean_string(df1_col)
#     for df_col in df.columns:
#         if cleaned_df1_col == clean_string(df_col):
#             column_mapping[df1_col] = df_col
#             break  # Move to next df1 column once we find a match

# # Rename df1 columns to match df column names exactly
# df1_renamed = df1.rename(columns=column_mapping)

In [26]:
# df1_renamed[df1_renamed['id']==18050][['id','ROUTE_SURVEYEDCode','ROUTE_SURVEYED']]

          id ROUTE_SURVEYEDCode                          ROUTE_SURVEYED
10519  18050        SUN_2_17_00  17 - Country Club/29th St. - NORTHWEST

In [27]:
# all_columns = list(set(df.columns) | set(df1_filtered.columns))

In [28]:
# result_df = pd.merge(
#     df,
#     df1_filtered,
#     on='id',
#     how='outer',
#     suffixes=('', '_temp')
# )

# # Resolve columns with temporary suffix
# for col in all_columns:
#     if col + '_temp' in result_df.columns:
#         result_df[col] = result_df[col].fillna(result_df[col + '_temp'])
#         result_df = result_df.drop(columns=[col + '_temp'])

# # Ensure all columns are present
# for col in all_columns:
#     if col not in result_df.columns:
#         if col in df1_filtered.columns:
#             result_df[col] = df1_filtered[col]
#         elif col in df.columns:
#             result_df[col] = df[col]

In [30]:
# result_df.to_csv('Merged Databases Data2.csv',index=False)