In [1]:
import pandas as pd
import openpyxl 
import os
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl import Workbook
import warnings

warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
details_file = 'details_project_od_SantaClarita (1).xlsx'
od_sample_plan_file = 'Santa Clarita Sample Plan 20240126.xlsx'
cr_file = 'project_CR_Santa Clarita.xlsx'
# check if cr_target_directory exists and if not create it
cr_target_directory = 'Processed_CR_dir'
if not os.path.exists(cr_target_directory):
    os.makedirs(cr_target_directory)
    


region = 'SantaClarita'

In [4]:
cr_wb = openpyxl.load_workbook(cr_file)
details_wb = openpyxl.load_workbook(details_file, data_only=True)
#od_sample_plan_wb = openpyxl.load_workbook(od_sample_plan_file, data_only=True, header = 3)

#
#sample_plan_df = pd.read_excel(od_sample_plan_file, sheet_name='Bus', header=3)


#sp = pd.read_excel(od_sample_plan_file, sheet_name='Bus', header=3)
try:
    sp = pd.read_excel(od_sample_plan_file, sheet_name='Sheet1', header=2)
except:
    sp = pd.read_excel(od_sample_plan_file, sheet_name='Weekday', header=2)

sp.head()

,Unnamed: 0,Ridership Data,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Sampling Goals,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Surveys Collected,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Surveys Remaining,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30
0,Route_Direction,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Ridership,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,NaN,NaN,NaN,NaN,NaN,NaN
1,1 - Outbound - To Castaic,37.935296,51.856867,29.527491,21.425711,140.745365,221.29465,1.896765,2.592843,1.476375,1.071286,7.037268,29.874778,4,11,4,5,24,37,0,0,0,0,0,0,1 - Outbound - To Castaic,4.0,11.0,4.0,5.0,NaN
2,1 - Inbound - To McBean,12.215236,25.141432,30.674587,12.51803,80.549285,NaN,0.610762,1.257072,1.533729,0.625901,4.027464,NaN,1,2,8,2,13,NaN,0,0,0,0,0,NaN,1 - Inbound - To McBean,1.0,2.0,8.0,2.0,NaN
3,2 - Outbound - To Val Verde,31.951438,25.617013,20.339237,12.443138,90.350826,164.04324,1.597572,1.280851,1.016962,0.622157,4.517541,22.145837,3,3,5,1,12,24,0,0,0,0,0,0,2 - Outbound - To Val Verde,3.0,3.0,5.0,1.0,
4,2 - Inbound - To McBean,13.938558,20.350662,28.379016,11.024178,73.692414,NaN,0.696928,1.017533,1.418951,0.551209,3.684621,NaN,5,4,1,2,12,NaN,0,0,0.418951,0,0.418951,NaN,2 - Inbound - To McBean,5.0,4.0,0.0,2.0,

In [5]:
sp.columns

Index(['Unnamed: 0', 'Ridership Data', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Sampling Goals',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Surveys Collected', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Surveys Remaining', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30'],
      dtype='object')

In [6]:
sample_col=sp.columns.get_loc('Sampling Goals')
sample_col

7

In [7]:
sampling_goals_indexs=[sample_col,sample_col+1,sample_col+2,sample_col+3,sample_col+4,sample_col+5]
sampling_goals_indexs

[7, 8, 9, 10, 11, 12]

In [8]:
new_sp=sp.iloc[:-3,[0,*sampling_goals_indexs]]

In [9]:
new_sp.columns = new_sp.iloc[0]
new_sp = new_sp[1:]

In [10]:

new_sp.reset_index(inplace=True,drop=True)
new_sp

,Route_Direction,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys
0,1 - Outbound - To Castaic,1.896765,2.592843,1.476375,1.071286,7.037268,29.874778
1,1 - Inbound - To McBean,0.610762,1.257072,1.533729,0.625901,4.027464,NaN
2,2 - Outbound - To Val Verde,1.597572,1.280851,1.016962,0.622157,4.517541,22.145837
3,2 - Inbound - To McBean,0.696928,1.017533,1.418951,0.551209,3.684621,NaN
4,3 - Outbound - To Seco Canyon,0.553204,0.676035,0.894075,0.884067,3.007381,16.426045
5,3 - Inbound - To Six Flags Magic Mountain,1.079804,0.939968,0.59734,0.459227,3.07634,NaN
6,4 - Outbound - To Newhall,1.690795,3.530684,2.37389,1.207284,8.802653,44.570096
7,4 - Inbound - To Bouquet Canyon/Plum Canyon,0.969202,2.955031,2.385797,1.39476,7.70479,NaN
8,5 - Outbound - To Vasquez Canyon,4.437076,6.241646,4.088108,4.109591,18.876421,101.704011
9,5 - Inbound - To Stevenson Ranch,4.548079,6.970255,4.649874,2.623523,18.791732,NaN
10,6 - Outbound - To Shadow Pines,3.415854,8.48899,6.491409,4.493341,22.889594,130.942892
11,6 - Inbound - To Stevenson Ranch,8.68579,8.441787,5.117228,3.362969,25.607773,NaN
12,7 - Outbound - To Seco Canyon,0.232796,0.89148,0.627879,0.399475,2.15163,14.177693
13,7 - Inbound - To Six Flags Magic Mountain,0.45,1.449789,0.78806,0.411518,3.099367,NaN
14,12 - Outbound - To Plum Canyon,2.902564,5.105794,4.966206,3.725556,16.70012,85.814986
15,12 - Inbound - To McBean,4.877242,4.630907,3.908473,1.666586,15.083208,NaN
16,14 - Outbound - To Newhall,1.353036,3.706749,3.074472,0.909053,9.04331,43.460994
17,14 - Inbound - To Bouquet Canyon & Plum Canyon,0.847222,3.238883,2.104284,0.862966,7.053355,NaN
18,757 - Outbound,0.384649,0.250804,0.221202,0.161059,1.017714,27.629485
19,757 - Inbound,2.506258,2.865766,2.148156,1.695248,9.215429,NaN
20,501 - Outbound,1.012011,1.061628,0,0,2.073639,9.405692
21,501 - Inbound,0,0,0.667816,0.742135,1.409951,NaN
22,502 - Outbound,0.035429,0,0.303472,0.263636,0.602537,4.970715
23,502 - Inbound,1.047563,0,0.102381,0.088525,1.238468,NaN
24,791 - Outbound - To Santa Clarita,0.3854,0.12807,0,0,0.51347,2.905054
25,791 - Inbound - To Warner Center,0,0,0.333725,0.22875,0.562475,NaN
26,792 - Outbound - To Santa Clarita,0.296858,0,0,0,0.296858,2.271165
27,792 - Inbound - To Century City,0,0,0.317784,0.226531,0.544314,NaN
28,794 - Outbound - To Santa Clarita,0.622131,0,0,0,0.622131,3.870814
29,794 - Inbound - To Downtown Los Angeles,0,0,0.367273,0.444231,0.811503,NaN
30,796 - Outbound - To Warner Center,0.987579,0,0,0,0.987579,7.441684
31,796 - Inbound - To Santa Clarita,0,0,1.398809,0.369792,1.768601,NaN
32,797 - Outbound - To Century City,1.945504,0,0,0,1.945504,16.645141
33,797 - Inbound - To Santa Clarita,0,0,2.694683,1.524679,4.219363,NaN
34,799 - Outbound - To Downtown Los Angeles,3.374727,0,0,0,3.374727,16.388832
35,799 - Inbound - To Santa Clarita,0,0,2.321185,0.374026,2.695211,NaN

In [11]:
new_sp.rename(columns={'Route_Direction':'ETC_ROUTE_NAME'},inplace=True)
new_sp

,ETC_ROUTE_NAME,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys
0,1 - Outbound - To Castaic,1.896765,2.592843,1.476375,1.071286,7.037268,29.874778
1,1 - Inbound - To McBean,0.610762,1.257072,1.533729,0.625901,4.027464,NaN
2,2 - Outbound - To Val Verde,1.597572,1.280851,1.016962,0.622157,4.517541,22.145837
3,2 - Inbound - To McBean,0.696928,1.017533,1.418951,0.551209,3.684621,NaN
4,3 - Outbound - To Seco Canyon,0.553204,0.676035,0.894075,0.884067,3.007381,16.426045
5,3 - Inbound - To Six Flags Magic Mountain,1.079804,0.939968,0.59734,0.459227,3.07634,NaN
6,4 - Outbound - To Newhall,1.690795,3.530684,2.37389,1.207284,8.802653,44.570096
7,4 - Inbound - To Bouquet Canyon/Plum Canyon,0.969202,2.955031,2.385797,1.39476,7.70479,NaN
8,5 - Outbound - To Vasquez Canyon,4.437076,6.241646,4.088108,4.109591,18.876421,101.704011
9,5 - Inbound - To Stevenson Ranch,4.548079,6.970255,4.649874,2.623523,18.791732,NaN
10,6 - Outbound - To Shadow Pines,3.415854,8.48899,6.491409,4.493341,22.889594,130.942892
11,6 - Inbound - To Stevenson Ranch,8.68579,8.441787,5.117228,3.362969,25.607773,NaN
12,7 - Outbound - To Seco Canyon,0.232796,0.89148,0.627879,0.399475,2.15163,14.177693
13,7 - Inbound - To Six Flags Magic Mountain,0.45,1.449789,0.78806,0.411518,3.099367,NaN
14,12 - Outbound - To Plum Canyon,2.902564,5.105794,4.966206,3.725556,16.70012,85.814986
15,12 - Inbound - To McBean,4.877242,4.630907,3.908473,1.666586,15.083208,NaN
16,14 - Outbound - To Newhall,1.353036,3.706749,3.074472,0.909053,9.04331,43.460994
17,14 - Inbound - To Bouquet Canyon & Plum Canyon,0.847222,3.238883,2.104284,0.862966,7.053355,NaN
18,757 - Outbound,0.384649,0.250804,0.221202,0.161059,1.017714,27.629485
19,757 - Inbound,2.506258,2.865766,2.148156,1.695248,9.215429,NaN
20,501 - Outbound,1.012011,1.061628,0,0,2.073639,9.405692
21,501 - Inbound,0,0,0.667816,0.742135,1.409951,NaN
22,502 - Outbound,0.035429,0,0.303472,0.263636,0.602537,4.970715
23,502 - Inbound,1.047563,0,0.102381,0.088525,1.238468,NaN
24,791 - Outbound - To Santa Clarita,0.3854,0.12807,0,0,0.51347,2.905054
25,791 - Inbound - To Warner Center,0,0,0.333725,0.22875,0.562475,NaN
26,792 - Outbound - To Santa Clarita,0.296858,0,0,0,0.296858,2.271165
27,792 - Inbound - To Century City,0,0,0.317784,0.226531,0.544314,NaN
28,794 - Outbound - To Santa Clarita,0.622131,0,0,0,0.622131,3.870814
29,794 - Inbound - To Downtown Los Angeles,0,0,0.367273,0.444231,0.811503,NaN
30,796 - Outbound - To Warner Center,0.987579,0,0,0,0.987579,7.441684
31,796 - Inbound - To Santa Clarita,0,0,1.398809,0.369792,1.768601,NaN
32,797 - Outbound - To Century City,1.945504,0,0,0,1.945504,16.645141
33,797 - Inbound - To Santa Clarita,0,0,2.694683,1.524679,4.219363,NaN
34,799 - Outbound - To Downtown Los Angeles,3.374727,0,0,0,3.374727,16.388832
35,799 - Inbound - To Santa Clarita,0,0,2.321185,0.374026,2.695211,NaN

In [12]:
# cr_wb = openpyxl.load_workbook(cr_file)
details_wb = openpyxl.load_workbook(details_file, data_only=True)
# #od_sample_plan_wb = openpyxl.load_workbook(od_sample_plan_file, data_only=True, header = 3)

# #
# #sample_plan_df = pd.read_excel(od_sample_plan_file, sheet_name='Bus', header=3)


# #sp = pd.read_excel(od_sample_plan_file, sheet_name='Bus', header=3)
# try:
#     sp = pd.read_excel(od_sample_plan_file, sheet_name='Sheet1', header=3)
# except:
#     sp = pd.read_excel(od_sample_plan_file, sheet_name='Weekday', header=3)
# #sp list
# sp_list = [sp]

agency_list = ['SAN']
details_sisroutes = pd.read_excel(details_file, sheet_name='SIS_ROUTE')
details_tod = pd.read_excel(details_file, sheet_name='TOD')

route_columns = details_sisroutes[['ETC_ROUTE_ID', 'ETC_ROUTE_NAME']]
route_columns

    ETC_ROUTE_ID                                     ETC_ROUTE_NAME
0     SAN_1_1_01                          1 - Outbound - To Castaic
1     SAN_1_1_00                            1 - Inbound - To McBean
2     SAN_1_2_01                        2 - Outbound - To Val Verde
3     SAN_1_2_00                            2 - Inbound - To McBean
4     SAN_1_3_01                      3 - Outbound - To Seco Canyon
5     SAN_1_3_00          3 - Inbound - To Six Flags Magic Mountain
6     SAN_1_4_01                          4 - Outbound - To Newhall
7     SAN_1_4_00        4 - Inbound - To Bouquet Canyon/Plum Canyon
8     SAN_1_5_01                   5 - Outbound - To Vasquez Canyon
9     SAN_1_5_00                   5 - Inbound - To Stevenson Ranch
10    SAN_1_6_01                     6 - Outbound - To Shadow Pines
11    SAN_1_6_00                   6 - Inbound - To Stevenson Ranch
12    SAN_1_7_01                      7 - Outbound - To Seco Canyon
13    SAN_1_7_00          7 - Inbound - To Six Flags Magic Mountain
14   SAN_1_12_01                     12 - Outbound - To Plum Canyon
15   SAN_1_12_00                           12 - Inbound - To McBean
16   SAN_1_14_01                         14 - Outbound - To Newhall
17   SAN_1_14_00       14 - Inbound - To Bouquet Canyon/Plum Canyon
18  SAN_1_501_01                                     501 - Outbound
19  SAN_1_501_00                                      501 - Inbound
20  SAN_1_502_01                                     502 - Outbound
21  SAN_1_502_00                                      502 - Inbound
22  SAN_1_757_01                         757 - Outbound - To McBean
23  SAN_1_757_00  757 - Inbound - To North Hollywood and Newhall...
24  SAN_1_791_01                  791 - Outbound - To Santa Clarita
25  SAN_1_791_00                   791 - Inbound - To Warner Center
26  SAN_1_792_01                  792 - Outbound - To Santa Clarita
27  SAN_1_792_00                    792 - Inbound - To Century City
28  SAN_1_794_01                  794 - Outbound - To Santa Clarita
29  SAN_1_794_00            794 - Inbound - To Downtown Los Angeles
30  SAN_1_796_01                  796 - Outbound - To Warner Center
31  SAN_1_796_00                   796 - Inbound - To Santa Clarita
32  SAN_1_797_01                   797 - Outbound - To Century City
33  SAN_1_797_00                   797 - Inbound - To Santa Clarita
34  SAN_1_799_01           799 - Outbound - To Downtown Los Angeles
35  SAN_1_799_00                   799 - Inbound - To Santa Clarita

In [13]:
new_sp['Prefix'] = new_sp['ETC_ROUTE_NAME'].str[:9]
route_columns['Prefix'] = route_columns['ETC_ROUTE_NAME'].str[:9]

In [14]:
merged_df = pd.merge(new_sp, route_columns[['ETC_ROUTE_ID', 'ETC_ROUTE_NAME','Prefix']], on='Prefix')

In [15]:
merged_df.drop_duplicates(subset=['ETC_ROUTE_ID'],keep='first',inplace=True)
merged_df.drop(columns=['Prefix','ETC_ROUTE_NAME_y'],inplace=True)
merged_df.rename(columns={"ETC_ROUTE_NAME_x":'LS_NAME','ETC_ROUTE_ID':"LS_NAME_CODE","AM Peak (Before 9:00am)":'AM Peak','Midday (9:00am-1:59pm)':'Midday','PM Peak (2:00-4:59pm)':'PM Peak','Evening (5:00-10:00pm)':'Evening'},inplace=True)

In [16]:
# merged_df.to_csv("SantaClarita WkDAY-Overall.csv",index=False)

In [17]:
merged_df

,LS_NAME,AM Peak,Midday,PM Peak,Evening,Total,Total Surveys,LS_NAME_CODE
0,1 - Outbound - To Castaic,1.896765,2.592843,1.476375,1.071286,7.037268,29.874778,SAN_1_1_01
1,1 - Inbound - To McBean,0.610762,1.257072,1.533729,0.625901,4.027464,NaN,SAN_1_1_00
2,2 - Outbound - To Val Verde,1.597572,1.280851,1.016962,0.622157,4.517541,22.145837,SAN_1_2_01
3,2 - Inbound - To McBean,0.696928,1.017533,1.418951,0.551209,3.684621,NaN,SAN_1_2_00
4,3 - Outbound - To Seco Canyon,0.553204,0.676035,0.894075,0.884067,3.007381,16.426045,SAN_1_3_01
5,3 - Inbound - To Six Flags Magic Mountain,1.079804,0.939968,0.59734,0.459227,3.07634,NaN,SAN_1_3_00
6,4 - Outbound - To Newhall,1.690795,3.530684,2.37389,1.207284,8.802653,44.570096,SAN_1_4_01
7,4 - Inbound - To Bouquet Canyon/Plum Canyon,0.969202,2.955031,2.385797,1.39476,7.70479,NaN,SAN_1_4_00
8,5 - Outbound - To Vasquez Canyon,4.437076,6.241646,4.088108,4.109591,18.876421,101.704011,SAN_1_5_01
9,5 - Inbound - To Stevenson Ranch,4.548079,6.970255,4.649874,2.623523,18.791732,NaN,SAN_1_5_00
10,6 - Outbound - To Shadow Pines,3.415854,8.48899,6.491409,4.493341,22.889594,130.942892,SAN_1_6_01
11,6 - Inbound - To Stevenson Ranch,8.68579,8.441787,5.117228,3.362969,25.607773,NaN,SAN_1_6_00
12,7 - Outbound - To Seco Canyon,0.232796,0.89148,0.627879,0.399475,2.15163,14.177693,SAN_1_7_01
13,7 - Inbound - To Six Flags Magic Mountain,0.45,1.449789,0.78806,0.411518,3.099367,NaN,SAN_1_7_00
14,12 - Outbound - To Plum Canyon,2.902564,5.105794,4.966206,3.725556,16.70012,85.814986,SAN_1_12_01
15,12 - Inbound - To McBean,4.877242,4.630907,3.908473,1.666586,15.083208,NaN,SAN_1_12_00
16,14 - Outbound - To Newhall,1.353036,3.706749,3.074472,0.909053,9.04331,43.460994,SAN_1_14_01
17,14 - Inbound - To Bouquet Canyon & Plum Canyon,0.847222,3.238883,2.104284,0.862966,7.053355,NaN,SAN_1_14_00
18,757 - Outbound,0.384649,0.250804,0.221202,0.161059,1.017714,27.629485,SAN_1_757_01
19,757 - Inbound,2.506258,2.865766,2.148156,1.695248,9.215429,NaN,SAN_1_757_00
20,501 - Outbound,1.012011,1.061628,0,0,2.073639,9.405692,SAN_1_501_01
21,501 - Inbound,0,0,0.667816,0.742135,1.409951,NaN,SAN_1_501_00
22,502 - Outbound,0.035429,0,0.303472,0.263636,0.602537,4.970715,SAN_1_502_01
23,502 - Inbound,1.047563,0,0.102381,0.088525,1.238468,NaN,SAN_1_502_00
24,791 - Outbound - To Santa Clarita,0.3854,0.12807,0,0,0.51347,2.905054,SAN_1_791_01
25,791 - Inbound - To Warner Center,0,0,0.333725,0.22875,0.562475,NaN,SAN_1_791_00
26,792 - Outbound - To Santa Clarita,0.296858,0,0,0,0.296858,2.271165,SAN_1_792_01
27,792 - Inbound - To Century City,0,0,0.317784,0.226531,0.544314,NaN,SAN_1_792_00
28,794 - Outbound - To Santa Clarita,0.622131,0,0,0,0.622131,3.870814,SAN_1_794_01
29,794 - Inbound - To Downtown Los Angeles,0,0,0.367273,0.444231,0.811503,NaN,SAN_1_794_00
30,796 - Outbound - To Warner Center,0.987579,0,0,0,0.987579,7.441684,SAN_1_796_01
31,796 - Inbound - To Santa Clarita,0,0,1.398809,0.369792,1.768601,NaN,SAN_1_796_00
32,797 - Outbound - To Century City,1.945504,0,0,0,1.945504,16.645141,SAN_1_797_01
33,797 - Inbound - To Santa Clarita,0,0,2.694683,1.524679,4.219363,NaN,SAN_1_797_00
34,799 - Outbound - To Downtown Los Angeles,3.374727,0,0,0,3.374727,16.388832,SAN_1_799_01
35,799 - Inbound - To Santa Clarita,0,0,2.321185,0.374026,2.695211,NaN,SAN_1_799_00