In [1]:
import pandas as pd
import openpyxl 
import os
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl import Workbook
import warnings

warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
details_file = 'details_project_od_SantaClarita (1).xlsx'
od_sample_plan_file = 'Santa Clarita Sample Plan 20240126.xlsx'
cr_file = 'project_CR_Santa Clarita.xlsx'
# check if cr_target_directory exists and if not create it
cr_target_directory = 'Processed_CR_dir'
if not os.path.exists(cr_target_directory):
    os.makedirs(cr_target_directory)
    


region = 'SantaClarita'

In [4]:
cr_wb = openpyxl.load_workbook(cr_file)
details_wb = openpyxl.load_workbook(details_file, data_only=True)
#od_sample_plan_wb = openpyxl.load_workbook(od_sample_plan_file, data_only=True, header = 3)

#
#sample_plan_df = pd.read_excel(od_sample_plan_file, sheet_name='Bus', header=3)


#sp = pd.read_excel(od_sample_plan_file, sheet_name='Bus', header=3)
try:
    sp = pd.read_excel(od_sample_plan_file, sheet_name='Sheet1', header=2)
except:
    sp = pd.read_excel(od_sample_plan_file, sheet_name='Weekend', header=2)

sp.head()

,Unnamed: 0,Ridership Data,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Sampling Goals,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Surveys Collected,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Surveys Remaining,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,Route_Direction,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Ridership,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,NaN,NaN,NaN,NaN,NaN
1,1 - Outbound - To Castaic,NaN,NaN,NaN,NaN,0,128,NaN,NaN,NaN,NaN,NaN,6.4,1,3,2,0,6,6,0,0,0,0,0,0.4,1 - Outbound - To Castaic,1.0,3.0,2.0,0.0
2,1 - Inbound - To McBean,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,NaN,1 - Inbound - To McBean,NaN,NaN,NaN,NaN
3,2 - Outbound - To Val Verde,NaN,NaN,NaN,NaN,0,89.5,NaN,NaN,NaN,NaN,NaN,4.475,0,5,0,0,5,5,0,0,0,0,0,0,2 - Outbound - To Val Verde,0.0,5.0,0.0,0.0
4,2 - Inbound - To McBean,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,NaN,2 - Inbound - To McBean,NaN,NaN,NaN,NaN

In [5]:
sp.columns

Index(['Unnamed: 0', 'Ridership Data', 'Unnamed: 2', 'Unnamed: 3',
       'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Sampling Goals',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Surveys Collected', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Surveys Remaining', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29'],
      dtype='object')

In [6]:
sample_col=sp.columns.get_loc('Sampling Goals')
sample_col

7

In [7]:
sampling_goals_indexs=[sample_col,sample_col+1,sample_col+2,sample_col+3,sample_col+4,sample_col+5]
sampling_goals_indexs

[7, 8, 9, 10, 11, 12]

In [8]:
sp

,Unnamed: 0,Ridership Data,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Sampling Goals,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Surveys Collected,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Surveys Remaining,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,Route_Direction,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Ridership,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys,NaN,NaN,NaN,NaN,NaN
1,1 - Outbound - To Castaic,NaN,NaN,NaN,NaN,0,128,NaN,NaN,NaN,NaN,NaN,6.4,1,3,2,0,6,6,0,0,0,0,0,0.4,1 - Outbound - To Castaic,1.0,3.0,2.0,0.0
2,1 - Inbound - To McBean,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,NaN,1 - Inbound - To McBean,NaN,NaN,NaN,NaN
3,2 - Outbound - To Val Verde,NaN,NaN,NaN,NaN,0,89.5,NaN,NaN,NaN,NaN,NaN,4.475,0,5,0,0,5,5,0,0,0,0,0,0,2 - Outbound - To Val Verde,0.0,5.0,0.0,0.0
4,2 - Inbound - To McBean,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,NaN,0,0,0,0,0,NaN,2 - Inbound - To McBean,NaN,NaN,NaN,NaN
5,3 - Outbound - To Seco Canyon,NaN,NaN,NaN,NaN,0,102,NaN,NaN,NaN,NaN,NaN,5.1,0,0,0,0,0,5,0,0,0,0,0,0.1,3 - Outbound - To Seco Canyon,NaN,NaN,NaN,NaN
6,3 - Inbound - To Six Flags Magic Mountain,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,1,0,5,NaN,0,0,0,0,0,NaN,3 - Inbound - To Six Flags Magic Mountain,2.0,2.0,1.0,0.0
7,4 - Outbound - To Newhall,NaN,NaN,NaN,NaN,0,232,NaN,NaN,NaN,NaN,NaN,11.6,0,5,5,0,10,15,0,0,0,0,0,0,4 - Outbound - To Newhall,0.0,5.0,5.0,0.0
8,4 - Inbound - To Bouquet Canyon/Plum Canyon,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,3,2,0,5,NaN,0,0,0,0,0,NaN,4 - Inbound - To Bouquet Canyon/Plum Canyon,0.0,3.0,2.0,0.0
9,5 - Outbound - To Vasquez Canyon,NaN,NaN,NaN,NaN,0,437,NaN,NaN,NaN,NaN,NaN,21.85,0,6,4,0,10,22,0,0,0,0,0,0,5 - Outbound - To Vasquez Canyon,0.0,6.0,4.0,0.0
10,5 - Inbound - To Stevenson Ranch,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,8,3,0,12,NaN,0,0,0,0,0,NaN,5 - Inbound - To Stevenson Ranch,1.0,8.0,3.0,0.0
11,6 - Outbound - To Shadow Pines,NaN,NaN,NaN,NaN,0,653,NaN,NaN,NaN,NaN,NaN,32.65,0,14,4,3,21,44,0,0,0,0,0,0,6 - Outbound - To Shadow Pines,0.0,14.0,4.0,3.0
12,6 - Inbound - To Stevenson Ranch,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,15,7,0,23,NaN,0,0,0,0,0,NaN,6 - Inbound - To Stevenson Ranch,1.0,15.0,7.0,0.0
13,7 - Outbound - To Seco Canyon,NaN,NaN,NaN,NaN,0,87.5,NaN,NaN,NaN,NaN,NaN,4.375,0,0,0,0,0,4,0,0,0,0,0,0.375,7 - Outbound - To Seco Canyon,NaN,NaN,NaN,NaN
14,7 - Inbound - To Six Flags Magic Mountain,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,4,NaN,0,0,0,0,0,NaN,7 - Inbound - To Six Flags Magic Mountain,1.0,1.0,1.0,1.0
15,12 - Outbound - To Plum Canyon,NaN,NaN,NaN,NaN,0,434.5,NaN,NaN,NaN,NaN,NaN,21.725,1,9,3,0,13,25,0,0,0,0,0,0,12 - Outbound - To Plum Canyon,1.0,9.0,3.0,0.0
16,12 - Inbound - To McBean,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,12,0,0,12,NaN,0,0,0,0,0,NaN,12 - Inbound - To McBean,0.0,12.0,0.0,0.0
17,14 - Outbound - To Newhall,NaN,NaN,NaN,NaN,0,219.5,NaN,NaN,NaN,NaN,NaN,10.975,1,3,2,0,6,12,0,0,0,0,0,0,14 - Outbound - To Newhall,1.0,3.0,2.0,0.0
18,14 - Inbound - To Bouquet Canyon & Plum Canyon,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,6,0,0,6,NaN,0,0,0,0,0,NaN,14 - Inbound - To Bouquet Canyon/Plum Canyon,0.0,6.0,0.0,0.0
19,757 - Outbound - To McBean,NaN,NaN,NaN,NaN,0,189.5,NaN,NaN,NaN,NaN,NaN,9.475,7,1,0,0,8,16,0,0,0,0,0,0,757 - Outbound - To McBean,7.0,1.0,0.0,0.0
20,757 - Inbound - To North Hollywood and Newhall...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,4,1,3,8,NaN,0,0,0,0,0,NaN,757 - Inbound - To North Hollywood and Newhall...,0.0,4.0,1.0,3.0
21,501 - Outbound,NaN,NaN,NaN,NaN,0,31,NaN,NaN,NaN,NaN,NaN,1.55,0,1,0,0,1,2,0,0,0,0,0,0,501 - Outbound,0.0,1.0,0.0,0.0
22,501 - Inbound,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1,0,1,NaN,0,0,0,0,0,NaN,501 - Inbound,0.0,0.0,1.0,0.0
23,Totals,0,0,0,0,0,2603.5,0,0,0,0,0,130.175,15,98,36,7,156,156,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total,150,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,NaN,NaN,NaN

In [9]:
new_sp=sp.iloc[:-2,[0,*sampling_goals_indexs]]

In [10]:
new_sp.columns = new_sp.iloc[0]
new_sp = new_sp[1:]

In [11]:

new_sp.reset_index(inplace=True,drop=True)
new_sp

,Route_Direction,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys
0,1 - Outbound - To Castaic,NaN,NaN,NaN,NaN,NaN,6.4
1,1 - Inbound - To McBean,NaN,NaN,NaN,NaN,NaN,NaN
2,2 - Outbound - To Val Verde,NaN,NaN,NaN,NaN,NaN,4.475
3,2 - Inbound - To McBean,NaN,NaN,NaN,NaN,NaN,NaN
4,3 - Outbound - To Seco Canyon,NaN,NaN,NaN,NaN,NaN,5.1
5,3 - Inbound - To Six Flags Magic Mountain,NaN,NaN,NaN,NaN,NaN,NaN
6,4 - Outbound - To Newhall,NaN,NaN,NaN,NaN,NaN,11.6
7,4 - Inbound - To Bouquet Canyon/Plum Canyon,NaN,NaN,NaN,NaN,NaN,NaN
8,5 - Outbound - To Vasquez Canyon,NaN,NaN,NaN,NaN,NaN,21.85
9,5 - Inbound - To Stevenson Ranch,NaN,NaN,NaN,NaN,NaN,NaN
10,6 - Outbound - To Shadow Pines,NaN,NaN,NaN,NaN,NaN,32.65
11,6 - Inbound - To Stevenson Ranch,NaN,NaN,NaN,NaN,NaN,NaN
12,7 - Outbound - To Seco Canyon,NaN,NaN,NaN,NaN,NaN,4.375
13,7 - Inbound - To Six Flags Magic Mountain,NaN,NaN,NaN,NaN,NaN,NaN
14,12 - Outbound - To Plum Canyon,NaN,NaN,NaN,NaN,NaN,21.725
15,12 - Inbound - To McBean,NaN,NaN,NaN,NaN,NaN,NaN
16,14 - Outbound - To Newhall,NaN,NaN,NaN,NaN,NaN,10.975
17,14 - Inbound - To Bouquet Canyon & Plum Canyon,NaN,NaN,NaN,NaN,NaN,NaN
18,757 - Outbound - To McBean,NaN,NaN,NaN,NaN,NaN,9.475
19,757 - Inbound - To North Hollywood and Newhall...,NaN,NaN,NaN,NaN,NaN,NaN
20,501 - Outbound,NaN,NaN,NaN,NaN,NaN,1.55
21,501 - Inbound,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
new_sp.rename(columns={'Route_Direction':'ETC_ROUTE_NAME'},inplace=True)
new_sp

,ETC_ROUTE_NAME,AM Peak (Before 9:00am),Midday (9:00am-1:59pm),PM Peak (2:00-4:59pm),Evening (5:00-10:00pm),Total,Total Surveys
0,1 - Outbound - To Castaic,NaN,NaN,NaN,NaN,NaN,6.4
1,1 - Inbound - To McBean,NaN,NaN,NaN,NaN,NaN,NaN
2,2 - Outbound - To Val Verde,NaN,NaN,NaN,NaN,NaN,4.475
3,2 - Inbound - To McBean,NaN,NaN,NaN,NaN,NaN,NaN
4,3 - Outbound - To Seco Canyon,NaN,NaN,NaN,NaN,NaN,5.1
5,3 - Inbound - To Six Flags Magic Mountain,NaN,NaN,NaN,NaN,NaN,NaN
6,4 - Outbound - To Newhall,NaN,NaN,NaN,NaN,NaN,11.6
7,4 - Inbound - To Bouquet Canyon/Plum Canyon,NaN,NaN,NaN,NaN,NaN,NaN
8,5 - Outbound - To Vasquez Canyon,NaN,NaN,NaN,NaN,NaN,21.85
9,5 - Inbound - To Stevenson Ranch,NaN,NaN,NaN,NaN,NaN,NaN
10,6 - Outbound - To Shadow Pines,NaN,NaN,NaN,NaN,NaN,32.65
11,6 - Inbound - To Stevenson Ranch,NaN,NaN,NaN,NaN,NaN,NaN
12,7 - Outbound - To Seco Canyon,NaN,NaN,NaN,NaN,NaN,4.375
13,7 - Inbound - To Six Flags Magic Mountain,NaN,NaN,NaN,NaN,NaN,NaN
14,12 - Outbound - To Plum Canyon,NaN,NaN,NaN,NaN,NaN,21.725
15,12 - Inbound - To McBean,NaN,NaN,NaN,NaN,NaN,NaN
16,14 - Outbound - To Newhall,NaN,NaN,NaN,NaN,NaN,10.975
17,14 - Inbound - To Bouquet Canyon & Plum Canyon,NaN,NaN,NaN,NaN,NaN,NaN
18,757 - Outbound - To McBean,NaN,NaN,NaN,NaN,NaN,9.475
19,757 - Inbound - To North Hollywood and Newhall...,NaN,NaN,NaN,NaN,NaN,NaN
20,501 - Outbound,NaN,NaN,NaN,NaN,NaN,1.55
21,501 - Inbound,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# cr_wb = openpyxl.load_workbook(cr_file)
details_wb = openpyxl.load_workbook(details_file, data_only=True)
# #od_sample_plan_wb = openpyxl.load_workbook(od_sample_plan_file, data_only=True, header = 3)

# #
# #sample_plan_df = pd.read_excel(od_sample_plan_file, sheet_name='Bus', header=3)


# #sp = pd.read_excel(od_sample_plan_file, sheet_name='Bus', header=3)
# try:
#     sp = pd.read_excel(od_sample_plan_file, sheet_name='Sheet1', header=3)
# except:
#     sp = pd.read_excel(od_sample_plan_file, sheet_name='Weekday', header=3)
# #sp list
# sp_list = [sp]

agency_list = ['SAN']
details_sisroutes = pd.read_excel(details_file, sheet_name='SIS_ROUTE')
details_tod = pd.read_excel(details_file, sheet_name='TOD')

route_columns = details_sisroutes[['ETC_ROUTE_ID', 'ETC_ROUTE_NAME']]
route_columns

    ETC_ROUTE_ID                                     ETC_ROUTE_NAME
0     SAN_1_1_01                          1 - Outbound - To Castaic
1     SAN_1_1_00                            1 - Inbound - To McBean
2     SAN_1_2_01                        2 - Outbound - To Val Verde
3     SAN_1_2_00                            2 - Inbound - To McBean
4     SAN_1_3_01                      3 - Outbound - To Seco Canyon
5     SAN_1_3_00          3 - Inbound - To Six Flags Magic Mountain
6     SAN_1_4_01                          4 - Outbound - To Newhall
7     SAN_1_4_00        4 - Inbound - To Bouquet Canyon/Plum Canyon
8     SAN_1_5_01                   5 - Outbound - To Vasquez Canyon
9     SAN_1_5_00                   5 - Inbound - To Stevenson Ranch
10    SAN_1_6_01                     6 - Outbound - To Shadow Pines
11    SAN_1_6_00                   6 - Inbound - To Stevenson Ranch
12    SAN_1_7_01                      7 - Outbound - To Seco Canyon
13    SAN_1_7_00          7 - Inbound - To Six Flags Magic Mountain
14   SAN_1_12_01                     12 - Outbound - To Plum Canyon
15   SAN_1_12_00                           12 - Inbound - To McBean
16   SAN_1_14_01                         14 - Outbound - To Newhall
17   SAN_1_14_00       14 - Inbound - To Bouquet Canyon/Plum Canyon
18  SAN_1_501_01                                     501 - Outbound
19  SAN_1_501_00                                      501 - Inbound
20  SAN_1_502_01                                     502 - Outbound
21  SAN_1_502_00                                      502 - Inbound
22  SAN_1_757_01                         757 - Outbound - To McBean
23  SAN_1_757_00  757 - Inbound - To North Hollywood and Newhall...
24  SAN_1_791_01                  791 - Outbound - To Santa Clarita
25  SAN_1_791_00                   791 - Inbound - To Warner Center
26  SAN_1_792_01                  792 - Outbound - To Santa Clarita
27  SAN_1_792_00                    792 - Inbound - To Century City
28  SAN_1_794_01                  794 - Outbound - To Santa Clarita
29  SAN_1_794_00            794 - Inbound - To Downtown Los Angeles
30  SAN_1_796_01                  796 - Outbound - To Warner Center
31  SAN_1_796_00                   796 - Inbound - To Santa Clarita
32  SAN_1_797_01                   797 - Outbound - To Century City
33  SAN_1_797_00                   797 - Inbound - To Santa Clarita
34  SAN_1_799_01           799 - Outbound - To Downtown Los Angeles
35  SAN_1_799_00                   799 - Inbound - To Santa Clarita

In [14]:
new_sp['Prefix'] = new_sp['ETC_ROUTE_NAME'].str[:9]
route_columns['Prefix'] = route_columns['ETC_ROUTE_NAME'].str[:9]

In [15]:
merged_df = pd.merge(new_sp, route_columns[['ETC_ROUTE_ID', 'ETC_ROUTE_NAME','Prefix']], on='Prefix')

In [16]:
merged_df.drop_duplicates(subset=['ETC_ROUTE_ID'],keep='first',inplace=True)
merged_df.drop(columns=['Prefix','ETC_ROUTE_NAME_y'],inplace=True)
merged_df.rename(columns={"ETC_ROUTE_NAME_x":'LS_NAME','ETC_ROUTE_ID':"LS_NAME_CODE","AM Peak (Before 9:00am)":'AM Peak','Midday (9:00am-1:59pm)':'Midday','PM Peak (2:00-4:59pm)':'PM Peak','Evening (5:00-10:00pm)':'Evening','Total Surveys':'Weekend Goals'},inplace=True)

In [17]:
merged_df.fillna(0,inplace=True)

In [18]:
# merged_df.to_csv("SantaClarita WkEnd-Overall.csv",index=False)

In [19]:
merged_df

,LS_NAME,AM Peak,Midday,PM Peak,Evening,Total,Weekend Goals,LS_NAME_CODE
0,1 - Outbound - To Castaic,0,0,0,0,0,6.400,SAN_1_1_01
1,1 - Inbound - To McBean,0,0,0,0,0,0.000,SAN_1_1_00
2,2 - Outbound - To Val Verde,0,0,0,0,0,4.475,SAN_1_2_01
3,2 - Inbound - To McBean,0,0,0,0,0,0.000,SAN_1_2_00
4,3 - Outbound - To Seco Canyon,0,0,0,0,0,5.100,SAN_1_3_01
5,3 - Inbound - To Six Flags Magic Mountain,0,0,0,0,0,0.000,SAN_1_3_00
6,4 - Outbound - To Newhall,0,0,0,0,0,11.600,SAN_1_4_01
7,4 - Inbound - To Bouquet Canyon/Plum Canyon,0,0,0,0,0,0.000,SAN_1_4_00
8,5 - Outbound - To Vasquez Canyon,0,0,0,0,0,21.850,SAN_1_5_01
9,5 - Inbound - To Stevenson Ranch,0,0,0,0,0,0.000,SAN_1_5_00
10,6 - Outbound - To Shadow Pines,0,0,0,0,0,32.650,SAN_1_6_01
11,6 - Inbound - To Stevenson Ranch,0,0,0,0,0,0.000,SAN_1_6_00
12,7 - Outbound - To Seco Canyon,0,0,0,0,0,4.375,SAN_1_7_01
13,7 - Inbound - To Six Flags Magic Mountain,0,0,0,0,0,0.000,SAN_1_7_00
14,12 - Outbound - To Plum Canyon,0,0,0,0,0,21.725,SAN_1_12_01
15,12 - Inbound - To McBean,0,0,0,0,0,0.000,SAN_1_12_00
16,14 - Outbound - To Newhall,0,0,0,0,0,10.975,SAN_1_14_01
17,14 - Inbound - To Bouquet Canyon & Plum Canyon,0,0,0,0,0,0.000,SAN_1_14_00
18,757 - Outbound - To McBean,0,0,0,0,0,9.475,SAN_1_757_01
19,757 - Inbound - To North Hollywood and Newhall...,0,0,0,0,0,0.000,SAN_1_757_00
20,501 - Outbound,0,0,0,0,0,1.550,SAN_1_501_01
21,501 - Inbound,0,0,0,0,0,0.000,SAN_1_501_00

In [20]:
wkday_route_df=pd.read_excel('project_CR_Santa Clarita.xlsx',sheet_name='WkDAY-RouteTotal')

In [22]:
wkday_route_df

    SORT SURVEY_ROUTE_CODE  SURVEY_ROUTE  ROUTE_TOTAL
0    1.0           SAN_1_1           1.0    11.064733
1    2.0           SAN_1_2           2.0     8.202162
2    3.0           SAN_1_3           3.0     6.083720
3    4.0           SAN_1_4           4.0    16.507443
4    5.0           SAN_1_5           5.0    37.668152
5    6.0           SAN_1_6           6.0    48.497367
6    7.0           SAN_1_7           7.0     5.250997
7    8.0          SAN_1_12          12.0    31.783328
8    9.0          SAN_1_14          14.0    16.096664
9   10.0         SAN_1_757         757.0    10.233142
10  11.0         SAN_1_501         501.0     3.483590
11  12.0         SAN_1_502         502.0     1.841006
12  13.0         SAN_1_791         791.0     1.075946
13  14.0         SAN_1_792         792.0     0.841172
14  15.0         SAN_1_794         794.0     1.433635
15  16.0         SAN_1_796         796.0     2.756179
16  17.0         SAN_1_797         797.0     6.164867
17  18.0         SAN_1_799         799.0     6.069938
18   NaN               NaN           NaN   191.387710

In [23]:
wkday_route_df.rename(columns={'ROUTE_TOTAL':'CR_Overall_Goal','SURVEY_ROUTE_CODE':'ROUTE_SURVEYEDCode'},inplace=True)

In [25]:
wkday_route_df.dropna(subset=['ROUTE_SURVEYEDCode'],inplace=True)
wkday_route_df

    SORT ROUTE_SURVEYEDCode  SURVEY_ROUTE  CR_Overall_Goal
0    1.0            SAN_1_1           1.0        11.064733
1    2.0            SAN_1_2           2.0         8.202162
2    3.0            SAN_1_3           3.0         6.083720
3    4.0            SAN_1_4           4.0        16.507443
4    5.0            SAN_1_5           5.0        37.668152
5    6.0            SAN_1_6           6.0        48.497367
6    7.0            SAN_1_7           7.0         5.250997
7    8.0           SAN_1_12          12.0        31.783328
8    9.0           SAN_1_14          14.0        16.096664
9   10.0          SAN_1_757         757.0        10.233142
10  11.0          SAN_1_501         501.0         3.483590
11  12.0          SAN_1_502         502.0         1.841006
12  13.0          SAN_1_791         791.0         1.075946
13  14.0          SAN_1_792         792.0         0.841172
14  15.0          SAN_1_794         794.0         1.433635
15  16.0          SAN_1_796         796.0         2.756179
16  17.0          SAN_1_797         797.0         6.164867
17  18.0          SAN_1_799         799.0         6.069938