In [44]:
import numpy as np
import pandas as pd
from geopy.distance import geodesic
import warnings

warnings.filterwarnings('ignore')

In [2]:
def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [114]:
ke_df=pd.read_excel("MUNI_CA_KINGElvis (1).xlsx",sheet_name='Elvis_Review')
df=pd.read_csv('elvismunica2024obweekday_export_odbc(v1).csv')
main_df=pd.read_csv('munica2024obweekday_export_odbc(v1).csv')

In [87]:
ke_df=pd.read_excel("UTA_SLC_KINGElvis (1).xlsx",sheet_name='Elvis_Review')
df=pd.read_csv('elvisutaobweekday2024_export_odbc(v1).csv')
main_df=pd.read_csv('utaobweekday2024_export_odbc(v1).csv')

In [5]:
ke_df=ke_df[ke_df['INTERV_INIT']!=999]
ke_df=ke_df[ke_df['HAVE_5_MIN_FOR_SURVECode']==1]

In [6]:
prev_trip_codes_checks=['tripfirstroutecode','tripsecondroutecode','tripthirdroutecode','tripfourthroutecode']
route_survey_checks=['routesurveyedcode']
next_trip_codes_checks=['tripnextroutecode','tripafterroutecode','trip3rdroutecode','triplast4thrtecode']
prev_trip_codes_columns=check_all_characters_present(df,prev_trip_codes_checks)
route_survey_column=check_all_characters_present(df,route_survey_checks)
next_trip_codes_columns=check_all_characters_present(df,next_trip_codes_checks)
transfer_list_columns=[*prev_trip_codes_columns,*route_survey_column,*next_trip_codes_columns]
transfer_list_columns

['TRIP_FIRST_ROUTECode',
 'TRIP_SECOND_ROUTECode',
 'TRIP_THIRD_ROUTECode',
 'TRIP_FOURTH_ROUTECode',
 'ROUTE_SURVEYEDCode',
 'TRIP_NEXT_ROUTECode',
 'TRIP_AFTER_ROUTECode',
 'TRIP_3RD_ROUTECode',
 'TRIP_LAST4TH_RTECode']

In [7]:
main_prev_trip_codes_checks=['tripfirstroutecode','tripsecondroutecode','tripthirdroutecode','tripfourthroutecode']
main_route_survey_checks=['routesurveyedcode']
main_next_trip_codes_checks=['tripnextroutecode','tripafterroutecode','trip3rdroutecode','triplast4thrtecode']
main_prev_trip_codes_columns=check_all_characters_present(main_df,main_prev_trip_codes_checks)
main_route_survey_column=check_all_characters_present(main_df,main_route_survey_checks)
main_next_trip_codes_columns=check_all_characters_present(main_df,main_next_trip_codes_checks)
main_transfer_list_columns=[*main_prev_trip_codes_columns,*main_route_survey_column,*main_next_trip_codes_columns]
main_transfer_list_columns

['TRIP_FIRST_ROUTE_Code_',
 'TRIP_SECOND_ROUTE_Code_',
 'TRIP_THIRD_ROUTE_Code_',
 'TRIP_FOURTH_ROUTE_Code_',
 'ROUTE_SURVEYED_Code_',
 'TRIP_NEXT_ROUTE_Code_',
 'TRIP_AFTER_ROUTE_Code_',
 'TRIP_3RD_ROUTE_Code_',
 'TRIP_LAST4TH_RTE_Code_']

In [8]:
df[df['id']==6127][transfer_list_columns]

Empty DataFrame
Columns: [TRIP_FIRST_ROUTECode, TRIP_SECOND_ROUTECode, TRIP_THIRD_ROUTECode, TRIP_FOURTH_ROUTECode, ROUTE_SURVEYEDCode, TRIP_NEXT_ROUTECode, TRIP_AFTER_ROUTECode, TRIP_3RD_ROUTECode, TRIP_LAST4TH_RTECode]
Index: []

In [9]:
main_df[main_df['id']==6127][main_transfer_list_columns]

Empty DataFrame
Columns: [TRIP_FIRST_ROUTE_Code_, TRIP_SECOND_ROUTE_Code_, TRIP_THIRD_ROUTE_Code_, TRIP_FOURTH_ROUTE_Code_, ROUTE_SURVEYED_Code_, TRIP_NEXT_ROUTE_Code_, TRIP_AFTER_ROUTE_Code_, TRIP_3RD_ROUTE_Code_, TRIP_LAST4TH_RTE_Code_]
Index: []

In [10]:
test_df=main_df[main_df['id']==6127][main_transfer_list_columns]
test_df

Empty DataFrame
Columns: [TRIP_FIRST_ROUTE_Code_, TRIP_SECOND_ROUTE_Code_, TRIP_THIRD_ROUTE_Code_, TRIP_FOURTH_ROUTE_Code_, ROUTE_SURVEYED_Code_, TRIP_NEXT_ROUTE_Code_, TRIP_AFTER_ROUTE_Code_, TRIP_3RD_ROUTE_Code_, TRIP_LAST4TH_RTE_Code_]
Index: []

In [11]:
test_df['ROUTE_SURVEYED_Code_']=test_df['ROUTE_SURVEYED_Code_'].apply(lambda x : '_'.join(x.split('_')[:-1]))

In [12]:
test_df

Empty DataFrame
Columns: [TRIP_FIRST_ROUTE_Code_, TRIP_SECOND_ROUTE_Code_, TRIP_THIRD_ROUTE_Code_, TRIP_FOURTH_ROUTE_Code_, ROUTE_SURVEYED_Code_, TRIP_NEXT_ROUTE_Code_, TRIP_AFTER_ROUTE_Code_, TRIP_3RD_ROUTE_Code_, TRIP_LAST4TH_RTE_Code_]
Index: []

In [13]:
new_df=pd.merge(df[['id',*transfer_list_columns]],main_df[['id',*main_transfer_list_columns]],on='id',suffixes=('_Elvis', '_Non_Elvis'))
new_df

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_
0,5604.0,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN
1,5605.0,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN
2,5755.0,NaN,NaN,NaN,NaN,UTA_1_209_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_209_01,NaN,NaN,NaN,NaN
3,5824.0,NaN,NaN,NaN,NaN,UTA_1_200_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_200_00,NaN,NaN,NaN,NaN
4,5825.0,NaN,NaN,NaN,NaN,UTA_1_200_01,UTA_1_704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_200_01,UTA_1_704,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,7876.0,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN
1192,7878.0,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN
1193,7879.0,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN
1194,7883.0,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN
1195,7884.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN

In [14]:
# new_df[new_df['id']==6127]
new_df[new_df['id']==6155]

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_
95,6155.0,NaN,NaN,NaN,NaN,UTA_1_703_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_703_00,NaN,NaN,NaN,NaN

In [15]:
new_df[main_transfer_list_columns]

,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_
0,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,UTA_1_209_01,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,UTA_1_200_00,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,UTA_1_200_01,UTA_1_704,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1191,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN
1192,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN
1193,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN
1194,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN
1195,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN

In [16]:
new_df.reset_index(inplace=True,drop=True)

In [17]:
new_df.head()

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_
0,5604.0,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN
1,5605.0,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN
2,5755.0,NaN,NaN,NaN,NaN,UTA_1_209_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_209_01,NaN,NaN,NaN,NaN
3,5824.0,NaN,NaN,NaN,NaN,UTA_1_200_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_200_00,NaN,NaN,NaN,NaN
4,5825.0,NaN,NaN,NaN,NaN,UTA_1_200_01,UTA_1_704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_200_01,UTA_1_704,NaN,NaN,NaN

In [18]:
new_df[main_route_survey_column[0]] = new_df[main_route_survey_column[0]].apply(lambda x: '_'.join(x.split('_')[:-1]))
new_df[route_survey_column[0]] = new_df[route_survey_column[0]].apply(lambda x: '_'.join(x.split('_')[:-1]))

In [19]:
new_df.head()

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_
0,5604.0,NaN,NaN,NaN,NaN,UTA_1_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_1,NaN,NaN,NaN,NaN
1,5605.0,NaN,NaN,NaN,NaN,UTA_1_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_1,NaN,NaN,NaN,NaN
2,5755.0,NaN,NaN,NaN,NaN,UTA_1_209,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_209,NaN,NaN,NaN,NaN
3,5824.0,NaN,NaN,NaN,NaN,UTA_1_200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_200,NaN,NaN,NaN,NaN
4,5825.0,NaN,NaN,NaN,NaN,UTA_1_200,UTA_1_704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_200,UTA_1_704,NaN,NaN,NaN

In [20]:
for index, row in new_df.iterrows():
    main_transferlist=row[main_transfer_list_columns].values
    elvis_transferlist=row[transfer_list_columns].values
    elvis_non_nan_values = [value for value in elvis_transferlist if pd.notna(value)]
    non_nan_values = [value for value in main_transferlist if pd.notna(value)]
    has_duplicates = len(non_nan_values) != len(set(non_nan_values))
    if has_duplicates:
        if len(elvis_non_nan_values)==len(set(non_nan_values)):
            new_df.loc[index,'Duplicate_Route']=1
            new_df.loc[index,'Duplicate_Route_Changed']='Yes'
        else:
            new_df.loc[index,'Duplicate_Route_Changed']='No'
            new_df.loc[index,'Duplicate_Route']=1
    else:
        new_df.loc[index,'Duplicate_Route_Changed']=''
        new_df.loc[index,'Duplicate_Route']=0

In [21]:
new_df[new_df['id']==6127][[*main_transfer_list_columns,'Duplicate_Route','Duplicate_Route_Changed']]

Empty DataFrame
Columns: [TRIP_FIRST_ROUTE_Code_, TRIP_SECOND_ROUTE_Code_, TRIP_THIRD_ROUTE_Code_, TRIP_FOURTH_ROUTE_Code_, ROUTE_SURVEYED_Code_, TRIP_NEXT_ROUTE_Code_, TRIP_AFTER_ROUTE_Code_, TRIP_3RD_ROUTE_Code_, TRIP_LAST4TH_RTE_Code_, Duplicate_Route, Duplicate_Route_Changed]
Index: []

In [22]:
mylist=new_df[main_transfer_list_columns].values[0]

In [23]:
# mylist=new_df[new_df['id']==6127][main_transfer_list_columns].values[0]

In [24]:
non_nan_values = [value for value in mylist if pd.notna(value)]
non_nan_values

['UTA_1_1']

In [25]:
has_duplicates = len(non_nan_values) != len(set(non_nan_values))
has_duplicates

False

In [26]:
if has_duplicates:
    print("Duplicate non-NaN values found.")
else:
    print("No duplicate non-NaN values.")

No duplicate non-NaN values.

In [27]:
test_df=pd.merge(df[['id',*transfer_list_columns]],main_df[['id',*main_transfer_list_columns]],on='id',suffixes=("_e","_ne"))
test_df

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_
0,5604.0,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN
1,5605.0,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_1_01,NaN,NaN,NaN,NaN
2,5755.0,NaN,NaN,NaN,NaN,UTA_1_209_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_209_01,NaN,NaN,NaN,NaN
3,5824.0,NaN,NaN,NaN,NaN,UTA_1_200_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_200_00,NaN,NaN,NaN,NaN
4,5825.0,NaN,NaN,NaN,NaN,UTA_1_200_01,UTA_1_704,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_200_01,UTA_1_704,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1191,7876.0,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN
1192,7878.0,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN
1193,7879.0,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN
1194,7883.0,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN
1195,7884.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN

# Logic For Removal Route Percentage

In [28]:
df=pd.merge(df,ke_df[['id','Final_Usage']],on='id',how='left',indicator=True)
df['Matched'] = (df['_merge'] == 'both').astype(int)
df.drop(columns=['_merge'])
df=df[df['Matched']==1]
df.drop_duplicates(subset=['id'],keep='first',inplace=True)

# getting data from non-elvis database file which matches with KingElvis 
main_df=pd.merge(main_df,ke_df[['id','Final_Usage']],on='id',how='left',indicator=True)
main_df['Matched'] = (main_df['_merge'] == 'both').astype(int)
main_df.drop(columns=['_merge'])
main_df=main_df[main_df['Matched']==1]
main_df.drop_duplicates(subset=['id'],keep='first',inplace=True)

In [29]:
main_df

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,_REVERSE_TRIP,GENERATABLE_TRIPS,Final_Usage,_merge,Matched
33,5948,2024-02-27 14:24:12,76,en,2024-02-27 14:12:08,2024-02-27 14:24:12,172.59.152.37,https://uta-od.etc-research.com/,-25200,FRJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
55,6067,2024-02-27 20:03:44,76,en,2024-02-27 19:54:12,2024-02-27 20:03:44,174.247.147.233,https://uta-od.etc-research.com/index.php/surv...,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
56,6077,2024-02-28 05:21:27,76,en,2024-02-28 05:15:50,2024-02-28 05:21:27,174.247.144.180,https://uta-od.etc-research.com/,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
58,6078,2024-02-28 05:24:34,76,en,2024-02-28 05:16:40,2024-02-28 05:24:34,172.59.152.134,https://uta-od.etc-research.com/,-25200,GMH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
59,6073,2024-02-28 05:25:55,76,en,2024-02-28 05:12:45,2024-02-28 05:25:55,172.59.152.71,https://uta-od.etc-research.com/,-25200,JLF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1189,7878,2024-02-29 22:21:01,76,en,2024-02-29 22:02:24,2024-02-29 22:21:01,172.59.152.232,https://uta-od.etc-research.com/index.php/surv...,-25200,AXV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
1190,7879,2024-02-29 22:23:10,76,en,2024-02-29 22:18:45,2024-02-29 22:23:10,172.59.153.80,https://uta-od.etc-research.com/,-25200,JXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
1191,7874,2024-02-29 23:48:12,76,en,2024-02-29 21:43:08,2024-02-29 23:48:12,174.247.154.240,https://uta-od.etc-research.com/index.php/surv...,-25200,LXS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
1192,7883,2024-03-01 05:53:09,76,en,2024-03-01 05:42:33,2024-03-01 05:53:09,174.204.1.5,https://uta-od.etc-research.com/index.php/surv...,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
1193,7884,2024-03-01 06:03:37,76,en,2024-03-01 05:53:11,2024-03-01 06:03:37,174.204.1.5,https://uta-od.etc-research.com/index.php/surv...,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1

In [30]:
df

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,_REVERSE_TRIP,GENERATABLE_TRIPS,Final_Usage,_merge,Matched
34,5948.0,2024-02-27 14:24:12,76.0,en,2024-02-27 14:12:08,2024-03-03 23:30:00,172.59.152.37,https://uta-od.etc-research.com/,-25200.0,FRJ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
56,6067.0,2024-02-27 20:03:44,76.0,en,2024-02-27 19:54:12,2024-02-27 20:03:44,174.247.147.233,https://uta-od.etc-research.com/index.php/surv...,-25200.0,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
59,6073.0,2024-02-28 05:25:55,76.0,en,2024-02-28 05:12:45,2024-03-03 23:33:50,172.59.152.71,https://uta-od.etc-research.com/,-25200.0,JLF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
60,6077.0,2024-02-28 05:21:27,76.0,en,2024-02-28 05:15:50,2024-02-28 05:21:27,174.247.144.180,https://uta-od.etc-research.com/,-25200.0,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
61,6078.0,2024-02-28 05:24:34,76.0,en,2024-02-28 05:16:40,2024-03-03 23:34:24,172.59.152.134,https://uta-od.etc-research.com/,-25200.0,GMH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1194,7876.0,2024-02-29 22:02:22,76.0,en,2024-02-29 21:57:03,2024-02-29 22:02:22,172.59.152.222,https://uta-od.etc-research.com/,-25200.0,AXV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
1195,7878.0,2024-02-29 22:21:01,76.0,en,2024-02-29 22:02:24,2024-02-29 22:21:01,172.59.152.232,https://uta-od.etc-research.com/index.php/surv...,-25200.0,AXV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
1196,7879.0,2024-02-29 22:23:10,76.0,en,2024-02-29 22:18:45,2024-02-29 22:23:10,172.59.153.80,https://uta-od.etc-research.com/,-25200.0,JXF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
1197,7883.0,2024-03-01 05:53:09,76.0,en,2024-03-01 05:42:33,2024-03-01 05:53:09,174.204.1.5,https://uta-od.etc-research.com/index.php/surv...,-25200.0,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1
1198,7884.0,2024-03-01 06:03:37,76.0,en,2024-03-01 05:53:11,2024-03-01 06:03:37,174.204.1.5,https://uta-od.etc-research.com/index.php/surv...,-25200.0,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Use,both,1

In [31]:
test_df=pd.merge(df[['id',*transfer_list_columns,'Final_Usage']],main_df[['id',*main_transfer_list_columns,'Final_Usage']],on='id',suffixes=('_Elvis', '_Non_Elvis'))
test_df

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,...,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_,Final_Usage_Non_Elvis
0,5948.0,NaN,NaN,NaN,NaN,UTA_1_2_01,UTA_1_470,NaN,NaN,NaN,...,UTA_1_470,NaN,NaN,NaN,UTA_1_2_01,UTA_1_470,NaN,NaN,NaN,Use
1,6067.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use
2,6073.0,NaN,NaN,NaN,NaN,UTA_1_750_01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,UTA_1_750_01,NaN,NaN,NaN,NaN,Use
3,6077.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use
4,6078.0,NaN,NaN,NaN,NaN,UTA_1_220_00,UTA_1_39,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,UTA_1_220_00,UTA_1_39,NaN,NaN,NaN,Use
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,7876.0,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,...,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,Use
963,7878.0,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,Use
964,7879.0,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN,Use
965,7883.0,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,...,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use
966,7884.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use

In [32]:
test_df[(test_df['Final_Usage_Non_Elvis'].str.lower()=='remove')][['id',*transfer_list_columns,*main_transfer_list_columns,'Final_Usage_Non_Elvis']]

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_,Final_Usage_Non_Elvis
14,6097.0,UTA_1_35,NaN,NaN,NaN,UTA_1_703_01,UTA_1_473,NaN,NaN,NaN,UTA_1_35,NaN,NaN,NaN,UTA_1_703_01,UTA_1_473,NaN,NaN,NaN,remove
17,6103.0,NaN,NaN,NaN,NaN,UTA_1_220_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_220_00,NaN,NaN,NaN,NaN,remove
20,6119.0,NaN,NaN,NaN,NaN,UTA_1_701_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_701_00,NaN,NaN,NaN,NaN,remove
27,6139.0,NaN,NaN,NaN,NaN,UTA_1_701_00,UTA_1_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_701_00,UTA_1_9,NaN,NaN,NaN,Remove
33,6149.0,NaN,NaN,NaN,NaN,UTA_1_220_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_220_01,NaN,NaN,NaN,NaN,Remove
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,7702.0,NaN,NaN,NaN,NaN,UTA_1_2_01,UTA_1_750,UTA_1_830X,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_2_01,UTA_1_750,UTA_1_830X,NaN,NaN,Remove
862,7705.0,UTA_1_750,NaN,NaN,NaN,UTA_1_220_01,NaN,NaN,NaN,NaN,UTA_1_750,NaN,NaN,NaN,UTA_1_220_01,NaN,NaN,NaN,NaN,Remove
868,7711.0,NaN,NaN,NaN,NaN,UTA_1_701_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_701_00,NaN,NaN,NaN,NaN,Remove
905,7791.0,NaN,NaN,NaN,NaN,UTA_1_701_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_701_01,NaN,NaN,NaN,NaN,Remove
939,7840.0,UTA_1_750,NaN,NaN,NaN,UTA_1_2_00,NaN,NaN,NaN,NaN,UTA_1_750,NaN,NaN,NaN,UTA_1_2_00,NaN,NaN,NaN,NaN,Remove

In [33]:
for index, row in test_df.iterrows():
    main_transferlist=row[main_transfer_list_columns].values
    elvis_transferlist=row[transfer_list_columns].values
    elvis_non_nan_values = [value for value in elvis_transferlist if pd.notna(value)]
    non_nan_values = [value for value in main_transferlist if pd.notna(value)]
    has_duplicates = len(non_nan_values) != len(set(non_nan_values))
    if has_duplicates:
        test_df.loc[index,'Duplicate_Route']=1
    else:
        test_df.loc[index,'Duplicate_Route']=0

In [34]:
test_df

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,...,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_,Final_Usage_Non_Elvis,Duplicate_Route
0,5948.0,NaN,NaN,NaN,NaN,UTA_1_2_01,UTA_1_470,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_2_01,UTA_1_470,NaN,NaN,NaN,Use,1.0
1,6067.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use,0.0
2,6073.0,NaN,NaN,NaN,NaN,UTA_1_750_01,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_750_01,NaN,NaN,NaN,NaN,Use,0.0
3,6077.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use,0.0
4,6078.0,NaN,NaN,NaN,NaN,UTA_1_220_00,UTA_1_39,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_220_00,UTA_1_39,NaN,NaN,NaN,Use,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,7876.0,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,Use,0.0
963,7878.0,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,Use,0.0
964,7879.0,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN,Use,0.0
965,7883.0,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use,0.0
966,7884.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use,0.0

In [35]:
test_df[(test_df['Final_Usage_Non_Elvis'].str.lower()=='remove')&(test_df['Duplicate_Route']==1)][['id',*transfer_list_columns,*main_transfer_list_columns,'Final_Usage_Non_Elvis']]

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_,Final_Usage_Non_Elvis
237,6563.0,UTA_1_750,NaN,NaN,NaN,UTA_1_701_00,UTA_1_701,UTA_1_750,NaN,NaN,UTA_1_750,NaN,NaN,NaN,UTA_1_701_00,UTA_1_701,UTA_1_750,NaN,NaN,Remove
853,7693.0,NaN,NaN,NaN,NaN,UTA_1_701_00,UTA_1_701,UTA_1_703,NaN,NaN,UTA_1_703,NaN,NaN,NaN,UTA_1_701_00,UTA_1_701,UTA_1_703,NaN,NaN,Remove

In [36]:
test_df[(test_df['Final_Usage_Non_Elvis'].str.lower()=='remove')][['id',*transfer_list_columns,*main_transfer_list_columns,'Final_Usage_Non_Elvis']]

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_,Final_Usage_Non_Elvis
14,6097.0,UTA_1_35,NaN,NaN,NaN,UTA_1_703_01,UTA_1_473,NaN,NaN,NaN,UTA_1_35,NaN,NaN,NaN,UTA_1_703_01,UTA_1_473,NaN,NaN,NaN,remove
17,6103.0,NaN,NaN,NaN,NaN,UTA_1_220_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_220_00,NaN,NaN,NaN,NaN,remove
20,6119.0,NaN,NaN,NaN,NaN,UTA_1_701_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_701_00,NaN,NaN,NaN,NaN,remove
27,6139.0,NaN,NaN,NaN,NaN,UTA_1_701_00,UTA_1_9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_701_00,UTA_1_9,NaN,NaN,NaN,Remove
33,6149.0,NaN,NaN,NaN,NaN,UTA_1_220_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_220_01,NaN,NaN,NaN,NaN,Remove
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,7702.0,NaN,NaN,NaN,NaN,UTA_1_2_01,UTA_1_750,UTA_1_830X,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_2_01,UTA_1_750,UTA_1_830X,NaN,NaN,Remove
862,7705.0,UTA_1_750,NaN,NaN,NaN,UTA_1_220_01,NaN,NaN,NaN,NaN,UTA_1_750,NaN,NaN,NaN,UTA_1_220_01,NaN,NaN,NaN,NaN,Remove
868,7711.0,NaN,NaN,NaN,NaN,UTA_1_701_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_701_00,NaN,NaN,NaN,NaN,Remove
905,7791.0,NaN,NaN,NaN,NaN,UTA_1_701_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_701_01,NaN,NaN,NaN,NaN,Remove
939,7840.0,UTA_1_750,NaN,NaN,NaN,UTA_1_2_00,NaN,NaN,NaN,NaN,UTA_1_750,NaN,NaN,NaN,UTA_1_2_00,NaN,NaN,NaN,NaN,Remove

In [37]:
test_df[(test_df['Final_Usage_Non_Elvis'].str.lower()=='use')][['id',*transfer_list_columns,*main_transfer_list_columns,'Final_Usage_Non_Elvis']]

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,TRIP_FIRST_ROUTE_Code_,TRIP_SECOND_ROUTE_Code_,TRIP_THIRD_ROUTE_Code_,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_,Final_Usage_Non_Elvis
0,5948.0,NaN,NaN,NaN,NaN,UTA_1_2_01,UTA_1_470,NaN,NaN,NaN,UTA_1_470,NaN,NaN,NaN,UTA_1_2_01,UTA_1_470,NaN,NaN,NaN,Use
1,6067.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use
2,6073.0,NaN,NaN,NaN,NaN,UTA_1_750_01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_750_01,NaN,NaN,NaN,NaN,Use
3,6077.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use
4,6078.0,NaN,NaN,NaN,NaN,UTA_1_220_00,UTA_1_39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_220_00,UTA_1_39,NaN,NaN,NaN,Use
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,7876.0,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,UTA_1_830X,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,Use
963,7878.0,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_750_00,NaN,NaN,NaN,NaN,Use
964,7879.0,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_750_00,UTA_1_703,NaN,NaN,NaN,Use
965,7883.0,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,UTA_1_217,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use
966,7884.0,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UTA_1_47_00,NaN,NaN,NaN,NaN,Use

In [115]:
def duplicate_route_information(df,main_df,ke_df):

    ke_df=ke_df[ke_df['INTERV_INIT']!=999]
    ke_df=ke_df[ke_df['HAVE_5_MIN_FOR_SURVECode']==1]

    df=pd.merge(df,ke_df[['id','Final_Usage']],on='id',how='left',indicator=True)
    df['Matched'] = (df['_merge'] == 'both').astype(int)
    df.drop(columns=['_merge'])
    df=df[df['Matched']==1]
    df.drop_duplicates(subset=['id'],keep='first',inplace=True)

    # getting data from non-elvis database file which matches with KingElvis 
    main_df=pd.merge(main_df,ke_df[['id','Final_Usage']],on='id',how='left',indicator=True)
    main_df['Matched'] = (main_df['_merge'] == 'both').astype(int)
    main_df.drop(columns=['_merge'])
    main_df=main_df[main_df['Matched']==1]
    main_df.drop_duplicates(subset=['id'],keep='first',inplace=True)

    # columns from elvis database file
    prev_trip_codes_checks=['tripfirstroutecode','tripsecondroutecode','tripthirdroutecode','tripfourthroutecode']
    route_survey_checks=['routesurveyedcode']
    next_trip_codes_checks=['tripnextroutecode','tripafterroutecode','trip3rdroutecode','triplast4thrtecode']
    prev_trip_codes_columns=check_all_characters_present(df,prev_trip_codes_checks)
    route_survey_column=check_all_characters_present(df,route_survey_checks)
    next_trip_codes_columns=check_all_characters_present(df,next_trip_codes_checks)
    transfer_list_columns=[*prev_trip_codes_columns,*route_survey_column,*next_trip_codes_columns]
    
    # columns from non-elvis database file
    main_prev_trip_codes_checks=['tripfirstroutecode','tripsecondroutecode','tripthirdroutecode','tripfourthroutecode']
    main_route_survey_checks=['routesurveyedcode']
    main_next_trip_codes_checks=['tripnextroutecode','tripafterroutecode','trip3rdroutecode','triplast4thrtecode']
    main_prev_trip_codes_columns=check_all_characters_present(main_df,main_prev_trip_codes_checks)
    main_route_survey_column=check_all_characters_present(main_df,main_route_survey_checks)
    main_next_trip_codes_columns=check_all_characters_present(main_df,main_next_trip_codes_checks)
    main_transfer_list_columns=[*main_prev_trip_codes_columns,*main_route_survey_column,*main_next_trip_codes_columns]
    
    new_df=pd.merge(df[['id',*transfer_list_columns,'Final_Usage']],main_df[['id',*main_transfer_list_columns,'Final_Usage']],on='id',suffixes=('_Elvis', '_Non_Elvis'))
    new_df.reset_index(inplace=True,drop=True)

    new_df[main_route_survey_column[0]] = new_df[main_route_survey_column[0]].apply(lambda x: '_'.join(x.split('_')[:-1]))
    new_df[route_survey_column[0]] = new_df[route_survey_column[0]].apply(lambda x: '_'.join(x.split('_')[:-1]))

    for index, row in new_df.iterrows():
        main_transferlist=row[main_transfer_list_columns].values
        elvis_transferlist=row[transfer_list_columns].values
        elvis_non_nan_values = [value for value in elvis_transferlist if pd.notna(value)]
        non_nan_values = [value for value in main_transferlist if pd.notna(value)]
        has_duplicates = len(non_nan_values) != len(set(non_nan_values))
        if has_duplicates:
            new_df.loc[index,'Duplicate_Route']=1
        else:
            new_df.loc[index,'Duplicate_Route']=0
    
    return new_df

In [116]:
duplicate_df=duplicate_route_information(df,main_df,ke_df)

In [117]:
def review_the_reviewer(df,ke_df,main_df):
    ke_df=ke_df[ke_df['INTERV_INIT']!=999]
    ke_df=ke_df[ke_df['HAVE_5_MIN_FOR_SURVECode']==1]
    # getting data from elvis database file which matches with KingElvis 
    df=pd.merge(df,ke_df[['id']],on='id',how='left',indicator=True)
    df['Matched'] = (df['_merge'] == 'both').astype(int)
    df.drop(columns=['_merge'])
    df=df[df['Matched']==1]
    df.drop_duplicates(subset=['id'],keep='first',inplace=True)

    # getting data from non-elvis database file which matches with KingElvis 
    main_df=pd.merge(main_df,ke_df[['id']],on='id',how='left',indicator=True)
    main_df['Matched'] = (main_df['_merge'] == 'both').astype(int)
    main_df.drop(columns=['_merge'])
    main_df=main_df[main_df['Matched']==1]
    main_df.drop_duplicates(subset=['id'],keep='first',inplace=True)

    origin_home_columns_check=['originaddresslat', 'originaddresslong','originplacetype','homeaddresslat','homeaddresslong']
    origin_home_columns=check_all_characters_present(df,origin_home_columns_check)
    origin_home_columns.sort()
    origin_home_columns

    destin_home_columns_check=['destinaddresslat', 'destinaddresslong','destinplacetype','homeaddresslat','homeaddresslong']
    destin_home_columns=check_all_characters_present(df,destin_home_columns_check)
    destin_home_columns.sort()
    destin_home_columns
    # if origin lat/long not present in elvis database file then add home lat/long to those values
    for index, row in df.iterrows():
        if (pd.isna(row[origin_home_columns[2]]) or pd.isna(row[origin_home_columns[3]])) and 'home' in row[origin_home_columns[4]].lower():
            df.loc[index, origin_home_columns[2]] = row[origin_home_columns[0]]
            df.loc[index, origin_home_columns[3]] = row[origin_home_columns[1]]
            
        if (pd.isna(row[destin_home_columns[0]]) or pd.isna(row[destin_home_columns[1]])) and 'home' in str(row[destin_home_columns[2]]).lower():
            df.loc[index, destin_home_columns[0]] = row[destin_home_columns[3]]
            df.loc[index, destin_home_columns[1]] = row[destin_home_columns[4]]

    non_origin_home_columns_check=['originaddresslat', 'originaddresslong','originplacetype','homeaddresslat','homeaddresslong']
    non_origin_home_columns=check_all_characters_present(main_df,non_origin_home_columns_check)
    non_origin_home_columns.sort()
    non_origin_home_columns

    non_destin_home_columns_check=['destinaddresslat', 'destinaddresslong','destinplacetype','homeaddresslat','homeaddresslong']
    non_destin_home_columns=check_all_characters_present(main_df,non_destin_home_columns_check)
    non_destin_home_columns.sort()
    non_destin_home_columns

    # if origin lat/long not present in non elvis database file then add home lat/long to those values
    for index, row in main_df.iterrows():
        if (pd.isna(row[non_origin_home_columns[2]]) or pd.isna(row[non_origin_home_columns[3]])) and ('home' in row[non_origin_home_columns[4]].lower()) :
            main_df.loc[index, non_origin_home_columns[2]] = row[non_origin_home_columns[0]]
            main_df.loc[index, non_origin_home_columns[3]] = row[non_origin_home_columns[1]]

        if (pd.isna(row[non_destin_home_columns[0]]) or pd.isna(row[non_destin_home_columns[1]])) and ('home' in str(row[non_destin_home_columns[2]]).lower()) :
            main_df.loc[index, non_destin_home_columns[0]] = row[non_destin_home_columns[3]]
            main_df.loc[index, non_destin_home_columns[1]] = row[non_destin_home_columns[4]]

    # get columns from elvis file
    origin_destin_prev_next_columns_check=['originaddresslat', 'originaddresslong', 'stoponlat', 'stoponlong', 'stopofflat', 'stopofflong','destinaddresslat', 'destinaddresslong','prevtransferscode','nexttransferscode']
    origin_destin_prev_next_columns=check_all_characters_present(df,origin_destin_prev_next_columns_check)
    origin_destin_prev_next_columns.sort()

    # get columns form non-elvis file
    non_origin_destin_prev_next_columns_check=['originaddresslat', 'originaddresslong', 'stoponlat', 'stoponlong', 'stopofflat', 'stopofflong','destinaddresslat', 'destinaddresslong','prevtransferscode','nexttransferscode']
    non_origin_destin_prev_next_columns=check_all_characters_present(main_df,non_origin_destin_prev_next_columns_check)
    non_origin_destin_prev_next_columns.sort()

    # add elvis database columns in KINGElvis file and rename them to KE_ColumnsName
    ke_df=pd.merge(ke_df,df[['id',*origin_destin_prev_next_columns]],on='id',how='left')
    # ke_df=pd.merge(ke_df,df[['id',*origin_destin_prev_next_columns]],on='id',how='left')
    ke_df.rename(columns={'DESTIN_ADDRESS_LAT':'KE_DESTIN_ADDRESS_LAT','DESTIN_ADDRESS_LONG':'KE_DESTIN_ADDRESS_LONG',
                        'ORIGIN_ADDRESS_LAT':'KE_ORIGIN_ADDRESS_LAT','ORIGIN_ADDRESS_LONG':'KE_ORIGIN_ADDRESS_LONG',
                        'STOP_OFF_LAT':'KE_STOP_OFF_LAT','STOP_OFF_LONG':'KE_STOP_OFF_LONG','STOP_ON_LAT':'KE_STOP_ON_LAT',
                        'STOP_ON_LONG':'KE_STOP_ON_LONG','PREV_TRANSFERSCode':'KE_PREV_TRANSFERSCode','NEXT_TRANSFERSCode':'KE_NEXT_TRANSFERSCode'
                        },inplace=True)

    # add non-elvis database columns in KINGElvis file and rename them to KE_ColumnsName
    ke_df=pd.merge(ke_df,main_df[['id',*non_origin_destin_prev_next_columns]],on='id',how='left')

    non_origin_destin_columns_check=['originaddresslat', 'originaddresslong','destinaddresslat', 'destinaddresslong']
    non_prev_next_columns_check=['prevtransferscode','nexttransferscode']
    non_origin_destin_columns=check_all_characters_present(main_df,non_origin_destin_columns_check)
    non_prev_next_columns=check_all_characters_present(main_df,non_prev_next_columns_check)
    non_origin_destin_columns.sort()
    non_prev_next_columns.sort()
    non_origin_destin_columns

    ke_df[[*non_prev_next_columns,'KE_PREV_TRANSFERSCode','KE_NEXT_TRANSFERSCode']]=ke_df[[*non_prev_next_columns,'KE_PREV_TRANSFERSCode','KE_NEXT_TRANSFERSCode']].fillna(0)


    ke_df[[*non_origin_destin_columns,'KE_ORIGIN_ADDRESS_LAT','KE_ORIGIN_ADDRESS_LONG','KE_DESTIN_ADDRESS_LAT','KE_DESTIN_ADDRESS_LONG']]=ke_df[[*non_origin_destin_columns,'KE_ORIGIN_ADDRESS_LAT','KE_ORIGIN_ADDRESS_LONG','KE_DESTIN_ADDRESS_LAT','KE_DESTIN_ADDRESS_LONG']].fillna(0)

    for index, row in ke_df.iterrows():
        num_changes = 0
        elvis_origin_lat=row['KE_ORIGIN_ADDRESS_LAT']
        elvis_origin_long=row['KE_ORIGIN_ADDRESS_LONG']
        non_elvis_origin_lat=row[non_origin_destin_columns[2]]
        non_elvis_origin_long=row[non_origin_destin_columns[3]]
        
        elvis_destin_lat=row['KE_DESTIN_ADDRESS_LAT']
        elvis_destin_long=row['KE_DESTIN_ADDRESS_LONG']
        non_elvis_destin_lat=row[non_origin_destin_columns[0]]
        non_elvis_destin_long=row[non_origin_destin_columns[1]]
        
        if all([elvis_origin_lat, elvis_origin_long, non_elvis_origin_lat, non_elvis_origin_long]):
            distance=get_distance_between_coordinates(elvis_origin_lat,elvis_origin_long,non_elvis_origin_lat,non_elvis_origin_long)
            ke_df.loc[index,'Origin Distance']=distance
            if distance > 0.15:
                ke_df.loc[index,'Origin Change']=1
                num_changes += 1
            else:
                ke_df.loc[index,'Origin Change']=0
        elif elvis_origin_lat and elvis_origin_long:
            ke_df.loc[index,'Origin Distance']=0
            num_changes += 1
            ke_df.loc[index,'Origin Change']=1
        elif non_elvis_origin_lat and non_elvis_origin_long:
            ke_df.loc[index,'Origin Distance']=0
            num_changes += 1
            ke_df.loc[index,'Origin Change']=1
        else:
            ke_df.loc[index,'Origin Distance']=0
            ke_df.loc[index,'Origin Change']=0
                

        if all([elvis_destin_lat, elvis_destin_long, non_elvis_destin_lat, non_elvis_destin_long]):
            distance=get_distance_between_coordinates(elvis_destin_lat,elvis_destin_long,non_elvis_destin_lat,non_elvis_destin_long)
            ke_df.loc[index,'Destin Distance']=distance
            if distance > 0.15:
                ke_df.loc[index,'Destin Change']=1
                num_changes += 1
            else:
                ke_df.loc[index,'Destin Change']=0
        elif elvis_destin_lat and elvis_destin_long:
            ke_df.loc[index,'Destin Distance']=0
            ke_df.loc[index,'Destin Change']=1
            num_changes += 1
        elif non_elvis_destin_lat and non_elvis_destin_long:
            ke_df.loc[index,'Destin Distance']=0
            ke_df.loc[index,'Destin Change']=1
            num_changes += 1
        else:
            ke_df.loc[index,'Destin Distance']=0
            ke_df.loc[index,'Destin Change']=0

        if row[non_prev_next_columns[0]] == row['KE_NEXT_TRANSFERSCode']:
            ke_df.loc[index,'NextTrans Change']=0
        else:
            ke_df.loc[index,'NextTrans Change']=1
            num_changes += 1

        if row[non_prev_next_columns[1]] == row['KE_PREV_TRANSFERSCode']:
            ke_df.loc[index,'PrevTrans Change']=0

        else:
            ke_df.loc[index,'PrevTrans Change']=1
            num_changes += 1

        ke_df.at[index, 'Change Count'] = num_changes



    ke_df['Low Count'] = np.where(ke_df['Change Count'] <= 1, 'Yes', 'No')


    stop_on_off_columns_check=['stoponlat', 'stoponlong', 'stopofflat', 'stopofflong']
    stop_on_off_columns=check_all_characters_present(ke_df,stop_on_off_columns_check)
    stop_on_off_columns.sort()


    ke_df[[*stop_on_off_columns,'KE_STOP_OFF_LAT', 'KE_STOP_OFF_LONG', 'KE_STOP_ON_LAT', 'KE_STOP_ON_LONG']]=ke_df[[*stop_on_off_columns,'KE_STOP_OFF_LAT', 'KE_STOP_OFF_LONG', 'KE_STOP_ON_LAT', 'KE_STOP_ON_LONG']].fillna(0)

    ke_stop_on_off_column_check=['kestopofflat','kestopofflong','kestoponlat','kestoponlong']
    ke_stop_on_off_column=check_all_characters_present(ke_df,ke_stop_on_off_column_check)
    ke_stop_on_off_column.sort()

    for index, row in ke_df.iterrows():
        if (
            (round(row[stop_on_off_columns[0]], 3) == round(row[ke_stop_on_off_column[0]], 3)) and
            (round(row[stop_on_off_columns[1]], 3) == round(row[ke_stop_on_off_column[1]], 3))
        ) and (
            (round(row[stop_on_off_columns[2]], 3) == round(row[ke_stop_on_off_column[2]], 3)) and
            (round(row[stop_on_off_columns[3]], 3) == round(row[ke_stop_on_off_column[3]], 3))
        ):
            ke_df.loc[index, 'Route Changes'] = 0
        else:
            ke_df.loc[index, 'Route Changes'] = 1
    return ke_df

In [118]:
def get_distance_between_coordinates(lat1, lon1, lat2, lon2):
    try:
        lat1 = float(lat1)
        lon1 = float(lon1)
        lat2 = float(lat2)
        lon2 = float(lon2)
        
        coords_1 = (lat1, lon1)
        coords_2 = (lat2, lon2)
        
        distance = geodesic(coords_1, coords_2).miles
        return distance
    except (ValueError, TypeError) as e:
        # Handle the exception here
        pass

In [119]:
reviewer_df=review_the_reviewer(df,ke_df,main_df)
reviewer_df.head()

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,STOP_ON_LONG_,Origin Distance,Origin Change,Destin Distance,Destin Change,NextTrans Change,PrevTrans Change,Change Count,Low Count,Route Changes
0,2024-03-01,6015,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.468632,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes,0.0
1,2024-03-01,6069,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.412441,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes,0.0
2,2024-03-01,6071,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.422553,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes,1.0
3,2024-03-01,6073,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.404378,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes,0.0
4,2024-03-01,6074,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.407992,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Yes,0.0

In [120]:
total_records=reviewer_df.shape[0]
total_records

1885

In [121]:
reviewer_df.columns

Index(['Elvis_Date', 'elvis_id', '1st Cleaner', 'FINAL_REVIEWER',
       'Final_Usage', 'REASON FOR REMOVAL', 'REASON FOR REMOVAL [Other]',
       'route_match_flag', 'distance_flag', 'SUPERVISOR_COMMENT', 'id',
       'Completed', 'INTERV_INIT', 'ROUTE_SURVEYEDCode', 'ROUTE_SURVEYED',
       'HAVE_5_MIN_FOR_SURVECode', 'HAVE_5_MIN_FOR_SURVE', 'ORIGIN_PLACE_TYPE',
       'ORIGIN_TRANSPORTCode', 'ORIGIN_TRANSPORT', 'DESTIN_PLACE_TYPE',
       'DESTIN_TRANSPORTCode', 'DESTIN_TRANSPORT', '_INTRV_NOTE',
       'ELVIS_STATUS', 'ELVIS_COMMENT', 'ROUTE_STATUS', 'Stops_Status',
       'Test_Status', 'Traditional_Check', 'OD_Distance_Check',
       'Transfer_Distance_Check', '2X_REVIEW_CHECK', '2X_REVIEW_CHECK.1',
       '2x_REVIEWED_BY', '2x_REVIEWED_FLAG', 'ADMIN_APPROVED',
       'SURVEY_RECOVERY', 'SURVEY_RECOVERY_REVIEWED_BY', 'Recovery Check',
       '2x_REVIEWED_BY.1', '2x_REVIEWED_FLAG.1', 'ADMIN_APPROVED.1',
       'RECORD_INFO', 'KE_DESTIN_ADDRESS_LAT', 'KE_DESTIN_ADDRESS_LONG',
       'KE_NEXT_TRANSFERSCode', 'KE_ORIGIN_ADDRESS_LAT',
       'KE_ORIGIN_ADDRESS_LONG', 'KE_PREV_TRANSFERSCode', 'KE_STOP_OFF_LAT',
       'KE_STOP_OFF_LONG', 'KE_STOP_ON_LAT', 'KE_STOP_ON_LONG',
       'DESTIN_ADDRESS_LAT_', 'DESTIN_ADDRESS_LONG_', 'NEXT_TRANSFERS_Code_',
       'ORIGIN_ADDRESS_LAT_', 'ORIGIN_ADDRESS_LONG_', 'PREV_TRANSFERS_Code_',
       'STOP_OFF_LAT_', 'STOP_OFF_LONG_', 'STOP_ON_LAT_', 'STOP_ON_LONG_',
       'Origin Distance', 'Origin Change', 'Destin Distance', 'Destin Change',
       'NextTrans Change', 'PrevTrans Change', 'Change Count', 'Low Count',
       'Route Changes'],
      dtype='object')

In [122]:
reviewer_df[(reviewer_df['PrevTrans Change']==1)|(reviewer_df['NextTrans Change']==1)]

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,STOP_ON_LONG_,Origin Distance,Origin Change,Destin Distance,Destin Change,NextTrans Change,PrevTrans Change,Change Count,Low Count,Route Changes
7,2024-03-01,6097,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.407790,0.0,0.0,0.0,0.0,0.0,1.0,1.0,Yes,0.0
8,2024-03-01,6103,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.437373,0.0,0.0,0.0,0.0,1.0,0.0,1.0,Yes,1.0
9,2024-03-01,6105,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.430760,0.0,0.0,0.0,0.0,1.0,0.0,1.0,Yes,0.0
13,2024-03-01,6127,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.407050,0.0,0.0,0.0,0.0,0.0,1.0,1.0,Yes,0.0
23,2024-03-01,6155,HereAPI,Sameera,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.408620,0.0,0.0,0.0,0.0,0.0,1.0,1.0,Yes,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1765,2024-03-01,12437,HereAPI,Divya sravani,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.475245,0.0,0.0,0.0,0.0,0.0,1.0,1.0,Yes,0.0
1785,2024-03-01,12472,HereAPI,Divya sravani,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.429321,0.0,0.0,0.0,0.0,1.0,0.0,1.0,Yes,0.0
1808,2024-03-01,12576,HereAPI,T A Divya,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.403461,0.0,0.0,0.0,0.0,1.0,0.0,1.0,Yes,0.0
1824,2024-03-01,12632,HereAPI,T A Divya,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.438883,0.0,0.0,0.0,0.0,1.0,0.0,1.0,Yes,0.0
1837,2024-03-01,12684,HereAPI,Kashish,Use,NaN,NaN,Elvis_Review,Elvis_Review,NaN,...,-122.402300,0.0,0.0,0.0,0.0,0.0,1.0,1.0,Yes,0.0

In [123]:
duplicate_df.shape

(1885, 22)

In [124]:
duplicate_df=pd.merge(duplicate_df,reviewer_df[['id','PrevTrans Change','NextTrans Change']],on='id')

In [125]:
duplicate_df.shape

(1885, 24)

In [126]:
duplicate_df.head()

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,...,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_,Final_Usage_Non_Elvis,Duplicate_Route,PrevTrans Change,NextTrans Change
0,6015,BAX_1_Yellow-N,NaN,NaN,NaN,MUN_1_14R,NaN,NaN,NaN,NaN,...,NaN,MUN_1_14R,NaN,NaN,NaN,NaN,Use,0.0,0.0,0.0
1,6069,NaN,NaN,NaN,NaN,MUN_1_7,NaN,NaN,NaN,NaN,...,NaN,MUN_1_7,NaN,NaN,NaN,NaN,Use,0.0,0.0,0.0
2,6071,NaN,NaN,NaN,NaN,MUN_1_7,MUN_1_33,MUN_1_39,NaN,NaN,...,NaN,MUN_1_7,MUN_1_33,MUN_1_39,NaN,NaN,Use,0.0,0.0,0.0
3,6073,NaN,NaN,NaN,NaN,MUN_1_30,NaN,NaN,NaN,NaN,...,NaN,MUN_1_30,NaN,NaN,NaN,NaN,Use,0.0,0.0,0.0
4,6074,MUN_1_15,NaN,NaN,NaN,MUN_1_7,NaN,NaN,NaN,NaN,...,NaN,MUN_1_7,NaN,NaN,NaN,NaN,Use,0.0,0.0,0.0

In [127]:
transfer_change_total=duplicate_df[((duplicate_df['PrevTrans Change']==1)|(duplicate_df['NextTrans Change']==1))].shape[0]

In [128]:
total_records=duplicate_df.shape[0]

In [129]:
transfer_change_percentage=(transfer_change_total/total_records)*100

In [130]:
duplicate_transfer_total=duplicate_df[((duplicate_df['PrevTrans Change']==1)|(duplicate_df['NextTrans Change']==1))&(duplicate_df['Duplicate_Route']==1)].shape[0]

In [131]:
duplicate_transfer_percentage=(duplicate_transfer_total/transfer_change_total)*100

In [132]:
percentage_dict={'Records Reviewed':total_records,'Trnasfer Updates':transfer_change_percentage,'Duplicate Routes Of Transfer Updates':duplicate_transfer_percentage}

In [133]:
percentage_dict = {'Records Reviewed': total_records,
                   'Transfer Updates': transfer_change_percentage,
                   'Duplicate Routes Of Transfer Updates': duplicate_transfer_percentage}
percentage_df = pd.DataFrame([percentage_dict])

In [134]:
percentage_df

   Records Reviewed  Transfer Updates  Duplicate Routes Of Transfer Updates
0              1885          7.161804                             35.555556

In [135]:
duplicate_df[((duplicate_df['PrevTrans Change']==1)|(duplicate_df['NextTrans Change']==1))&(duplicate_df['Duplicate_Route']==1)].shape[0]

48

In [136]:
duplicate_df[((duplicate_df['PrevTrans Change']==1)|(duplicate_df['NextTrans Change']==1))].shape[0]

135

In [137]:
duplicate_df[duplicate_df['Duplicate_Route']==1]

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,...,TRIP_FOURTH_ROUTE_Code_,ROUTE_SURVEYED_Code_,TRIP_NEXT_ROUTE_Code_,TRIP_AFTER_ROUTE_Code_,TRIP_3RD_ROUTE_Code_,TRIP_LAST4TH_RTE_Code_,Final_Usage_Non_Elvis,Duplicate_Route,PrevTrans Change,NextTrans Change
7,6097,NaN,NaN,NaN,NaN,MUN_1_45,NaN,NaN,NaN,NaN,...,NaN,MUN_1_45,NaN,NaN,NaN,NaN,Use,1.0,1.0,0.0
8,6103,MUN_1_22,NaN,NaN,NaN,MUN_1_7,MUN_1_N,NaN,NaN,NaN,...,NaN,MUN_1_7,MUN_1_7,MUN_1_N,NaN,NaN,Use,1.0,0.0,1.0
9,6105,NaN,NaN,NaN,NaN,MUN_1_7,NaN,NaN,NaN,NaN,...,NaN,MUN_1_7,MUN_1_7,MUN_1_28,NaN,NaN,Use,1.0,0.0,1.0
13,6127,NaN,NaN,NaN,NaN,MUN_1_30,NaN,NaN,NaN,NaN,...,NaN,MUN_1_30,NaN,NaN,NaN,NaN,Use,1.0,1.0,0.0
19,6141,NaN,NaN,NaN,NaN,MUN_1_30,MUN_1_30,NaN,NaN,NaN,...,NaN,MUN_1_30,MUN_1_30,NaN,NaN,NaN,Remove,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1667,11860,MUN_1_48,NaN,NaN,NaN,MUN_1_14,MUN_1_33,NaN,NaN,NaN,...,NaN,MUN_1_14,BAX_1_Yellow-N,NaN,NaN,NaN,Use,1.0,0.0,0.0
1671,11870,NaN,NaN,NaN,NaN,MUN_1_9,NaN,NaN,NaN,NaN,...,NaN,MUN_1_9,NaN,NaN,NaN,NaN,Use,1.0,1.0,0.0
1727,12194,MUN_1_31,NaN,NaN,NaN,MUN_1_31,NaN,NaN,NaN,NaN,...,NaN,MUN_1_31,NaN,NaN,NaN,NaN,Remove,1.0,0.0,0.0
1785,12472,MUN_1_24,NaN,NaN,NaN,MUN_1_M,NaN,NaN,NaN,NaN,...,NaN,MUN_1_M,MUN_1_M,NaN,NaN,NaN,Use,1.0,0.0,1.0
1837,12684,NaN,NaN,NaN,NaN,MUN_1_8,MUN_1_31,NaN,NaN,NaN,...,NaN,MUN_1_8,MUN_1_31,NaN,NaN,NaN,Use,1.0,1.0,0.0