In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import warnings

warnings.filterwarnings('ignore')

In [2]:
# sample_df=pd.read_excel('o2o_20230522_valleymetro_az_rail.xlsx',sheet_name='WKDAY_O2O_RAIL')
# sample_df.head()

In [3]:
# sample_df.columns

In [4]:
df=pd.read_csv('seattle_rail2024o2o_export_odbc.csv')

df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,STTAC_ON_Code_,STTAC_ON,STTAC_OFF_Code_,STTAC_OFF,TIME_BOARDED_Code_,TIME_BOARDED,LANGUAGE_Code_,LANGUAGE,LANGUAGE_Other_,RESTART_URL
0,81161,2024-04-02 18:32:39,4,en,2024-04-02 18:32:30,2024-04-02 18:32:39,136.37.108.111,https://seattle-od.etc-research.com/index.php/...,-25200,999,...,NaN,NaN,NaN,NaN,AM,AM Peak (Before 9:00am),NaN,NaN,NaN,NaN
1,81162,2024-04-02 18:34:31,4,en,2024-04-02 18:32:40,2024-04-02 18:34:31,136.37.108.111,https://seattle-od.etc-research.com/index.php/...,-25200,999,...,NaN,NaN,NaN,NaN,AM,AM Peak (Before 9:00am),NaN,NaN,NaN,NaN
2,81163,NaN,2,en,2024-04-02 18:34:32,2024-04-02 18:34:32,136.37.108.111,https://seattle-od.etc-research.com/index.php/...,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,81164,NaN,2,en,2024-04-02 18:36:12,2024-04-02 18:36:27,70.113.126.123,https://seattle-od.etc-research.com/,-25200,BAC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,81165,NaN,-1,en,2024-04-02 18:36:51,2024-04-02 18:36:51,168.61.170.4,https://seattle-od.etc-research.com/,-25200,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.fillna(method='ffill',inplace=True)

In [6]:
df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,STTAC_ON_Code_,STTAC_ON,STTAC_OFF_Code_,STTAC_OFF,TIME_BOARDED_Code_,TIME_BOARDED,LANGUAGE_Code_,LANGUAGE,LANGUAGE_Other_,RESTART_URL
0,81161,2024-04-02 18:32:39,4,en,2024-04-02 18:32:30,2024-04-02 18:32:39,136.37.108.111,https://seattle-od.etc-research.com/index.php/...,-25200,999,...,NaN,NaN,NaN,NaN,AM,AM Peak (Before 9:00am),NaN,NaN,NaN,NaN
1,81162,2024-04-02 18:34:31,4,en,2024-04-02 18:32:40,2024-04-02 18:34:31,136.37.108.111,https://seattle-od.etc-research.com/index.php/...,-25200,999,...,NaN,NaN,NaN,NaN,AM,AM Peak (Before 9:00am),NaN,NaN,NaN,NaN
2,81163,2024-04-02 18:34:31,2,en,2024-04-02 18:34:32,2024-04-02 18:34:32,136.37.108.111,https://seattle-od.etc-research.com/index.php/...,-25200,999,...,NaN,NaN,NaN,NaN,AM,AM Peak (Before 9:00am),NaN,NaN,NaN,NaN
3,81164,2024-04-02 18:34:31,2,en,2024-04-02 18:36:12,2024-04-02 18:36:27,70.113.126.123,https://seattle-od.etc-research.com/,-25200,BAC,...,NaN,NaN,NaN,NaN,AM,AM Peak (Before 9:00am),NaN,NaN,NaN,NaN
4,81165,2024-04-02 18:34:31,-1,en,2024-04-02 18:36:51,2024-04-02 18:36:51,168.61.170.4,https://seattle-od.etc-research.com/,-25200,BAC,...,NaN,NaN,NaN,NaN,AM,AM Peak (Before 9:00am),NaN,NaN,NaN,NaN

In [7]:
detail_df=pd.read_excel('details_project_od_Seattle.xlsx',sheet_name='STOPS')
detail_df.head()

,agency,gtfs_date,gtfs_ver,route_short_name,route_long_name,direction_id,route_dir,MaxOfstop_sequence,seq_fixed,stop_id,stop_name,stop_lat,stop_lon,stop_lat6,stop_lon6,ETC_STOP_ID,ETC_STOP_NAME,notes,ETC_ROUTE_ID,ETC_ROUTE_NAME
0,CMT,3/26/2024,1,101,Mariner P&R - Aurora Village,0,101_0,1,1,29-2105,Mariner Park & Ride Bay 3,47.879670,-122.238570,47.879670,-122.238570,CMT_1_101_00_29-2105,Mariner Park & Ride Bay 3,NaN,CMT_1_101_00,CMT_1_101_00
1,CMT,3/26/2024,1,101,Mariner P&R - Aurora Village,0,101_0,2,2,1553,128th St SW & 4th Ave W,47.882044,-122.240279,47.882044,-122.240279,CMT_1_101_00_1553,128th St SW & 4th Ave W,NaN,CMT_1_101_00,CMT_1_101_00
2,CMT,3/26/2024,1,101,Mariner P&R - Aurora Village,0,101_0,3,3,1554,128th St SW & 8th Ave W,47.882001,-122.245798,47.882001,-122.245798,CMT_1_101_00_1554,128th St SW & 8th Ave W,NaN,CMT_1_101_00,CMT_1_101_00
3,CMT,3/26/2024,1,101,Mariner P&R - Aurora Village,0,101_0,4,4,29-808,Airport Rd & E Gibson Rd,47.882200,-122.250961,47.882200,-122.250961,CMT_1_101_00_29-808,Airport Rd & E Gibson Rd,NaN,CMT_1_101_00,CMT_1_101_00
4,CMT,3/26/2024,1,101,Mariner P&R - Aurora Village,0,101_0,5,5,29-807,Airport Rd & Admiralty Way,47.884833,-122.254348,47.884833,-122.254348,CMT_1_101_00_29-807,Airport Rd & Admiralty Way,NaN,CMT_1_101_00,CMT_1_101_00

In [8]:
def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [9]:
df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT', 'ORIGRESPID', 'ROUTE_SURVEYED_Code_', 'ROUTE_SURVEYED',
       'ROUTE_SURVEYED_Other_', 'SSSL_ON_Code_', 'SSSL_ON', 'SSSL_OFF_Code_',
       'SSSL_OFF', 'S1L_ON_Code_', 'S1L_ON', 'S1L_OFF_Code_', 'S1L_OFF',
       'STTAC_ON_Code_', 'STTAC_ON', 'STTAC_OFF_Code_', 'STTAC_OFF',
       'TIME_BOARDED_Code_', 'TIME_BOARDED', 'LANGUAGE_Code_', 'LANGUAGE',
       'LANGUAGE_Other_', 'RESTART_URL'],
      dtype='object')

In [10]:
database_columns_checks=['id','completed','routesurveyedcode','routesurveyed','timeboardedcode','timeboarded','jwboncode','jwbon','jwboffcode','jwboff','jeboncode','jebon','jeboffcode','jeboff']
database_columns=check_all_characters_present(df,database_columns_checks)
database_columns

['id',
 'Completed',
 'ROUTE_SURVEYED_Code_',
 'ROUTE_SURVEYED',
 'TIME_BOARDED_Code_',
 'TIME_BOARDED']

In [11]:
o2o_df=df[database_columns]
o2o_df.head()

,id,Completed,ROUTE_SURVEYED_Code_,ROUTE_SURVEYED,TIME_BOARDED_Code_,TIME_BOARDED
0,81161,2024-04-02 18:32:39,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
1,81162,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
2,81163,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
3,81164,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
4,81165,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)

In [12]:
o2o_df.tail()

,id,Completed,ROUTE_SURVEYED_Code_,ROUTE_SURVEYED,TIME_BOARDED_Code_,TIME_BOARDED
23356,104835,2024-05-28 08:29:10,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am)
23357,104836,2024-05-28 08:29:40,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am)
23358,104837,2024-05-28 08:30:17,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am)
23359,104838,2024-05-28 08:30:36,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am)
23360,104844,2024-05-28 13:31:00,S1L,ST 1 LINE,MID,Midday (9:00am-2:59pm)

In [13]:
o2o_df

,id,Completed,ROUTE_SURVEYED_Code_,ROUTE_SURVEYED,TIME_BOARDED_Code_,TIME_BOARDED
0,81161,2024-04-02 18:32:39,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
1,81162,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
2,81163,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
3,81164,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
4,81165,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am)
...,...,...,...,...,...,...
23356,104835,2024-05-28 08:29:10,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am)
23357,104836,2024-05-28 08:29:40,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am)
23358,104837,2024-05-28 08:30:17,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am)
23359,104838,2024-05-28 08:30:36,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am)
23360,104844,2024-05-28 13:31:00,S1L,ST 1 LINE,MID,Midday (9:00am-2:59pm)

In [14]:
date_columns_check=['completed']
date_columns=check_all_characters_present(o2o_df,date_columns_check)

# def get_day_name(x):
#     try:
#         # Try parsing the date with the expected format
#         date_object = datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
#     except ValueError:
#         # If parsing fails, try parsing with a different format
#         date_object = datetime.strptime(x, '%d/%m/%Y %H:%M')
#     day_name = date_object.strftime('%A')
#     if day_name in ['Saturday', 'Sunday']:
#         return 'Weekend'
#     return 'Weekday'

def get_day_name(x):
    if pd.isna(x) or x == 'nan':
        return 'Invalid Date'
    try:
        date_object = datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
    except ValueError:
        try:
            date_object = datetime.strptime(x, '%d/%m/%Y %H:%M')
        except ValueError:
            return 'Invalid Date'
    day_name = date_object.strftime('%A')
    if day_name in ['Saturday', 'Sunday']:
        return 'Weekend'
    return 'Weekday'

In [15]:
# o2o_df[date_columns[0]].fillna(method='ffill',inplace=True)

In [16]:

o2o_df['Day']=o2o_df[date_columns[0]].apply(get_day_name)

In [17]:
o2o_df

,id,Completed,ROUTE_SURVEYED_Code_,ROUTE_SURVEYED,TIME_BOARDED_Code_,TIME_BOARDED,Day
0,81161,2024-04-02 18:32:39,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am),Weekday
1,81162,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am),Weekday
2,81163,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am),Weekday
3,81164,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am),Weekday
4,81165,2024-04-02 18:34:31,SSSL,ST SOUNDER S LINE,AM,AM Peak (Before 9:00am),Weekday
...,...,...,...,...,...,...,...
23356,104835,2024-05-28 08:29:10,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am),Weekday
23357,104836,2024-05-28 08:29:40,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am),Weekday
23358,104837,2024-05-28 08:30:17,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am),Weekday
23359,104838,2024-05-28 08:30:36,S1L,ST 1 LINE,AM,AM Peak (Before 9:00am),Weekday
23360,104844,2024-05-28 13:31:00,S1L,ST 1 LINE,MID,Midday (9:00am-2:59pm),Weekday

In [ ]:
o2o_df[o2o_df['id']==4378]

In [ ]:
def clean_string(s):
    return s.replace(':', '').replace('-', '').replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

In [ ]:
# value='before500am'
owl_values=['500am559am','before500am']
am_values=['600am659am','700am759am','800am859am']
midday_values=['900am959am','1000am1059am','1100am1159am','1200pm1259pm','100pm159pm']
pm_values=['200pm259pm','300pm359pm']
pm_peak_values=['400pm459pm','500pm559pm','600pm659pm']
eve_values=['700pm759pm','800pm859pm','900pm959pm']
night_values=['after1000pm']
# if clean_string('Before 5:00 am') in owl_values:
#     print('cleaning process Worked')
#     print(f"Code is 6 and Time Period is OWL")

In [ ]:
o2o_df['TIME_BOARDED'][0]

In [ ]:
owl_values=['100am']
am_values=['600am','700am','800am']
midday_values=['900am','1000','1100am','1200pm','100pm']
pm_values=['200pm','300pm']
pm_peak_values=['400pm','500pm','600pm']
eve_values=['700pm','800pm','900pm']
night_values=['1000pm']

In [ ]:
def get_start_time(x):
    return clean_string(x.split('-')[0])

In [ ]:
o2o_df['Start_Time']=o2o_df['TIME_BOARDED'].apply(get_start_time)

In [ ]:
o2o_df

In [ ]:
# for _,row in o2o_df.iterrows():
#     if row['Start_Time'] in am_values:
#         o2o_df.loc[row.name,'TIME PERIOD']='AM'        
#         o2o_df.loc[row.name,'TIME PERIOD[CODE]']=0
#     elif row['Start_Time'] in midday_values:
#         o2o_df.loc[row.name,'TIME PERIOD']='MIDDAY'        
#         o2o_df.loc[row.name,'TIME PERIOD[CODE]']=1
#     elif row['Start_Time'] in pm_values:
#         o2o_df.loc[row.name,'TIME PERIOD']='PM'        
#         o2o_df.loc[row.name,'TIME PERIOD[CODE]']=2
#     elif row['Start_Time'] in pm_peak_values:
#         o2o_df.loc[row.name,'TIME PERIOD']='PM PEAK'        
#         o2o_df.loc[row.name,'TIME PERIOD[CODE]']=3
#     elif row['Start_Time'] in eve_values:
#         o2o_df.loc[row.name,'TIME PERIOD']='EVE'        
#         o2o_df.loc[row.name,'TIME PERIOD[CODE]']=4
#     elif row['Start_Time'] in night_values:
#         o2o_df.loc[row.name,'TIME PERIOD']='NIGHT'        
#         o2o_df.loc[row.name,'TIME PERIOD[CODE]']=5
#     else:
#         o2o_df.loc[row.name,'TIME PERIOD']='OWL'        
#         o2o_df.loc[row.name,'TIME PERIOD[CODE]']=6

In [ ]:
time_period_mapping = {
    'AM': am_values,
    'MIDDAY': midday_values,
    'PM': pm_values,
    'PM PEAK': pm_peak_values,
    'EVE': eve_values,
    'NIGHT': night_values
}

for index, row in o2o_df.iterrows():
    for period, values in time_period_mapping.items():
        if row['Start_Time'] in values:
            o2o_df.at[index, 'TIME PERIOD'] = period
            o2o_df.at[index, 'TIME PERIOD[CODE]'] = list(time_period_mapping.keys()).index(period)
            break
    else:
        o2o_df.at[index, 'TIME PERIOD'] = 'OWL'
        o2o_df.at[index, 'TIME PERIOD[CODE]'] = len(time_period_mapping)

In [ ]:
o2o_df.drop(columns=['Start_Time'],inplace=True)

In [ ]:
o2o_df[o2o_df['TIME PERIOD[CODE]']==5]

In [ ]:
o2o_df

In [ ]:
# stop_columns_check=['jwboncode','jwbon','jwboffcode','jwboff']
# stop_columns=check_all_characters_present(df,stop_columns_check)
# stop_columns

In [ ]:
stop_west_columns_check=['jwboncode','jwbon','jwboffcode','jwboff']
stop_west_columns=check_all_characters_present(df,stop_west_columns_check)
stop_east_columns_check=['jeboncode','jebon','jeboffcode','jeboff']
stop_east_columns=check_all_characters_present(df,stop_east_columns_check)
stop_west_columns.sort(),stop_east_columns.sort()
stop_columns=[*stop_east_columns,*stop_west_columns]
stop_columns.sort()
stop_west_columns,stop_east_columns,stop_columns

In [ ]:
o2o_df[o2o_df['J_WB_ON_Code_']==16997]['J_WB_ON'][:1].values[0]

In [ ]:
value='MUN_1_M_00_3716'
type(value)==str

In [ ]:
# value = 16997
def remove_1st_char(x):
    if type(x)==str:
        return float(x[-4:])
    return float(str(x)[1:])
remove_1st_char(value)

In [ ]:
data='Civic Center Station'
clean_string(data) in  clean_string(o2o_df[o2o_df['J_WB_ON_Code_']==16997]['J_WB_ON'][:1].values[0])

In [ ]:
# o2o_df[['J_WB_ON_Code_','J_WB_OFF_Code_']] = o2o_df[['J_WB_ON_Code_', 'J_WB_OFF_Code_']].fillna(0)

# stop_west_columns[3]='J_WB_ON_Code_',stop_west_columns[1]='J_WB_OFF_Code_'

# stop_east_columns[3]='J_EB_ON_Code_',stop_east_columns[1]='J_EB_OFF_Code_'

o2o_df[[stop_west_columns[3],stop_west_columns[1]]] = o2o_df[[stop_west_columns[3],stop_west_columns[1]]].fillna(0)

o2o_df[[stop_east_columns[3],stop_east_columns[1]]] = o2o_df[[stop_east_columns[3],stop_east_columns[1]]].fillna(0)
o2o_df

In [ ]:
stop_east_columns[1]+'NEW'

In [ ]:
# o2o_df['J_WB_ON_Code_NEW']=o2o_df['J_WB_ON_Code_'].apply(remove_1st_char)
# o2o_df['J_WB_OFF_Code_NEW']=o2o_df['J_WB_OFF_Code_'].apply(remove_1st_char)

o2o_df[stop_west_columns[3]+'NEW']=o2o_df[stop_west_columns[3]].apply(remove_1st_char)
o2o_df[stop_west_columns[1]+'NEW']=o2o_df[stop_west_columns[1]].apply(remove_1st_char)

o2o_df[stop_east_columns[3]+'NEW']=o2o_df[stop_east_columns[3]].apply(remove_1st_char)
o2o_df[stop_east_columns[1]+'NEW']=o2o_df[stop_east_columns[1]].apply(remove_1st_char)

In [ ]:
o2o_df

In [ ]:
detail_df.columns

In [ ]:
# for _,row in o2o_df.iterrows():
# #     stop_on value
#     on_value=detail_df[detail_df['stop_id']==row['J_WB_ON_Code_NEW']]
# #     stop off value
#     off_value=detail_df[detail_df['stop_id']==row['J_WB_OFF_Code_NEW']]
#     if on_value:
#         o2o_df.loc[row.name,row['STOP_ON_ID']]=on_value['stop_id']
#         o2o_df.loc[row.name,row['STOP_ON_CODE']]=on_value['ETC_STOP_ID']        
#         o2o_df.loc[row.name,row['STOP_ON_NAME']]=on_value['ETC_STOP_NAME']
#         o2o_df.loc[row.name,row['STOP_ON_LAT']]=on_value['stop_lat6']
#         o2o_df.loc[row.name,row['STOP_ON_LONG']]=on_value['stop_lon6']
#     else:
#         o2o_df.loc[row.name,row['STOP_ON_ID']]=np.nan
#         o2o_df.loc[row.name,row['STOP_ON_CODE']]=''       
#         o2o_df.loc[row.name,row['STOP_ON_NAME']]=''
#         o2o_df.loc[row.name,row['STOP_ON_LAT']]=np.nan
#         o2o_df.loc[row.name,row['STOP_ON_LONG']]=np.nan
        
#     if off_value:
#         o2o_df.loc[row.name,row['STOP_OFF_ID']]=on_value['stop_id']
#         o2o_df.loc[row.name,row['STOP_OFF_CODE']]=on_value['ETC_STOP_ID']        
#         o2o_df.loc[row.name,row['STOP_OFF_NAME']]=on_value['ETC_STOP_NAME']
#         o2o_df.loc[row.name,row['STOP_OFF_LAT']]=on_value['stop_lat6']
#         o2o_df.loc[row.name,row['STOP_OFF_LONG']]=on_value['stop_lon6']
#     else:
#         o2o_df.loc[row.name,row['STOP_OFF_ID']]=np.nan
#         o2o_df.loc[row.name,row['STOP_OFF_CODE']]=''       
#         o2o_df.loc[row.name,row['STOP_OFF_NAME']]=''
#         o2o_df.loc[row.name,row['STOP_OFF_LAT']]=np.nan
#         o2o_df.loc[row.name,row['STOP_OFF_LONG']]=np.nan

In [ ]:
# previous code where using only WB_Values

# for index, row in o2o_df.iterrows():
#     on_value = detail_df[detail_df['stop_id'] == row['J_WB_ON_Code_NEW']]
#     off_value = detail_df[detail_df['stop_id'] == row['J_WB_OFF_Code_NEW']]
    
#     # Handle STOP_ON values
#     if not on_value.empty:
#         o2o_df.loc[index, ['STOP_ON_ID', 'STOP_ON_CODE', 'STOP_ON_NAME', 'STOP_ON_LAT', 'STOP_ON_LONG']] = [
#             on_value.iloc[0]['stop_id'], 
#             on_value.iloc[0]['ETC_STOP_ID'], 
#             on_value.iloc[0]['ETC_STOP_NAME'], 
#             on_value.iloc[0]['stop_lat6'], 
#             on_value.iloc[0]['stop_lon6']
#         ]
#     else:
#         o2o_df.loc[index, ['STOP_ON_ID', 'STOP_ON_CODE', 'STOP_ON_NAME', 'STOP_ON_LAT', 'STOP_ON_LONG']] = np.nan, '', '', np.nan, np.nan

#     # Handle STOP_OFF values
#     if not off_value.empty:
#         o2o_df.loc[index, ['STOP_OFF_ID', 'STOP_OFF_CODE', 'STOP_OFF_NAME', 'STOP_OFF_LAT', 'STOP_OFF_LONG']] = [
#             off_value.iloc[0]['stop_id'], 
#             off_value.iloc[0]['ETC_STOP_ID'], 
#             off_value.iloc[0]['ETC_STOP_NAME'], 
#             off_value.iloc[0]['stop_lat6'], 
#             off_value.iloc[0]['stop_lon6']
#         ]
#     else:
#         o2o_df.loc[index, ['STOP_OFF_ID', 'STOP_OFF_CODE', 'STOP_OFF_NAME', 'STOP_OFF_LAT', 'STOP_OFF_LONG']] = np.nan, '', '', np.nan, np.nan

In [ ]:
for index, row in o2o_df.iterrows():
    on_wb_value = detail_df[detail_df['stop_id'] == row[stop_west_columns[3]+'NEW']]
    off_wb_value = detail_df[detail_df['stop_id'] == row[stop_west_columns[1]+'NEW']]
    
    on_eb_value = detail_df[detail_df['stop_id'] == row[stop_east_columns[3]+'NEW']]
    off_eb_value = detail_df[detail_df['stop_id'] == row[stop_east_columns[1]+'NEW']]
    
    # Handle STOP_ON values
    if not on_wb_value.empty and not off_wb_value.empty:
        o2o_df.loc[index, ['STOP_ON_ID', 'STOP_ON_CODE', 'STOP_ON_NAME', 'STOP_ON_LAT', 'STOP_ON_LONG']] = [
            on_wb_value.iloc[0]['stop_id'], 
            on_wb_value.iloc[0]['ETC_STOP_ID'], 
            on_wb_value.iloc[0]['ETC_STOP_NAME'], 
            on_wb_value.iloc[0]['stop_lat6'], 
            on_wb_value.iloc[0]['stop_lon6']
        ]
        o2o_df.loc[index, ['STOP_OFF_ID', 'STOP_OFF_CODE', 'STOP_OFF_NAME', 'STOP_OFF_LAT', 'STOP_OFF_LONG']] = [
            off_wb_value.iloc[0]['stop_id'], 
            off_wb_value.iloc[0]['ETC_STOP_ID'], 
            off_wb_value.iloc[0]['ETC_STOP_NAME'], 
            off_wb_value.iloc[0]['stop_lat6'], 
            off_wb_value.iloc[0]['stop_lon6']
        ]
    elif not on_eb_value.empty and not off_eb_value.empty:
        o2o_df.loc[index, ['STOP_ON_ID', 'STOP_ON_CODE', 'STOP_ON_NAME', 'STOP_ON_LAT', 'STOP_ON_LONG']] = [
            on_eb_value.iloc[0]['stop_id'], 
            on_eb_value.iloc[0]['ETC_STOP_ID'], 
            on_eb_value.iloc[0]['ETC_STOP_NAME'], 
            on_eb_value.iloc[0]['stop_lat6'], 
            on_eb_value.iloc[0]['stop_lon6']
        ]
        o2o_df.loc[index, ['STOP_OFF_ID', 'STOP_OFF_CODE', 'STOP_OFF_NAME', 'STOP_OFF_LAT', 'STOP_OFF_LONG']] = [
            off_eb_value.iloc[0]['stop_id'], 
            off_eb_value.iloc[0]['ETC_STOP_ID'], 
            off_eb_value.iloc[0]['ETC_STOP_NAME'], 
            off_eb_value.iloc[0]['stop_lat6'], 
            off_eb_value.iloc[0]['stop_lon6']
        ]

    # Handle STOP_OFF values
    else:
        o2o_df.loc[index, ['STOP_OFF_ID', 'STOP_OFF_CODE', 'STOP_OFF_NAME', 'STOP_OFF_LAT', 'STOP_OFF_LONG']] = np.nan, '', '', np.nan, np.nan

In [ ]:
o2o_df.drop(columns=['J_WB_ON_Code_NEW','J_WB_OFF_Code_NEW'],inplace=True)

In [ ]:
o2o_df.head()

In [ ]:
# with open('column_names.txt', 'w') as f:
#     f.write('\n'.join(df.columns))

In [ ]:
code_values = [
    "J_WB_ON_Code_",
    "J_WB_OFF_Code_",
    "J_EB_ON_Code_",
    "J_EB_OFF_Code_",
    "K_WB_ON_Code_",
    "K_WB_OFF_Code_",
    "K_EB_ON_Code_",
    "K_EB_OFF_Code_",
    "M_WB_ON_Code_",
    "M_WB_OFF_Code_",
    "M_EB_ON_Code_",
    "M_EB_OFF_Code_",
    "N_WB_ON_Code_",
    "N_WB_OFF_Code_",
    "N_EB_ON_Code_",
    "N_EB_OFF_Code_",
    "T_NB_ON_Code_",
    "T_NB_OFF_Code_",
    "T_SB_ON_Code_",
    "T_SB_OFF_Code_",
    "5R_OUT_ON_Code_",
    "5R_OUT_OFF_Code_",
    "5R_IN_ON_Code_",
    "5R_IN_OFF_Code_",
    "9R_OUT_ON_Code_",
    "9R_OUT_OFF_Code_",
    "9R_IN_ON_Code_",
    "9R_IN_OFF_Code_",
    "14R_OUT_ON_Code_",
    "14R_OUT_OFF_Code_",
    "14R_IN_ON_Code_",
    "14R_IN_OFF_Code_",
    "28R_OUT_ON_Code_",
    "28R_OUT_OFF_Code_",
    "28R_IN_ON_Code_",
    "28R_IN_OFF_Code_",
    "38R_OUT_ON_Code_",
    "38R_OUT_OFF_Code_",
    "38R_IN_ON_Code_",
    "38R_IN_OFF_Code_",
    "FMW_IN_ON_Code_",
    "FMW_IN_OFF_Code_",
    "FMW_OUT_ON_Code_",
    "FMW_OUT_OFF_Code_"
]

In [ ]:
df[code_values]