In [1]:
import pandas as pd
import numpy as np

import warnings

warnings.filterwarnings('ignore')

In [2]:
ke_df=pd.read_excel('COTA_KINGElvis.xlsx',sheet_name='Elvis_Review')
df=pd.read_csv('elviscota2023obweekday_export_odbc.csv')

In [3]:
def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [4]:
route_surveyed_column_check=['routesurveyedcode']
route_surveyed_column=check_all_characters_present(df,route_surveyed_column_check)
route_surveyed_column

['ROUTE_SURVEYEDCode']

In [5]:
ke_df=pd.merge(ke_df,df[['id',route_surveyed_column[0]]],on='id',how='left')

In [6]:
ke_df.rename(columns={'ROUTE_SURVEYEDCode_y':'ROUTE_SURVEYEDCode'},inplace=True)

In [7]:
ke_df = ke_df[(ke_df['INTERV_INIT'] != '999') & (ke_df['INTERV_INIT'] != 999)]

In [8]:
ke_df

,Elvis_Date,elvis_id,1st Cleaner,FINAL_REVIEWER,Final_Usage,REASON FOR REMOVAL,REASON FOR REMOVAL [Other],route_match_flag,distance_flag,SUPERVISOR_COMMENT,...,2x_REVIEWED_BY,2x_REVIEWED_FLAG,ADMIN_APPROVED,SURVEY_RECOVERY,SURVEY_RECOVERY_REVIEWED_BY,Recovery Check,2x_REVIEWED_BY.1,2x_REVIEWED_FLAG.1,ADMIN_APPROVED.1,ROUTE_SURVEYEDCode
16,2023-11-03,5632,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,COT_1_1_00
17,2023-11-03,5634,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,COT_1_2_00
18,2023-11-03,5636,HereAPI,"T A Divya, Regina",Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,COT_1_1_00
19,2023-11-03,5639,HereAPI,"T A Divya, Brian, Regina",Remove,Round trip,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,COT_1_1_00
20,2023-11-03,5640,Test/No 5 MIN,NaN,Remove,Test/No 5 MIN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,COT_1_2_00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5576,2023-12-03,13649,Test/No 5 MIN,NaN,Remove,Test/No 5 MIN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COT_1_25_00
5577,2023-12-03,13650,HereAPI,Divya sravani,Use,NaN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COT_1_25_01
5578,2023-12-03,13651,Test/No 5 MIN,NaN,Remove,Test/No 5 MIN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COT_1_25_01
5579,2023-12-03,13653,Test/No 5 MIN,NaN,Remove,Test/No 5 MIN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COT_1_10_01
5580,2023-12-03,13654,Test/No 5 MIN,NaN,Remove,Test/No 5 MIN,,Elvis_Review,Elvis_Review,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,COT_1_10_01

In [9]:
ke_df[['FINAL_REVIEWER']]

                FINAL_REVIEWER
16           T A Divya, Regina
17           T A Divya, Regina
18           T A Divya, Regina
19    T A Divya, Brian, Regina
20                         NaN
...                        ...
5576                       NaN
5577             Divya sravani
5578                       NaN
5579                       NaN
5580                       NaN

[5413 rows x 1 columns]

In [10]:
reviewers_names={}
for index, row in ke_df[ke_df['FINAL_REVIEWER'].notna()].iterrows():
    if '.' in row['FINAL_REVIEWER']:
        data_list = row['FINAL_REVIEWER'].split('.')
        data = ','.join(data_list)
        data_list = data.split(',')
    elif ',' in row['FINAL_REVIEWER']:
        data_list = row['FINAL_REVIEWER'].split(',')
    else:
        data_list = [row['FINAL_REVIEWER']]
    
    for name in data_list:
        name = name.strip()
        reviewers_names[name] = reviewers_names.get(name, 0)+1

In [11]:
reviewers_names

{'T A Divya': 180,
 'Regina': 150,
 'Brian': 312,
 'Sneh': 404,
 'Rutwa': 75,
 'Sameera': 237,
 'Kesar': 302,
 'Karthik': 140,
 'Priyanka': 100,
 'Saurav': 233,
 'Divya sravani': 418,
 'Kalpesh': 146,
 'Trusha': 198,
 'Raja': 200,
 'Himanshu': 200,
 'karthik': 92,
 'Vaishnavi': 200,
 'Gowtham': 374,
 'Bhumika': 397,
 'Srisamhita': 100,
 'Sakshi': 205,
 'muskan': 83}

In [12]:
max(reviewers_names,key=reviewers_names.get)

'Divya sravani'

In [13]:
reviewers_names = {}

for index, row in ke_df[ke_df['FINAL_REVIEWER'].notna()].iterrows():
    names = [name.strip() for name in row['FINAL_REVIEWER'].replace('.', ',').split(',')]
    for name in names:
        reviewers_names[name] = reviewers_names.get(name, 0) + 1
        
reviewers_names

{'T A Divya': 180,
 'Regina': 150,
 'Brian': 312,
 'Sneh': 404,
 'Rutwa': 75,
 'Sameera': 237,
 'Kesar': 302,
 'Karthik': 140,
 'Priyanka': 100,
 'Saurav': 233,
 'Divya sravani': 418,
 'Kalpesh': 146,
 'Trusha': 198,
 'Raja': 200,
 'Himanshu': 200,
 'karthik': 92,
 'Vaishnavi': 200,
 'Gowtham': 374,
 'Bhumika': 397,
 'Srisamhita': 100,
 'Sakshi': 205,
 'muskan': 83}

In [14]:
ke_df[['FINAL_REVIEWER']].value_counts()

FINAL_REVIEWER
Sneh                           399
Divya sravani                  378
Bhumika                        368
Gowtham                        339
Kesar                          285
Sameera                        234
Vaishnavi                      189
Himanshu                       183
Trusha                         182
Raja                           182
Sakshi                         181
Saurav                         174
T A Divya                      149
Kalpesh                        131
Karthik                        106
Priyanka                        98
Srisamhita                      88
karthik                         88
muskan                          83
Rutwa                           71
Saurav                          50
Divya sravani, Brian            25
Bhumika, Brian                  24
Sakshi, Brian                   24
Karthik,Regina, Brian           21
Gowtham, Brian                  19
Gowtham,Regina, Brian           16
Divya sravani,Regina, Brian     15
T A Divya, Regina               14
Karthik, Brian                  13
Srisamhita, Brian               12
Raja,Regina, Brian              11
Vaishnavi,Regina, Brian         10
Kesar, Regina, Brian            10
Saurav, Brian                    9
Trusha,Regina, Brian             9
Himanshu,Regina, Brian           9
Himanshu, Brian                  8
Raja, Brian                      7
Trusha, Brian                    7
T A Divya.Regina, Brian          6
Kalpesh, Brian                   6
T A Divya,Regina, Brian          6
Kalpesh,Regina, Brian            5
Bhumika,Regina, Brian            5
Sneh, Brian                      5
Kalpesh, Regina, Brian           4
karthik, Brian                   4
Rutwa, Brian                     4
Kesar,Regina, Brian              3
Sameera, Brian                   3
Kesar, Brian                     2
Kesar.Regina, Brian              2
T A Divya, Regina, Brian         2
T A Divya, Brian, Regina         2
Priyanka, Brian                  2
Vaishnavi, Brian                 1
T A Divya, Brian                 1
Name: count, dtype: int64

In [15]:
# Is there a reviewer not making any changes and we're getting a lot of our flags on their records to review again
reviewers_flags = {}
total_recovered=0
for index, row in ke_df[(ke_df['FINAL_REVIEWER'].notna()) &(ke_df['Final_Usage']=='Use')].iterrows():
    names = [name.strip() for name in row['FINAL_REVIEWER'].replace('.', ',').split(',')]
    if len(names)>1:
#         for name in names:
        reviewers_flags[names[0]] = reviewers_flags.get(names[0], 0) + 1
        total_recovered+=1
        
reviewers_flags

{'T A Divya': 17,
 'Rutwa': 1,
 'Karthik': 2,
 'Saurav': 4,
 'Divya sravani': 5,
 'Kalpesh': 1,
 'Sneh': 1,
 'Himanshu': 1,
 'Vaishnavi': 2,
 'Gowtham': 4,
 'Raja': 2,
 'Bhumika': 3,
 'karthik': 1,
 'Trusha': 1,
 'Srisamhita': 1,
 'Sakshi': 2}

In [16]:
check_all_characters_present(ke_df,route_surveyed_column_check)

['ROUTE_SURVEYEDCode']

In [35]:
#  Is there a certain route that is getting a lot of changes

route_flags = {}

for index, row in ke_df[(ke_df['FINAL_REVIEWER'].notna()) & (ke_df['Final_Usage'] == 'Remove')].iterrows():
    route = '_'.join(row[route_surveyed_column[0]].split('_')[:-1])
    route_flags[route] = route_flags.get(route, 0) + 1

        
route_flags

{'COT_1_1': 24,
 'COT_1_2': 47,
 'COT_1_22': 16,
 'COT_1_11': 12,
 'COT_1_CMAX': 64,
 'COT_1_10': 41,
 'COT_1_5': 27,
 'COT_1_ZOO': 1,
 'COT_1_42': 1,
 'COT_1_43': 1,
 'COT_1_8': 52,
 'COT_1_35': 1,
 'COT_1_12': 1,
 'COT_1_23': 6,
 'COT_1_24': 1,
 'COT_1_4': 3,
 'COT_1_7': 7,
 'COT_1_6': 3,
 'COT_1_31': 2,
 'COT_1_3': 8,
 'COT_1_32': 1,
 'COT_1_34': 2,
 'COT_1_9': 1,
 'COT_1_102': 8}

In [36]:
#  Is there a certain route that is getting a lot of changes

route_flags = {}

for index, row in ke_df[(ke_df['FINAL_REVIEWER'].notna()) &(ke_df['Final_Usage']=='Use')].iterrows():
    names = [name.strip() for name in row['FINAL_REVIEWER'].replace('.', ',').split(',')]
    if len(names)>1:
        route = '_'.join(row[route_surveyed_column[0]].split('_')[:-1])
        route_flags[route] = route_flags.get(route, 0) + 1

route_flags

{'COT_1_1': 11,
 'COT_1_2': 17,
 'COT_1_22': 2,
 'COT_1_11': 1,
 'COT_1_5': 1,
 'COT_1_CMAX': 6,
 'COT_1_8': 6,
 'COT_1_7': 1,
 'COT_1_24': 1,
 'COT_1_10': 1,
 'COT_1_31': 1}

In [18]:
# Overall summary (Previous transfers-20% are being changed)
total_removed=0
# Is there a reviewer not making any changes and we're getting a lot of our flags on their records to review again
for index, row in ke_df[(ke_df['FINAL_REVIEWER'].notna()) &(ke_df['Final_Usage']=='Remove')].iterrows():
    total_removed+=1
        
total_removed

330

In [19]:
(total_recovered*100)/(total_recovered+total_removed)

12.698412698412698

In [20]:
overall_summary=f'{round((total_recovered * 100) / (total_recovered + total_removed),2)}%'
overall_summary

'12.7%'

In [21]:
pd.DataFrame(list(reviewers_flags.items()), columns=['Reviewer_Name', 'Flagged Records'])

    Reviewer_Name  Flagged Records
0       T A Divya               17
1           Rutwa                1
2         Karthik                2
3          Saurav                4
4   Divya sravani                5
5         Kalpesh                1
6            Sneh                1
7        Himanshu                1
8       Vaishnavi                2
9         Gowtham                4
10           Raja                2
11        Bhumika                3
12        karthik                1
13         Trusha                1
14     Srisamhita                1
15         Sakshi                2

In [22]:
df_reviewer_flags = pd.DataFrame(list(reviewers_flags.items()), columns=['Reviewer_Name', 'Flagged Records'])
df_route_flags = pd.DataFrame(list(route_flags.items()), columns=['Route_Flaged', 'Count'])
df_reviewers_names = pd.DataFrame(list(reviewers_names.items()), columns=['Reviewer_Name', 'Records Reviewed'])

In [23]:
df_reviewers_names

    Reviewer_Name  Records Reviewed
0       T A Divya               180
1          Regina               150
2           Brian               312
3            Sneh               404
4           Rutwa                75
5         Sameera               237
6           Kesar               302
7         Karthik               140
8        Priyanka               100
9          Saurav               233
10  Divya sravani               418
11        Kalpesh               146
12         Trusha               198
13           Raja               200
14       Himanshu               200
15        karthik                92
16      Vaishnavi               200
17        Gowtham               374
18        Bhumika               397
19     Srisamhita               100
20         Sakshi               205
21         muskan                83

In [24]:
df_route_flags

   Route_Flaged  Count
0       COT_1_1     24
1       COT_1_2     47
2      COT_1_22     16
3      COT_1_11     12
4    COT_1_CMAX     64
5      COT_1_10     41
6       COT_1_5     27
7     COT_1_ZOO      1
8      COT_1_42      1
9      COT_1_43      1
10      COT_1_8     52
11     COT_1_35      1
12     COT_1_12      1
13     COT_1_23      6
14     COT_1_24      1
15      COT_1_4      3
16      COT_1_7      7
17      COT_1_6      3
18     COT_1_31      2
19      COT_1_3      8
20     COT_1_32      1
21     COT_1_34      2
22      COT_1_9      1
23    COT_1_102      8

In [25]:
df_reviewer_flags

    Reviewer_Name  Flagged Records
0       T A Divya               17
1           Rutwa                1
2         Karthik                2
3          Saurav                4
4   Divya sravani                5
5         Kalpesh                1
6            Sneh                1
7        Himanshu                1
8       Vaishnavi                2
9         Gowtham                4
10           Raja                2
11        Bhumika                3
12        karthik                1
13         Trusha                1
14     Srisamhita                1
15         Sakshi                2

In [28]:
summary_df = pd.DataFrame({
    'Total_Recovered': [total_recovered],
    'Total_Removed': [total_removed],
    'Overall_Summary': [overall_summary]
})

In [30]:
result_df = pd.concat([df_reviewer_flags, df_route_flags, df_reviewers_names,summary_df], axis=1)

In [31]:
result_df

,Reviewer_Name,Flagged Records,Route_Flaged,Count,Reviewer_Name,Records Reviewed,Total_Recovered,Total_Removed,Overall_Summary
0,T A Divya,17.0,COT_1_1,24,T A Divya,180.0,48.0,330.0,12.7%
1,Rutwa,1.0,COT_1_2,47,Regina,150.0,NaN,NaN,NaN
2,Karthik,2.0,COT_1_22,16,Brian,312.0,NaN,NaN,NaN
3,Saurav,4.0,COT_1_11,12,Sneh,404.0,NaN,NaN,NaN
4,Divya sravani,5.0,COT_1_CMAX,64,Rutwa,75.0,NaN,NaN,NaN
5,Kalpesh,1.0,COT_1_10,41,Sameera,237.0,NaN,NaN,NaN
6,Sneh,1.0,COT_1_5,27,Kesar,302.0,NaN,NaN,NaN
7,Himanshu,1.0,COT_1_ZOO,1,Karthik,140.0,NaN,NaN,NaN
8,Vaishnavi,2.0,COT_1_42,1,Priyanka,100.0,NaN,NaN,NaN
9,Gowtham,4.0,COT_1_43,1,Saurav,233.0,NaN,NaN,NaN
10,Raja,2.0,COT_1_8,52,Divya sravani,418.0,NaN,NaN,NaN
11,Bhumika,3.0,COT_1_35,1,Kalpesh,146.0,NaN,NaN,NaN
12,karthik,1.0,COT_1_12,1,Trusha,198.0,NaN,NaN,NaN
13,Trusha,1.0,COT_1_23,6,Raja,200.0,NaN,NaN,NaN
14,Srisamhita,1.0,COT_1_24,1,Himanshu,200.0,NaN,NaN,NaN
15,Sakshi,2.0,COT_1_4,3,karthik,92.0,NaN,NaN,NaN
16,NaN,NaN,COT_1_7,7,Vaishnavi,200.0,NaN,NaN,NaN
17,NaN,NaN,COT_1_6,3,Gowtham,374.0,NaN,NaN,NaN
18,NaN,NaN,COT_1_31,2,Bhumika,397.0,NaN,NaN,NaN
19,NaN,NaN,COT_1_3,8,Srisamhita,100.0,NaN,NaN,NaN
20,NaN,NaN,COT_1_32,1,Sakshi,205.0,NaN,NaN,NaN
21,NaN,NaN,COT_1_34,2,muskan,83.0,NaN,NaN,NaN
22,NaN,NaN,COT_1_9,1,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,COT_1_102,8,NaN,NaN,NaN,NaN,NaN

In [29]:
summary_df

   Total_Recovered  Total_Removed Overall_Summary
0               48            330           12.7%

In [33]:
result_df.to_csv("New Review.csv",index=False)