In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import warnings
import copy

In [2]:
warnings.filterwarnings('ignore')

In [3]:
def check_all_code_columns(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df_columns_lower if "code" in column]

    return matching_columns


def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

def clean_string(s):
    return s.replace(':', '').replace('-', '').replace(')', '').replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

In [4]:
df=pd.read_csv('seattle_rail2024o2o_export_odbc.csv')

In [5]:
detail_df=pd.read_excel('details_project_od_Seattle2 (1).xlsx',sheet_name='O2O_STOPS')

In [54]:
# Details File Stops Sheet
seq_df=pd.read_excel('details_project_od_Seattle2 (1).xlsx',sheet_name='STOPS')
seq_df.head(3)

,agency,gtfs_date,gtfs_ver,route_short_name,route_long_name,direction_id,route_dir,seq_fixed,stop_id,stop_name,stop_lat,stop_lon,stop_lat6,stop_lon6,ETC_STOP_ID,ETC_STOP_NAME,notes,ETC_ROUTE_ID,ETC_ROUTE_NAME
0,CMT,3/26/2024,1,101,Mariner P&R - Aurora Village,0,101_0,1.0,29-2105,Mariner Park & Ride Bay 3,47.879670,-122.238570,47.879670,-122.238570,CMT_1_101_00_29-2105,Mariner Park & Ride Bay 3,NaN,CMT_1_101_00,CMT_1_101_00
1,CMT,3/26/2024,1,101,Mariner P&R - Aurora Village,0,101_0,2.0,1553,128th St SW & 4th Ave W,47.882044,-122.240279,47.882044,-122.240279,CMT_1_101_00_1553,128th St SW & 4th Ave W,NaN,CMT_1_101_00,CMT_1_101_00
2,CMT,3/26/2024,1,101,Mariner P&R - Aurora Village,0,101_0,3.0,1554,128th St SW & 8th Ave W,47.882001,-122.245798,47.882001,-122.245798,CMT_1_101_00_1554,128th St SW & 8th Ave W,NaN,CMT_1_101_00,CMT_1_101_00

In [6]:
code_columns=check_all_code_columns(df,df.columns)

In [7]:
code_columns

['routesurveyedcode',
 'sssloncode',
 'sssloffcode',
 's1loncode',
 's1loffcode',
 'sttaconcode',
 'sttacoffcode',
 'timeboardedcode',
 'languagecode']

In [7]:
code_columns=check_all_characters_present(df,code_columns)
code_columns

['ROUTE_SURVEYED_Code_',
 'STLINE2_ON_Code_',
 'STLINE2_OFF_Code_',
 'SSSL_ON_Code_',
 'SSSL_OFF_Code_',
 'S1L_ON_Code_',
 'S1L_OFF_Code_',
 'STTAC_ON_Code_',
 'STTAC_OFF_Code_',
 'TIME_BOARDED_Code_',
 'LANGUAGE_Code_']

In [8]:
columns_to_remove=[]
for column in code_columns:
    cleaned_column=clean_string(column)
#     if 'routesurveyed' in cleaned_column or 'language' in cleaned_column:
    if 'time' in cleaned_column or 'language' in cleaned_column:
        columns_to_remove.append(column)

In [9]:
columns_to_remove

['TIME_BOARDED_Code_', 'LANGUAGE_Code_']

In [10]:
o2o_df=copy.deepcopy(df)

In [11]:
new_df=o2o_df.drop(columns=columns_to_remove)

In [12]:
new_df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,S1L_OFF_Code_,S1L_OFF,STTAC_ON_Code_,STTAC_ON,STTAC_OFF_Code_,STTAC_OFF,TIME_BOARDED,LANGUAGE,LANGUAGE_Other_,RESTART_URL
0,105535,2024-09-25 10:25:52,4,en,2024-09-25 10:25:27,2024-09-25 10:25:52,172.56.94.134,NaN,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,PM Peak (3:00-6:29pm),NaN,NaN,NaN
1,105544,2024-10-02 15:27:40,4,en,2024-10-02 15:27:29,2024-10-02 15:27:40,136.37.108.111,https://seattle-od.etc-research.com/,-25200,999,...,NaN,NaN,NaN,NaN,NaN,NaN,AM Peak (Before 9:00am),NaN,NaN,NaN
2,105546,2024-10-07 08:05:52,4,en,2024-10-07 08:05:21,2024-10-07 08:05:52,172.56.105.118,https://seattle-od.etc-research.com/,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,AM Peak (Before 9:00am),NaN,NaN,NaN
3,105547,2024-10-07 08:08:37,4,en,2024-10-07 08:05:53,2024-10-07 08:08:37,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,AM Peak (Before 9:00am),NaN,NaN,NaN
4,105548,2024-10-07 08:08:48,4,en,2024-10-07 08:08:38,2024-10-07 08:08:48,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,NaN,AM Peak (Before 9:00am),NaN,NaN,NaN

In [13]:
code_columns_check=check_all_characters_present(new_df,code_columns)

new_code_columns=check_all_characters_present(new_df,code_columns_check)
new_code_columns

['ROUTE_SURVEYED_Code_',
 'STLINE2_ON_Code_',
 'STLINE2_OFF_Code_',
 'SSSL_ON_Code_',
 'SSSL_OFF_Code_',
 'S1L_ON_Code_',
 'S1L_OFF_Code_',
 'STTAC_ON_Code_',
 'STTAC_OFF_Code_']

In [14]:
route_surveyed_column_check=['routesurveyed']
route_surveyed_column=check_all_characters_present(new_df,route_surveyed_column_check)
route_surveyed_column[0]

'ROUTE_SURVEYED'

In [15]:
def get_route_line(x):
    b_values=str(x).split('(')
#     print(b_values)
    if len(b_values)>1:
        join_value=" ".join(b_values[:-1]).strip()
#         values=(" ".join(b_values[:-1]).strip()).split(' ')
        values=str(join_value).split(' ')
        return values[-2]
    else:
        values=str(x).split(' ')
        if len(values)>1:
            return values[-2]
        return x

In [16]:
get_route_line('ST T Line (Tacoma)')

'T'

In [17]:
get_route_line('ST SOUNDER S LINE')

'S'

In [18]:
get_route_line('Other')

'Other'

In [19]:
get_route_line(" ".join('ST T Line (Tacoma)'.split('(')[:-1]).strip())

'T'

In [20]:
new_df['Line_Value']=new_df[route_surveyed_column[0]].apply(get_route_line)

In [22]:
new_df[new_df['Line_Value']=='2']

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,S1L_OFF,STTAC_ON_Code_,STTAC_ON,STTAC_OFF_Code_,STTAC_OFF,TIME_BOARDED,LANGUAGE,LANGUAGE_Other_,RESTART_URL,Line_Value
0,105535,2024-09-25 10:25:52,4,en,2024-09-25 10:25:27,2024-09-25 10:25:52,172.56.94.134,NaN,-25200,999,...,NaN,NaN,NaN,NaN,NaN,PM Peak (3:00-6:29pm),NaN,NaN,NaN,2
2,105546,2024-10-07 08:05:52,4,en,2024-10-07 08:05:21,2024-10-07 08:05:52,172.56.105.118,https://seattle-od.etc-research.com/,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,AM Peak (Before 9:00am),NaN,NaN,NaN,2
3,105547,2024-10-07 08:08:37,4,en,2024-10-07 08:05:53,2024-10-07 08:08:37,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,AM Peak (Before 9:00am),NaN,NaN,NaN,2
4,105548,2024-10-07 08:08:48,4,en,2024-10-07 08:08:38,2024-10-07 08:08:48,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,AM Peak (Before 9:00am),NaN,NaN,NaN,2
5,105549,2024-10-07 08:09:10,4,en,2024-10-07 08:08:49,2024-10-07 08:09:10,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,NaN,NaN,NaN,NaN,NaN,AM Peak (Before 9:00am),NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156,106813,2024-10-11 19:08:51,4,en,2024-10-11 19:08:36,2024-10-11 19:08:51,172.56.105.218,https://seattle-od.etc-research.com/,-25200,LSS,...,NaN,NaN,NaN,NaN,NaN,Evening (6:30pm later),NaN,NaN,NaN,2
1157,106814,2024-10-11 19:09:06,4,en,2024-10-11 19:08:51,2024-10-11 19:09:06,172.56.105.218,https://seattle-od.etc-research.com/index.php/...,-25200,LSS,...,NaN,NaN,NaN,NaN,NaN,Evening (6:30pm later),NaN,NaN,NaN,2
1158,106816,2024-10-11 19:13:03,4,en,2024-10-11 19:12:43,2024-10-11 19:13:03,172.56.109.107,https://seattle-od.etc-research.com/,-25200,LSS,...,NaN,NaN,NaN,NaN,NaN,Evening (6:30pm later),NaN,NaN,NaN,2
1159,106817,2024-10-11 19:13:11,4,en,2024-10-11 19:13:03,2024-10-11 19:13:11,172.56.109.107,https://seattle-od.etc-research.com/index.php/...,-25200,LSS,...,NaN,NaN,NaN,NaN,NaN,Evening (6:30pm later),NaN,NaN,NaN,2
1160,106818,2024-10-11 19:13:25,4,en,2024-10-11 19:13:12,2024-10-11 19:13:25,172.56.109.107,https://seattle-od.etc-research.com/index.php/...,-25200,LSS,...,NaN,NaN,NaN,NaN,NaN,Evening (6:30pm later),NaN,NaN,NaN,2

In [23]:
def get_detail_route_line(x):
    values=str(x).split('_')
    if len(values)>1:
        return values[-2][0]
    else:
        return x

In [24]:
get_detail_route_line('SND_1_TLine_00')

'T'

In [25]:
detail_df['Line_Value']=detail_df['ETC_ROUTE_ID'].apply(get_detail_route_line)

In [29]:
detail_df['Line_Value'].unique()

array(['S', '1', 'T', '2'], dtype=object)

In [30]:
detail_df[detail_df['Line_Value']=='2']

,STOP_ID,STOP_NAME,ETC_STOP_ID,ETC_STOP_NAME,notes,ETC_ROUTE_ID,ETC_ROUTE_NAME,Line_Value
40,1,South Bellevue,SND_1_2Line_00_E09-T2,South Bellevue,NaN,SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2
41,2,East Main,SND_1_2Line_00_E11-T2,East Main,NaN,SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2
42,3,Bellevue Downtown,SND_1_2Line_00_E15-T2,Bellevue Downtown,NaN,SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2
43,4,Wilburton,SND_1_2Line_00_E19-T2,Wilburton,NaN,SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2
44,5,Spring District,SND_1_2Line_00_E21-T2,Spring District,NaN,SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2
45,6,BelRed,SND_1_2Line_00_E23-T2,BelRed,NaN,SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2
46,7,Overlake Village,SND_1_2Line_00_E25-T2,Overlake Village,NaN,SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2
47,8,Redmond Technology,SND_1_2Line_00_E27-T1,Redmond Technology,NaN,SND_1_2Line_00,(Sound) 2 Line South Bellevue - Redmond Tech [...,2

In [27]:
new_code_columns

['ROUTE_SURVEYED_Code_',
 'SSSL_ON_Code_',
 'SSSL_OFF_Code_',
 'S1L_ON_Code_',
 'S1L_OFF_Code_',
 'STTAC_ON_Code_',
 'STTAC_OFF_Code_']

In [34]:
for _, row in new_df.iterrows():
    counter = 0
    for i in range(1, len(new_code_columns)):
        seq_value = row[code_columns[i]]
        value_column_check = [''.join(part for part in code_columns[i].split('_') if part.lower() != 'code').lower()]
        value_column = check_all_characters_present(new_df, value_column_check)
        value = row[value_column[0]]
        
        if not pd.isnull(value):
            stop_value = value
            matched_value = detail_df[
                (detail_df['Line_Value'] == row['Line_Value']) & 
                (detail_df['STOP_ID'] == seq_value) & 
                (detail_df['ETC_STOP_NAME'] == value)
            ]
            
            if not matched_value.empty:
                counter += 1
                if counter == 1:
                    # Set boarding stop details
                    new_df.loc[row.name, [
                        'ROUTE_DESCRIPTION[CODE]', 'ETC_ROUTE_NAME', 'BOARD_ID', 
                        'BOARD_STOP[CODE]', 'BOARD_STOP_NAME'
                    ]] = [
                        matched_value.iloc[0]['ETC_ROUTE_ID'], 
                        matched_value.iloc[0]['ETC_ROUTE_NAME'], 
                        matched_value.iloc[0]['STOP_ID'], 
                        matched_value.iloc[0]['ETC_STOP_ID'], 
                        matched_value.iloc[0]['ETC_STOP_NAME']
                    ]
                elif counter > 1:
                    # Set alighting stop details
                    new_df.loc[row.name, [
                        'ALIGHT_ID', 'ALIGHT_STOP[CODE]', 'ALIGHT_STOP_NAME'
                    ]] = [
                        matched_value.iloc[0]['STOP_ID'], 
                        matched_value.iloc[0]['ETC_STOP_ID'], 
                        matched_value.iloc[0]['ETC_STOP_NAME']
                    ]

In [36]:
new_df[['id','ROUTE_DESCRIPTION[CODE]','BOARD_ID', 'BOARD_STOP[CODE]', 'BOARD_STOP_NAME','ALIGHT_ID','ALIGHT_STOP[CODE]', 'ALIGHT_STOP_NAME']]

,id,ROUTE_DESCRIPTION[CODE],BOARD_ID,BOARD_STOP[CODE],BOARD_STOP_NAME,ALIGHT_ID,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME
0,105535,SND_1_2Line_00,8.0,SND_1_2Line_00_E27-T1,Redmond Technology,4.0,SND_1_2Line_00_E19-T2,Wilburton
1,105544,SND_1_SLine_00,2.0,SND_1_SLine_00_STKSB,Tukwila Station (Southbound),3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound)
2,105546,SND_1_2Line_00,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown
3,105547,SND_1_2Line_00,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown
4,105548,SND_1_2Line_00,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown
...,...,...,...,...,...,...,...,...
1156,106813,SND_1_2Line_00,4.0,SND_1_2Line_00_E19-T2,Wilburton,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown
1157,106814,SND_1_2Line_00,5.0,SND_1_2Line_00_E21-T2,Spring District,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown
1158,106816,SND_1_2Line_00,4.0,SND_1_2Line_00_E19-T2,Wilburton,2.0,SND_1_2Line_00_E11-T2,East Main
1159,106817,SND_1_2Line_00,5.0,SND_1_2Line_00_E21-T2,Spring District,2.0,SND_1_2Line_00_E11-T2,East Main
1160,106818,SND_1_2Line_00,5.0,SND_1_2Line_00_E21-T2,Spring District,2.0,SND_1_2Line_00_E11-T2,East Main

In [37]:
new_df['SEQ_CHECK'] = new_df['ALIGHT_ID'] - new_df['BOARD_ID']

In [55]:
ids_list = []
for _, row in new_df.iterrows():
    if row['SEQ_CHECK'] < 0:
        # Extract route code and modify it
        ids_list.append(row['id'])

        route_code = row['ROUTE_DESCRIPTION[CODE]']
        new_route_code = f"{'_'.join(route_code.split('_')[:-1])}_01" if route_code.split('_')[-1] == '00' else f"{'_'.join(route_code.split('_')[:-1])}_00"
        
        # Get new route name
        new_route_name_row = seq_df[seq_df['ETC_ROUTE_ID'] == new_route_code]
        if not new_route_name_row.empty:
            new_route_name = new_route_name_row['ETC_ROUTE_NAME'].iloc[0]
        else:
            # Handle the case when the new route name is not found
            continue  # Skip to the next iteration if new route code is not valid

        # Board stop details
        board_stop_row = seq_df[(seq_df['ETC_ROUTE_ID'] == new_route_code) & (seq_df['ETC_STOP_NAME'] == row['BOARD_STOP_NAME'])]
        if not board_stop_row.empty:
            board_stop_code = board_stop_row['ETC_STOP_ID'].iloc[0]
            board_stop_lat_lon = board_stop_row[['seq_fixed', 'stop_lat6', 'stop_lon6']].iloc[0]
        else:
            # Skip if no board stop information is found
            continue

        # Alight stop details
        alight_stop_row = seq_df[(seq_df['ETC_ROUTE_ID'] == new_route_code) & (seq_df['ETC_STOP_NAME'] == row['ALIGHT_STOP_NAME'])]
        if not alight_stop_row.empty:
            alight_stop_code = alight_stop_row['ETC_STOP_ID'].iloc[0]
            alight_stop_lat_lon = alight_stop_row[['seq_fixed', 'stop_lat6', 'stop_lon6']].iloc[0]
        else:
            # Skip if no alight stop information is found
            continue

        # Update new_df with the retrieved values
        new_df.loc[row.name, 'ROUTE_DESCRIPTION[CODE]'] = new_route_code
        new_df.loc[row.name, 'ETC_ROUTE_NAME'] = new_route_name

        new_df.loc[row.name, 'Board_Seq'] = board_stop_lat_lon['seq_fixed']
        new_df.loc[row.name, 'BOARD_STOP[CODE]'] = board_stop_code

        new_df.loc[row.name, 'BOARD_STOP_ON_LAT'] = board_stop_lat_lon['stop_lat6']
        new_df.loc[row.name, 'BOARD_STOP_ON_LONG'] = board_stop_lat_lon['stop_lon6']

        new_df.loc[row.name, 'Alight_Seq'] = alight_stop_lat_lon['seq_fixed']
        new_df.loc[row.name, 'ALIGHT_STOP[CODE]'] = alight_stop_code

        new_df.loc[row.name, 'ALIGHT_STOP_ON_LAT'] = alight_stop_lat_lon['stop_lat6']
        new_df.loc[row.name, 'ALIGHT_STOP_ON_LONG'] = alight_stop_lat_lon['stop_lon6']

In [58]:
new_df[['id','ROUTE_DESCRIPTION[CODE]','BOARD_ID', 'BOARD_STOP[CODE]', 'BOARD_STOP_NAME','ALIGHT_ID','ALIGHT_STOP[CODE]', 'ALIGHT_STOP_NAME']]

,id,ROUTE_DESCRIPTION[CODE],BOARD_ID,BOARD_STOP[CODE],BOARD_STOP_NAME,ALIGHT_ID,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME
0,105535,SND_1_2Line_01,8.0,SND_1_2Line_01_E27-T1,Redmond Technology,4.0,SND_1_2Line_01_E19-T1,Wilburton
1,105544,SND_1_SLine_00,2.0,SND_1_SLine_00_STKSB,Tukwila Station (Southbound),3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound)
2,105546,SND_1_2Line_00,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown
3,105547,SND_1_2Line_00,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown
4,105548,SND_1_2Line_00,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown
...,...,...,...,...,...,...,...,...
1156,106813,SND_1_2Line_01,4.0,SND_1_2Line_01_E19-T1,Wilburton,3.0,SND_1_2Line_01_E15-T1,Bellevue Downtown
1157,106814,SND_1_2Line_01,5.0,SND_1_2Line_01_E21-T1,Spring District,3.0,SND_1_2Line_01_E15-T1,Bellevue Downtown
1158,106816,SND_1_2Line_01,4.0,SND_1_2Line_01_E19-T1,Wilburton,2.0,SND_1_2Line_01_E11-T1,East Main
1159,106817,SND_1_2Line_01,5.0,SND_1_2Line_01_E21-T1,Spring District,2.0,SND_1_2Line_01_E11-T1,East Main
1160,106818,SND_1_2Line_01,5.0,SND_1_2Line_01_E21-T1,Spring District,2.0,SND_1_2Line_01_E11-T1,East Main

In [38]:
new_df=pd.merge(new_df,df[['id','TIME_BOARDED_Code_']],on='id',how='left')

In [39]:
new_df[['id','TIME_BOARDED_Code_','TIME_BOARDED']]

          id TIME_BOARDED_Code_             TIME_BOARDED
0     105535                PM1    PM Peak (3:00-6:29pm)
1     105544                 AM  AM Peak (Before 9:00am)
2     105546                 AM  AM Peak (Before 9:00am)
3     105547                 AM  AM Peak (Before 9:00am)
4     105548                 AM  AM Peak (Before 9:00am)
...      ...                ...                      ...
1156  106813                PM2   Evening (6:30pm later)
1157  106814                PM2   Evening (6:30pm later)
1158  106816                PM2   Evening (6:30pm later)
1159  106817                PM2   Evening (6:30pm later)
1160  106818                PM2   Evening (6:30pm later)

[1161 rows x 3 columns]

In [32]:
# new_df[['Completed','TIME_BOARDED_Code_','TIME_BOARDED']]=new_df[['Completed','TIME_BOARDED_Code_','TIME_BOARDED']].fillna(method='ffill')

In [40]:
def get_day_name(x):
    if pd.isna(x):
        return np.nan
    x = str(x)
    try:
        date_object = datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
    except ValueError:
        try:
            date_object = datetime.strptime(x, '%d/%m/%Y %H:%M')
        except ValueError:
            return np.nan
    day_name = date_object.strftime('%A')
    if day_name in ['Saturday', 'Sunday']:
        return 'Weekend'
    return 'Weekday'

In [41]:
new_df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,BOARD_ID,BOARD_STOP[CODE],BOARD_STOP_NAME,ALIGHT_ID,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME,BOARD_SEQ,ALIGHT_SEQ,SEQ_CHECK,TIME_BOARDED_Code_
0,105535,2024-09-25 10:25:52,4,en,2024-09-25 10:25:27,2024-09-25 10:25:52,172.56.94.134,NaN,-25200,999,...,8.0,SND_1_2Line_00_E27-T1,Redmond Technology,4.0,SND_1_2Line_00_E19-T2,Wilburton,8.0,4.0,-4.0,PM1
1,105544,2024-10-02 15:27:40,4,en,2024-10-02 15:27:29,2024-10-02 15:27:40,136.37.108.111,https://seattle-od.etc-research.com/,-25200,999,...,2.0,SND_1_SLine_00_STKSB,Tukwila Station (Southbound),3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound),NaN,NaN,1.0,AM
2,105546,2024-10-07 08:05:52,4,en,2024-10-07 08:05:21,2024-10-07 08:05:52,172.56.105.118,https://seattle-od.etc-research.com/,-25200,ANC,...,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown,1.0,3.0,2.0,AM
3,105547,2024-10-07 08:08:37,4,en,2024-10-07 08:05:53,2024-10-07 08:08:37,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown,1.0,3.0,2.0,AM
4,105548,2024-10-07 08:08:48,4,en,2024-10-07 08:08:38,2024-10-07 08:08:48,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,1.0,SND_1_2Line_00_E09-T2,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown,1.0,3.0,2.0,AM

In [42]:
new_df[['Completed']].values[0][0]

'2024-09-25 10:25:52'

In [43]:
get_day_name(new_df[['Completed']].values[0][0])

'Weekday'

In [44]:
new_df['Date'] = np.where(new_df['Completed'].notna(), new_df['Completed'], new_df['Date_started'])

In [45]:
new_df['Day']=new_df['Date'].apply(get_day_name)

In [46]:
new_df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,BOARD_STOP_NAME,ALIGHT_ID,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME,BOARD_SEQ,ALIGHT_SEQ,SEQ_CHECK,TIME_BOARDED_Code_,Date,Day
0,105535,2024-09-25 10:25:52,4,en,2024-09-25 10:25:27,2024-09-25 10:25:52,172.56.94.134,NaN,-25200,999,...,Redmond Technology,4.0,SND_1_2Line_00_E19-T2,Wilburton,8.0,4.0,-4.0,PM1,2024-09-25 10:25:52,Weekday
1,105544,2024-10-02 15:27:40,4,en,2024-10-02 15:27:29,2024-10-02 15:27:40,136.37.108.111,https://seattle-od.etc-research.com/,-25200,999,...,Tukwila Station (Southbound),3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound),NaN,NaN,1.0,AM,2024-10-02 15:27:40,Weekday
2,105546,2024-10-07 08:05:52,4,en,2024-10-07 08:05:21,2024-10-07 08:05:52,172.56.105.118,https://seattle-od.etc-research.com/,-25200,ANC,...,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown,1.0,3.0,2.0,AM,2024-10-07 08:05:52,Weekday
3,105547,2024-10-07 08:08:37,4,en,2024-10-07 08:05:53,2024-10-07 08:08:37,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown,1.0,3.0,2.0,AM,2024-10-07 08:08:37,Weekday
4,105548,2024-10-07 08:08:48,4,en,2024-10-07 08:08:38,2024-10-07 08:08:48,172.56.107.32,https://seattle-od.etc-research.com/index.php/...,-25200,ANC,...,South Bellevue,3.0,SND_1_2Line_00_E15-T2,Bellevue Downtown,1.0,3.0,2.0,AM,2024-10-07 08:08:48,Weekday

In [47]:
new_df[new_df['Day']=='Weekend']

Empty DataFrame
Columns: [id, Completed, Last_page, Start_language, Date_started, Date_last_action, IP_address, Referring_URL, TIME_ADJUST, INTERV_INIT, ORIGRESPID, ROUTE_SURVEYED_Code_, ROUTE_SURVEYED, ROUTE_SURVEYED_Other_, STLINE2_ON_Code_, STLINE2_ON, STLINE2_OFF_Code_, STLINE2_OFF, SSSL_ON_Code_, SSSL_ON, SSSL_OFF_Code_, SSSL_OFF, S1L_ON_Code_, S1L_ON, S1L_OFF_Code_, S1L_OFF, STTAC_ON_Code_, STTAC_ON, STTAC_OFF_Code_, STTAC_OFF, TIME_BOARDED, LANGUAGE, LANGUAGE_Other_, RESTART_URL, Line_Value, ROUTE_DESCRIPTION[CODE], ETC_ROUTE_NAME, BOARD_ID, BOARD_STOP[CODE], BOARD_STOP_NAME, ALIGHT_ID, ALIGHT_STOP[CODE], ALIGHT_STOP_NAME, BOARD_SEQ, ALIGHT_SEQ, SEQ_CHECK, TIME_BOARDED_Code_, Date, Day]
Index: []

[0 rows x 49 columns]

In [48]:
new_df['TIME_BOARDED']

0         PM Peak (3:00-6:29pm)
1       AM Peak (Before 9:00am)
2       AM Peak (Before 9:00am)
3       AM Peak (Before 9:00am)
4       AM Peak (Before 9:00am)
                 ...
1156     Evening (6:30pm later)
1157     Evening (6:30pm later)
1158     Evening (6:30pm later)
1159     Evening (6:30pm later)
1160     Evening (6:30pm later)
Name: TIME_BOARDED, Length: 1161, dtype: object

In [49]:
new_df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT', 'ORIGRESPID', 'ROUTE_SURVEYED_Code_', 'ROUTE_SURVEYED',
       'ROUTE_SURVEYED_Other_', 'STLINE2_ON_Code_', 'STLINE2_ON',
       'STLINE2_OFF_Code_', 'STLINE2_OFF', 'SSSL_ON_Code_', 'SSSL_ON',
       'SSSL_OFF_Code_', 'SSSL_OFF', 'S1L_ON_Code_', 'S1L_ON', 'S1L_OFF_Code_',
       'S1L_OFF', 'STTAC_ON_Code_', 'STTAC_ON', 'STTAC_OFF_Code_', 'STTAC_OFF',
       'TIME_BOARDED', 'LANGUAGE', 'LANGUAGE_Other_', 'RESTART_URL',
       'Line_Value', 'ROUTE_DESCRIPTION[CODE]', 'ETC_ROUTE_NAME', 'BOARD_ID',
       'BOARD_STOP[CODE]', 'BOARD_STOP_NAME', 'ALIGHT_ID', 'ALIGHT_STOP[CODE]',
       'ALIGHT_STOP_NAME', 'BOARD_SEQ', 'ALIGHT_SEQ', 'SEQ_CHECK',
       'TIME_BOARDED_Code_', 'Date', 'Day'],
      dtype='object')

In [43]:
# def get_time_period_value(x):
#     if x=='PM1':
#         return 'PM'
#     elif x=='PM2':
#         return 'Evening'
#     elif x=='MID':
#         return 'MIDDAY'
#     elif x=='AM':
#         return 'AM'
#     else:
#         return x
    
# new_df['TIME PERIOD']=new_df['TIME_BOARDED_Code_'].apply(get_time_period_value)

In [44]:
# new_df[['TIME PERIOD']]

In [50]:

time_period_mapping = {
    'PM1': 'PM',
    'PM2': 'Evening',
    'MID': 'MIDDAY',
    'AM': 'AM'
}

time_period_code_mapping = {
    'PM':2,
    'Evening':4,
    'MIDDAY':1,
    'AM': 0
}

new_df['TIME PERIOD'] = new_df['TIME_BOARDED_Code_'].map(time_period_mapping).fillna(new_df['TIME_BOARDED_Code_'])
new_df['TIME PERIOD[Code]'] = new_df['TIME PERIOD'].map(time_period_code_mapping)

In [51]:
new_df[['TIME PERIOD','TIME PERIOD[Code]']]

     TIME PERIOD  TIME PERIOD[Code]
0             PM                  2
1             AM                  0
2             AM                  0
3             AM                  0
4             AM                  0
...          ...                ...
1156     Evening                  4
1157     Evening                  4
1158     Evening                  4
1159     Evening                  4
1160     Evening                  4

[1161 rows x 2 columns]

In [52]:
new_df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT', 'ORIGRESPID', 'ROUTE_SURVEYED_Code_', 'ROUTE_SURVEYED',
       'ROUTE_SURVEYED_Other_', 'STLINE2_ON_Code_', 'STLINE2_ON',
       'STLINE2_OFF_Code_', 'STLINE2_OFF', 'SSSL_ON_Code_', 'SSSL_ON',
       'SSSL_OFF_Code_', 'SSSL_OFF', 'S1L_ON_Code_', 'S1L_ON', 'S1L_OFF_Code_',
       'S1L_OFF', 'STTAC_ON_Code_', 'STTAC_ON', 'STTAC_OFF_Code_', 'STTAC_OFF',
       'TIME_BOARDED', 'LANGUAGE', 'LANGUAGE_Other_', 'RESTART_URL',
       'Line_Value', 'ROUTE_DESCRIPTION[CODE]', 'ETC_ROUTE_NAME', 'BOARD_ID',
       'BOARD_STOP[CODE]', 'BOARD_STOP_NAME', 'ALIGHT_ID', 'ALIGHT_STOP[CODE]',
       'ALIGHT_STOP_NAME', 'BOARD_SEQ', 'ALIGHT_SEQ', 'SEQ_CHECK',
       'TIME_BOARDED_Code_', 'Date', 'Day', 'TIME PERIOD',
       'TIME PERIOD[Code]'],
      dtype='object')

In [53]:
new_df[['ETC_ROUTE_NAME','ALIGHT_STOP_NAME','BOARD_STOP_NAME']]

,ETC_ROUTE_NAME,ALIGHT_STOP_NAME,BOARD_STOP_NAME
0,(Sound) 2 Line South Bellevue - Redmond Tech [...,Wilburton,Redmond Technology
1,(Sound) S Line Seattle - Tacoma/Lakewood [SOUT...,Kent Station (Southbound),Tukwila Station (Southbound)
2,(Sound) 2 Line South Bellevue - Redmond Tech [...,Bellevue Downtown,South Bellevue
3,(Sound) 2 Line South Bellevue - Redmond Tech [...,Bellevue Downtown,South Bellevue
4,(Sound) 2 Line South Bellevue - Redmond Tech [...,Bellevue Downtown,South Bellevue
...,...,...,...
1156,(Sound) 2 Line South Bellevue - Redmond Tech [...,Bellevue Downtown,Wilburton
1157,(Sound) 2 Line South Bellevue - Redmond Tech [...,Bellevue Downtown,Spring District
1158,(Sound) 2 Line South Bellevue - Redmond Tech [...,East Main,Wilburton
1159,(Sound) 2 Line South Bellevue - Redmond Tech [...,East Main,Spring District
1160,(Sound) 2 Line South Bellevue - Redmond Tech [...,East Main,Spring District

In [73]:
data=new_df[['ETC_ROUTE_NAME','ALIGHT_STOP_NAME','BOARD_STOP_NAME']].values[0]
route_name=data[0]
alight_name=data[1]
board_name=data[2]

In [74]:
data,route_name,alight_name,board_name

(array(['(Sound) 1 Line Northgate - Angle Lake [NORTHBOUND]',
        "Tukwila Int'l Blvd", 'Northgate'], dtype=object),
 '(Sound) 1 Line Northgate - Angle Lake [NORTHBOUND]',
 "Tukwila Int'l Blvd",
 'Northgate')

In [75]:
seq_df[(seq_df['ETC_ROUTE_NAME']==route_name)&(seq_df['ETC_STOP_NAME']==alight_name)][['seq_fixed']]

       seq_fixed
19140          3

In [76]:
seq_df[(seq_df['ETC_ROUTE_NAME']==route_name)&(seq_df['ETC_STOP_NAME']==board_name)][['seq_fixed']]

       seq_fixed
19156         19
19157         19

In [59]:
new_df.dropna(subset=['ROUTE_DESCRIPTION[CODE]','BOARD_ID', 'BOARD_STOP[CODE]', 'BOARD_STOP_NAME','ALIGHT_ID', 'ALIGHT_STOP[CODE]', 'ALIGHT_STOP_NAME'],inplace=True)

In [61]:
new_df=new_df[new_df['INTERV_INIT']!='999']

In [62]:
new_df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,BOARD_STOP[CODE],BOARD_STOP_NAME,ALIGHT_ID,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME,TIME_BOARDED_Code_,Date,Day,TIME PERIOD,TIME PERIOD[Code]
5,81166,2024-04-02 18:39:37,4,en,2024-04-02 18:38:58,2024-04-02 18:39:37,70.113.126.123,https://seattle-od.etc-research.com/,-25200,BAC,...,SND_1_1Line_01_990006,Northgate,3.0,SND_1_1Line_01_99905,Tukwila Int'l Blvd,AM,2024-04-02 18:39:37,Weekday,AM,0.0
11,81173,2024-04-08 06:03:32,4,en,2024-04-08 05:40:09,2024-04-08 06:03:32,172.56.105.131,https://seattle-od.etc-research.com/,-25200,BLN,...,SND_1_SLine_00_SLW,Lakewood Station,7.0,SND_1_SLine_00_STD,Tacoma Dome Station,AM,2024-04-08 06:03:32,Weekday,AM,0.0
12,81174,2024-04-08 06:04:32,4,en,2024-04-08 06:03:32,2024-04-08 06:04:32,172.56.105.131,https://seattle-od.etc-research.com/index.php/...,-25200,BLN,...,SND_1_SLine_00_SLW,Lakewood Station,4.0,SND_1_SLine_00_SAUSB,Auburn Station (Southbound),AM,2024-04-08 06:04:32,Weekday,AM,0.0
13,81175,2024-04-08 06:05:41,4,en,2024-04-08 06:04:33,2024-04-08 06:05:41,172.56.105.131,https://seattle-od.etc-research.com/index.php/...,-25200,BLN,...,SND_1_SLine_00_SLW,Lakewood Station,3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound),AM,2024-04-08 06:05:41,Weekday,AM,0.0
14,81176,2024-04-08 06:06:04,4,en,2024-04-08 06:05:42,2024-04-08 06:06:04,172.56.105.131,https://seattle-od.etc-research.com/index.php/...,-25200,BLN,...,SND_1_SLine_00_SST,South Tacoma Station,3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound),AM,2024-04-08 06:06:04,Weekday,AM,0.0

In [71]:
for _, row in new_df.iterrows():
    # Extract the alight sequence
    alight_seq_df = seq_df[(seq_df['ETC_ROUTE_NAME'] == row['ETC_ROUTE_NAME']) & 
                           (seq_df['ETC_STOP_NAME'] == row['ALIGHT_STOP_NAME'])][['seq_fixed']]
    if not alight_seq_df.empty:
        alight_seq = alight_seq_df.iloc[0, 0]
    else:
        alight_seq = np.nan
    
    # Extract the board sequence
    board_seq_df = seq_df[(seq_df['ETC_ROUTE_NAME'] == row['ETC_ROUTE_NAME']) & 
                          (seq_df['ETC_STOP_NAME'] == row['BOARD_STOP_NAME'])][['seq_fixed']]
    if not board_seq_df.empty:
        board_seq = board_seq_df.iloc[0, 0]
    else:
        board_seq = np.nan

    # Assign values to new_df
    new_df.loc[row.name, 'Alight_Seq'] = alight_seq
    new_df.loc[row.name, 'Board_Seq'] = board_seq

In [77]:
new_df[['Alight_Seq','Board_Seq']].tail()

       Alight_Seq  Board_Seq
23356        13.0        7.0
23357        19.0        7.0
23358        15.0        7.0
23359        13.0        7.0
23360         2.0        1.0

In [78]:
for _,row in new_df.iterrows():
    new_df.loc[row.name,'SEQ_CHECK']=row['Alight_Seq']-row['Board_Seq']

In [79]:
new_df[['SEQ_CHECK']]

       SEQ_CHECK
5          -16.0
11          -2.0
12          -5.0
13          -6.0
14          -5.0
...          ...
23356        6.0
23357       12.0
23358        8.0
23359        6.0
23360        1.0

[22798 rows x 1 columns]

In [81]:
number=6
if number>0:
    print("Number is Positive")

Number is Positive

In [83]:
new_df[new_df['SEQ_CHECK']==0][['ETC_ROUTE_NAME','ALIGHT_STOP_NAME','BOARD_STOP_NAME']]

,ETC_ROUTE_NAME,ALIGHT_STOP_NAME,BOARD_STOP_NAME
291,(Sound) S Line Seattle - Tacoma/Lakewood [SOUT...,Sumner Station (Southbound),Sumner Station (Southbound)
1323,(Sound) 1 Line Northgate - Angle Lake [NORTHBO...,SeaTac/Airport,SeaTac/Airport
1792,(Sound) 1 Line Northgate - Angle Lake [NORTHBO...,Northgate,Northgate
2184,(Sound) S Line Seattle - Tacoma/Lakewood [SOUT...,King Street Station,King Street Station
3114,(Sound) S Line Seattle - Tacoma/Lakewood [SOUT...,Tukwila Station (Southbound),Tukwila Station (Southbound)
...,...,...,...
22072,(Sound) 1 Line Northgate - Angle Lake [NORTHBO...,Roosevelt,Roosevelt
22104,(Sound) 1 Line Northgate - Angle Lake [NORTHBO...,Univ of Washington,Univ of Washington
22339,(Sound) 1 Line Northgate - Angle Lake [NORTHBO...,U District,U District
22515,(Sound) 1 Line Northgate - Angle Lake [NORTHBO...,Rainier Beach,Rainier Beach
22638,(Sound) 1 Line Northgate - Angle Lake [NORTHBO...,Beacon Hill,Beacon Hill

In [84]:
new_df = new_df[new_df['SEQ_CHECK'] != 0].copy()

In [85]:
new_df[new_df['SEQ_CHECK']==0][['ETC_ROUTE_NAME','ALIGHT_STOP_NAME','BOARD_STOP_NAME']]

Empty DataFrame
Columns: [ETC_ROUTE_NAME, ALIGHT_STOP_NAME, BOARD_STOP_NAME]
Index: []

In [86]:
new_df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME,TIME_BOARDED_Code_,Date,Day,TIME PERIOD,TIME PERIOD[Code],Alight_Seq,Board_Seq,SEQ_CHECK
5,81166,2024-04-02 18:39:37,4,en,2024-04-02 18:38:58,2024-04-02 18:39:37,70.113.126.123,https://seattle-od.etc-research.com/,-25200,BAC,...,SND_1_1Line_01_99905,Tukwila Int'l Blvd,AM,2024-04-02 18:39:37,Weekday,AM,0.0,3.0,19.0,-16.0
11,81173,2024-04-08 06:03:32,4,en,2024-04-08 05:40:09,2024-04-08 06:03:32,172.56.105.131,https://seattle-od.etc-research.com/,-25200,BLN,...,SND_1_SLine_00_STD,Tacoma Dome Station,AM,2024-04-08 06:03:32,Weekday,AM,0.0,7.0,9.0,-2.0
12,81174,2024-04-08 06:04:32,4,en,2024-04-08 06:03:32,2024-04-08 06:04:32,172.56.105.131,https://seattle-od.etc-research.com/index.php/...,-25200,BLN,...,SND_1_SLine_00_SAUSB,Auburn Station (Southbound),AM,2024-04-08 06:04:32,Weekday,AM,0.0,4.0,9.0,-5.0
13,81175,2024-04-08 06:05:41,4,en,2024-04-08 06:04:33,2024-04-08 06:05:41,172.56.105.131,https://seattle-od.etc-research.com/index.php/...,-25200,BLN,...,SND_1_SLine_00_SKESB,Kent Station (Southbound),AM,2024-04-08 06:05:41,Weekday,AM,0.0,3.0,9.0,-6.0
14,81176,2024-04-08 06:06:04,4,en,2024-04-08 06:05:42,2024-04-08 06:06:04,172.56.105.131,https://seattle-od.etc-research.com/index.php/...,-25200,BLN,...,SND_1_SLine_00_SKESB,Kent Station (Southbound),AM,2024-04-08 06:06:04,Weekday,AM,0.0,3.0,8.0,-5.0

In [87]:
new_df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT', 'ORIGRESPID', 'ROUTE_SURVEYED_Code_', 'ROUTE_SURVEYED',
       'ROUTE_SURVEYED_Other_', 'SSSL_ON_Code_', 'SSSL_ON', 'SSSL_OFF_Code_',
       'SSSL_OFF', 'S1L_ON_Code_', 'S1L_ON', 'S1L_OFF_Code_', 'S1L_OFF',
       'STTAC_ON_Code_', 'STTAC_ON', 'STTAC_OFF_Code_', 'STTAC_OFF',
       'TIME_BOARDED', 'LANGUAGE', 'LANGUAGE_Other_', 'RESTART_URL',
       'Line_Value', 'ROUTE_DESCRIPTION[CODE]', 'ETC_ROUTE_NAME', 'BOARD_ID',
       'BOARD_STOP[CODE]', 'BOARD_STOP_NAME', 'ALIGHT_ID', 'ALIGHT_STOP[CODE]',
       'ALIGHT_STOP_NAME', 'TIME_BOARDED_Code_', 'Date', 'Day', 'TIME PERIOD',
       'TIME PERIOD[Code]', 'Alight_Seq', 'Board_Seq', 'SEQ_CHECK'],
      dtype='object')

In [88]:
new_df[new_df['SEQ_CHECK']<0][['BOARD_ID','BOARD_STOP[CODE]','BOARD_STOP_NAME','ALIGHT_ID','ALIGHT_STOP[CODE]','ALIGHT_STOP_NAME']].head()

,BOARD_ID,BOARD_STOP[CODE],BOARD_STOP_NAME,ALIGHT_ID,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME
5,19.0,SND_1_1Line_01_990006,Northgate,3.0,SND_1_1Line_01_99905,Tukwila Int'l Blvd
11,9.0,SND_1_SLine_00_SLW,Lakewood Station,7.0,SND_1_SLine_00_STD,Tacoma Dome Station
12,9.0,SND_1_SLine_00_SLW,Lakewood Station,4.0,SND_1_SLine_00_SAUSB,Auburn Station (Southbound)
13,9.0,SND_1_SLine_00_SLW,Lakewood Station,3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound)
14,8.0,SND_1_SLine_00_SST,South Tacoma Station,3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound)

In [89]:
for _, row in new_df.iterrows():
    if row['SEQ_CHECK'] < 0:
        # Swap the board and alight values
        board_id = row['BOARD_ID']
        board_stop_code = row['BOARD_STOP[CODE]']
        board_stop_name = row['BOARD_STOP_NAME']
        alight_id = row['ALIGHT_ID']
        alight_stop_code = row['ALIGHT_STOP[CODE]']
        alight_stop_name = row['ALIGHT_STOP_NAME']

        new_df.loc[row.name, 'BOARD_ID'] = alight_id
        new_df.loc[row.name, 'BOARD_STOP[CODE]'] = alight_stop_code
        new_df.loc[row.name, 'BOARD_STOP_NAME'] = alight_stop_name
        new_df.loc[row.name, 'ALIGHT_ID'] = board_id
        new_df.loc[row.name, 'ALIGHT_STOP[CODE]'] = board_stop_code
        new_df.loc[row.name, 'ALIGHT_STOP_NAME'] = board_stop_name

In [90]:
new_df[new_df['SEQ_CHECK']<0][['BOARD_ID','BOARD_STOP[CODE]','BOARD_STOP_NAME','ALIGHT_ID','ALIGHT_STOP[CODE]','ALIGHT_STOP_NAME']].head()

,BOARD_ID,BOARD_STOP[CODE],BOARD_STOP_NAME,ALIGHT_ID,ALIGHT_STOP[CODE],ALIGHT_STOP_NAME
5,3.0,SND_1_1Line_01_99905,Tukwila Int'l Blvd,19.0,SND_1_1Line_01_990006,Northgate
11,7.0,SND_1_SLine_00_STD,Tacoma Dome Station,9.0,SND_1_SLine_00_SLW,Lakewood Station
12,4.0,SND_1_SLine_00_SAUSB,Auburn Station (Southbound),9.0,SND_1_SLine_00_SLW,Lakewood Station
13,3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound),9.0,SND_1_SLine_00_SLW,Lakewood Station
14,3.0,SND_1_SLine_00_SKESB,Kent Station (Southbound),8.0,SND_1_SLine_00_SST,South Tacoma Station

In [93]:
new_df['RESET_SEQ_CHECK'] = new_df['ALIGHT_ID'] - new_df['BOARD_ID']

In [94]:
new_df[['RESET_SEQ_CHECK','SEQ_CHECK']]

       RESET_SEQ_CHECK  SEQ_CHECK
5                 16.0      -16.0
11                 2.0       -2.0
12                 5.0       -5.0
13                 6.0       -6.0
14                 5.0       -5.0
...                ...        ...
23356              6.0        6.0
23357             12.0       12.0
23358              8.0        8.0
23359              6.0        6.0
23360              1.0        1.0

[22708 rows x 2 columns]