In [1]:
import pandas as pd
import warnings

warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv("reviewtool_20240625_BART_TraditionalTransferFlags.csv")

In [3]:
df.head()

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,...,Transfer5,Check5.GoodTransfer,Transfer6,Check6.GoodTransfer,Transfer7,Check7.GoodTransfer,Transfer8,Check8.GoodTransfer,real flags,Checkall.GoodTransfer
0,14,NaN,NaN,NaN,NaN,NaN,ACX_1_20,NaN,NaN,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,0,1
1,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,1,0
2,16,NaN,NaN,NaN,NaN,NaN,BAX_1_Orange-N,BAX_1_Yellow-N,NaN,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,1,1
3,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,1,0
4,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,NaN,0,NaN,0,NaN,0,1,0

In [4]:
df.shape

(546, 31)

In [5]:
df.columns

Index(['id', 'TRIP_FIRST_ROUTECode', 'TRIP_SECOND_ROUTECode',
       'TRIP_THIRD_ROUTECode', 'TRIP_FOURTH_ROUTECode', 'ROUTE_SURVEYEDCode',
       'TRIP_NEXT_ROUTECode', 'TRIP_AFTER_ROUTECode', 'TRIP_3RD_ROUTECode',
       'TRIP_LAST4TH_RTECode', 'transfers_list', 'FINAL_REVIEWER',
       'Duplicate Transfers', 'Transfer1', 'Check1.GoodTransfer', 'Transfer2',
       'Check2.GoodTransfer', 'Transfer3', 'Check3.GoodTransfer', 'Transfer4',
       'Check4.GoodTransfer', 'Transfer5', 'Check5.GoodTransfer', 'Transfer6',
       'Check6.GoodTransfer', 'Transfer7', 'Check7.GoodTransfer', 'Transfer8',
       'Check8.GoodTransfer', 'real flags', 'Checkall.GoodTransfer'],
      dtype='object')

In [6]:
db=pd.read_csv('elvisbartca2024interceptNEW_main_export_odbc.csv')

In [12]:
new_df=pd.merge(df,db[['id','ORIGIN_ADDRESS_LAT','ORIGIN_ADDRESS_LONG','DESTIN_ADDRESS_LAT','DESTIN_ADDRESS_LONG','HOME_ADDRESS_LAT','HOME_ADDRESS_LONG']],on='id',how='left')

In [13]:
new_df.head()

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,...,Transfer8,Check8.GoodTransfer,real flags,Checkall.GoodTransfer,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,HOME_ADDRESS_LAT,HOME_ADDRESS_LONG
0,14,NaN,NaN,NaN,NaN,NaN,ACX_1_20,NaN,NaN,NaN,...,NaN,0,0,1,37.712747,-122.21392,37.782673,-122.217147,37.782673,-122.217147
1,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.405481,-121.949979,37.682035,-121.768386
2,16,NaN,NaN,NaN,NaN,NaN,BAX_1_Orange-N,BAX_1_Yellow-N,NaN,NaN,...,NaN,0,1,1,NaN,NaN,NaN,NaN,38.025319,-121.902573
3,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.795255,-122.392806,37.738446,-122.453205
4,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.794601,-122.398673,37.548727,-121.988377

In [10]:
new_df.shape

(546, 35)

In [15]:
df_cleaned = new_df.dropna(subset=['ORIGIN_ADDRESS_LAT', 'ORIGIN_ADDRESS_LONG', 'DESTIN_ADDRESS_LAT', 'DESTIN_ADDRESS_LONG'], how='all')

In [16]:
df_cleaned.head()

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,...,Transfer8,Check8.GoodTransfer,real flags,Checkall.GoodTransfer,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,HOME_ADDRESS_LAT,HOME_ADDRESS_LONG
0,14,NaN,NaN,NaN,NaN,NaN,ACX_1_20,NaN,NaN,NaN,...,NaN,0,0,1,37.712747,-122.213920,37.782673,-122.217147,37.782673,-122.217147
1,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.405481,-121.949979,37.682035,-121.768386
3,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.795255,-122.392806,37.738446,-122.453205
4,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.794601,-122.398673,37.548727,-121.988377
5,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,37.556402,-121.975623,NaN,NaN,37.568208,-122.049228

In [17]:
df_cleaned.shape

(508, 37)

In [18]:
# Step 2: Drop rows where missing Origin or Destination lat/long match Home lat/long
condition = (
    (df_cleaned['ORIGIN_ADDRESS_LAT'].isna() & df_cleaned['ORIGIN_ADDRESS_LONG'].isna() &
     (df_cleaned['DESTIN_ADDRESS_LAT'] == df_cleaned['HOME_ADDRESS_LAT']) & 
     (df_cleaned['DESTIN_ADDRESS_LONG'] == df_cleaned['HOME_ADDRESS_LONG'])) |
    (df_cleaned['DESTIN_ADDRESS_LAT'].isna() & df_cleaned['DESTIN_ADDRESS_LONG'].isna() &
     (df_cleaned['ORIGIN_ADDRESS_LAT'] == df_cleaned['HOME_ADDRESS_LAT']) & 
     (df_cleaned['ORIGIN_ADDRESS_LONG'] == df_cleaned['HOME_ADDRESS_LONG']))
)

In [19]:
df_final = df_cleaned[~condition]

In [20]:
df_final.head()

,id,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,ROUTE_SURVEYEDCode,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode,...,Transfer8,Check8.GoodTransfer,real flags,Checkall.GoodTransfer,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,HOME_ADDRESS_LAT,HOME_ADDRESS_LONG
0,14,NaN,NaN,NaN,NaN,NaN,ACX_1_20,NaN,NaN,NaN,...,NaN,0,0,1,37.712747,-122.213920,37.782673,-122.217147,37.782673,-122.217147
1,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.405481,-121.949979,37.682035,-121.768386
3,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.795255,-122.392806,37.738446,-122.453205
4,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,NaN,NaN,37.794601,-122.398673,37.548727,-121.988377
5,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0,1,0,37.556402,-121.975623,NaN,NaN,37.568208,-122.049228

In [21]:
df_final.shape

(507, 37)