# Here we check if there is Transfer Route present but Transfer points(lat, long) are not present

In [42]:
import pandas as pd
import numpy as np
import copy
from geopy.distance import geodesic
import warnings

warnings.filterwarnings("ignore")

In [2]:
def check_all_characters_present(df, columns_to_check):
    # Function to clean a string by removing underscores and square brackets and converting to lowercase
    def clean_string(s):
        return s.replace('_', '').replace('[', '').replace(']', '').replace(' ','').replace('#','').lower()

    # Clean and convert all column names in df to lowercase for case-insensitive comparison
    df_columns_lower = [clean_string(column) for column in df.columns]

    # Clean and convert the columns_to_check list to lowercase for case-insensitive comparison
    columns_to_check_lower = [clean_string(column) for column in columns_to_check]

    # Use a list comprehension to filter columns
    matching_columns = [column for column in df.columns if clean_string(column) in columns_to_check_lower]

    return matching_columns

In [3]:
df=pd.read_csv("elvismunica2024obweekday_export_odbc.csv")
df.head()

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ELVIS_USER_CHANGE_7_C_REASON,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,EXP_HOMELESSCode,EXP_HOMELESS,_REVERSE_TRIP,GENERATABLE_TRIPS
0,5844,2024-02-21 09:11:15,82,en,2024-02-21 08:54:29,2024-02-21 09:11:15,12.35.79.25,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5851,2024-02-21 09:11:20,82,en,2024-02-21 08:56:02,2024-02-21 09:11:20,107.77.213.142,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5854,2024-02-21 09:11:13,82,en,2024-02-21 08:57:31,2024-02-21 09:11:13,174.195.83.69,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5858,2024-02-21 09:11:11,82,en,2024-02-21 08:57:41,2024-02-21 09:11:11,174.249.148.95,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5864,2024-02-21 09:11:12,82,en,2024-02-21 08:57:45,2024-02-21 09:11:12,107.77.214.78,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns

Index(['id', 'Completed', 'Last_page', 'Start_language', 'Date_started',
       'Date_last_action', 'IP_address', 'Referring_URL', 'TIME_ADJUST',
       'INTERV_INIT',
       ...
       'ELVIS_USER_CHANGE_7_C_REASON', 'INVITE_EMAIL', 'INVITE_SMS',
       'INVITE_CALL', 'INVITE_TOKEN', 'INVITE_STATUS', 'EXP_HOMELESSCode',
       'EXP_HOMELESS', '_REVERSE_TRIP', 'GENERATABLE_TRIPS'],
      dtype='object', length=813)

In [5]:
pm_values=['PM1','PM2','PM3','PM4']

In [6]:
# pm_df=df[df['TIME_ONCode'].isin(pm_values)]
pm_df=copy.deepcopy(df)

In [7]:
pm_df

,id,Completed,Last_page,Start_language,Date_started,Date_last_action,IP_address,Referring_URL,TIME_ADJUST,INTERV_INIT,...,ELVIS_USER_CHANGE_7_C_REASON,INVITE_EMAIL,INVITE_SMS,INVITE_CALL,INVITE_TOKEN,INVITE_STATUS,EXP_HOMELESSCode,EXP_HOMELESS,_REVERSE_TRIP,GENERATABLE_TRIPS
0,5844,2024-02-21 09:11:15,82,en,2024-02-21 08:54:29,2024-02-21 09:11:15,12.35.79.25,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5851,2024-02-21 09:11:20,82,en,2024-02-21 08:56:02,2024-02-21 09:11:20,107.77.213.142,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5854,2024-02-21 09:11:13,82,en,2024-02-21 08:57:31,2024-02-21 09:11:13,174.195.83.69,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5858,2024-02-21 09:11:11,82,en,2024-02-21 08:57:41,2024-02-21 09:11:11,174.249.148.95,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5864,2024-02-21 09:11:12,82,en,2024-02-21 08:57:45,2024-02-21 09:11:12,107.77.214.78,https://muni-ca.etc-research.com/,-28800.0,999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33859,1003222,2024-03-02 19:44:16,82,en,2024-03-02 19:29:41,2024-07-18 09:31:09,107.77.213.114,https://muni-ca.etc-research.com/,-28800.0,AEM,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14004_MainTrip,NaN
33860,1003223,2024-04-22 10:07:06,82,en,2024-04-22 09:54:16,2024-07-18 20:50:56,174.195.84.131,https://muni-ca.etc-research.com/index.php/sur...,-25200.0,EBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48132_MainTrip,NaN
33861,1003224,2024-03-03 21:43:05,82,en,2024-03-03 21:34:58,2024-07-19 13:55:57,174.249.152.85,https://muni-ca.etc-research.com/,-28800.0,DAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15315_MainTrip,NaN
33862,1003225,2024-05-28 12:21:20,82,en,2024-05-28 12:14:11,2024-07-19 13:56:43,174.249.154.245,https://muni-ca.etc-research.com/,-25200.0,AMT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62247_MainTrip,NaN
33863,1003226,2024-03-11 07:19:55,82,en,2024-03-11 07:11:25,2024-07-20 14:55:51,174.249.150.78,https://muni-ca.etc-research.com/index.php/sur...,-25200.0,EBB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22300_MainTrip,NaN

In [8]:
pm_df['INTERV_INIT']!=999
pm_df['INTERV_INIT']!='999'

0        False
1        False
2        False
3        False
4        False
         ...
33859     True
33860     True
33861     True
33862     True
33863     True
Name: INTERV_INIT, Length: 33864, dtype: bool

In [9]:
pm_df=pm_df[pm_df['INTERV_INIT']!='999']

In [10]:
pm_df=pm_df[pm_df['HAVE_5_MIN_FOR_SURVECode']==1]

In [11]:
transfer_columns_checks=['prevtran1onbuslat', 'prevtran1onbuslong',
                  'prevtran1offbuslat', 'prevtran1offbuslong', 'prevtran2onbuslat', 
                  'prevtran2onbuslong', 'prevtran2offbuslat', 'prevtran2offbuslong',
                  'prevtran3onbuslat', 'prevtran3onbuslong', 'prevtran3offbuslat',
                  'prevtran3offbuslong', 'prevtran4onbuslat', 'prevtran4onbuslong', 
                  'prevtran4offbuslat', 'prevtran4offbuslong','nexttran1onbuslat',
                  'nexttran1onbuslong', 'nexttran1offbuslat', 'nexttran1offbuslong', 
                  'nexttran2onbuslat', 
                  'nexttran2onbuslong', 'nexttran2offbuslat', 'nexttran2offbuslong', 
                  'nexttran3onbuslat', 'nexttran3onbuslong',
                  'nexttran3offbuslat', 'nexttran3offbuslong', 'nexttran4onbuslat', 'nexttran4onbuslong',
                  'nexttran4offbuslat', 'nexttran4offbuslong']

In [12]:
transfer_columns=check_all_characters_present(pm_df,transfer_columns_checks)
transfer_columns

['PREV_TRAN_1_ON_BUS_LAT',
 'PREV_TRAN_1_ON_BUS_LONG',
 'PREV_TRAN_1_OFF_BUS_LAT',
 'PREV_TRAN_1_OFF_BUS_LONG',
 'PREV_TRAN_2_ON_BUS_LAT',
 'PREV_TRAN_2_ON_BUS_LONG',
 'PREV_TRAN_2_OFF_BUS_LAT',
 'PREV_TRAN_2_OFF_BUS_LONG',
 'PREV_TRAN_3_ON_BUS_LAT',
 'PREV_TRAN_3_ON_BUS_LONG',
 'PREV_TRAN_3_OFF_BUS_LAT',
 'PREV_TRAN_3_OFF_BUS_LONG',
 'PREV_TRAN_4_ON_BUS_LAT',
 'PREV_TRAN_4_ON_BUS_LONG',
 'PREV_TRAN_4_OFF_BUS_LAT',
 'PREV_TRAN_4_OFF_BUS_LONG',
 'NEXT_TRAN_1_ON_BUS_LAT',
 'NEXT_TRAN_1_ON_BUS_LONG',
 'NEXT_TRAN_1_OFF_BUS_LAT',
 'NEXT_TRAN_1_OFF_BUS_LONG',
 'NEXT_TRAN_2_ON_BUS_LAT',
 'NEXT_TRAN_2_ON_BUS_LONG',
 'NEXT_TRAN_2_OFF_BUS_LAT',
 'NEXT_TRAN_2_OFF_BUS_LONG',
 'NEXT_TRAN_3_ON_BUS_LAT',
 'NEXT_TRAN_3_ON_BUS_LONG',
 'NEXT_TRAN_3_OFF_BUS_LAT',
 'NEXT_TRAN_3_OFF_BUS_LONG',
 'NEXT_TRAN_4_ON_BUS_LAT',
 'NEXT_TRAN_4_ON_BUS_LONG',
 'NEXT_TRAN_4_OFF_BUS_LAT',
 'NEXT_TRAN_4_OFF_BUS_LONG']

In [13]:
pm_df[transfer_columns]

,PREV_TRAN_1_ON_BUS_LAT,PREV_TRAN_1_ON_BUS_LONG,PREV_TRAN_1_OFF_BUS_LAT,PREV_TRAN_1_OFF_BUS_LONG,PREV_TRAN_2_ON_BUS_LAT,PREV_TRAN_2_ON_BUS_LONG,PREV_TRAN_2_OFF_BUS_LAT,PREV_TRAN_2_OFF_BUS_LONG,PREV_TRAN_3_ON_BUS_LAT,PREV_TRAN_3_ON_BUS_LONG,...,NEXT_TRAN_2_OFF_BUS_LAT,NEXT_TRAN_2_OFF_BUS_LONG,NEXT_TRAN_3_ON_BUS_LAT,NEXT_TRAN_3_ON_BUS_LONG,NEXT_TRAN_3_OFF_BUS_LAT,NEXT_TRAN_3_OFF_BUS_LONG,NEXT_TRAN_4_ON_BUS_LAT,NEXT_TRAN_4_ON_BUS_LONG,NEXT_TRAN_4_OFF_BUS_LAT,NEXT_TRAN_4_OFF_BUS_LONG
45,37.637720,-122.416384,37.706259,-122.468908,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,37.760790,-122.388460,37.784227,-122.407880,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33860,37.737590,-122.384160,37.720952,-122.447379,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33863,37.770152,-122.445384,37.771293,-122.437373,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
transfer_route_code_check=['prevtransferscode', 'prevtransfers', 'tripfirstroutecode', 'tripsecondroutecode', 'tripthirdroutecode', 'tripfourthroutecode', 'nexttransferscode', 'nexttransfers', 'tripnextroutecode', 'tripafterroutecode', 'trip3rdroutecode', 'triplast4thrtecode']
transfer_route_code=check_all_characters_present(pm_df,transfer_route_code_check)
transfer_route_code

['PREV_TRANSFERSCode',
 'PREV_TRANSFERS',
 'TRIP_FIRST_ROUTECode',
 'TRIP_SECOND_ROUTECode',
 'TRIP_THIRD_ROUTECode',
 'TRIP_FOURTH_ROUTECode',
 'NEXT_TRANSFERSCode',
 'NEXT_TRANSFERS',
 'TRIP_NEXT_ROUTECode',
 'TRIP_AFTER_ROUTECode',
 'TRIP_3RD_ROUTECode',
 'TRIP_LAST4TH_RTECode']

In [15]:
pm_df[transfer_route_code]

,PREV_TRANSFERSCode,PREV_TRANSFERS,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,NEXT_TRANSFERSCode,NEXT_TRANSFERS,TRIP_NEXT_ROUTECode,TRIP_AFTER_ROUTECode,TRIP_3RD_ROUTECode,TRIP_LAST4TH_RTECode
45,1.0,(1) One,BAX_1_Yellow-N,NaN,NaN,NaN,0.0,(0) None,NaN,NaN,NaN,NaN
49,0.0,(0) None,NaN,NaN,NaN,NaN,0.0,(0) None,NaN,NaN,NaN,NaN
50,0.0,(0) None,NaN,NaN,NaN,NaN,0.0,(0) None,NaN,NaN,NaN,NaN
52,0.0,(0) None,NaN,NaN,NaN,NaN,0.0,(0) None,NaN,NaN,NaN,NaN
53,1.0,(1) One,MUN_1_15,NaN,NaN,NaN,0.0,(0) None,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
33859,0.0,(0) None,NaN,NaN,NaN,NaN,0.0,(0) None,NaN,NaN,NaN,NaN
33860,1.0,(1) One,MUN_1_54,NaN,NaN,NaN,0.0,(0) None,NaN,NaN,NaN,NaN
33861,0.0,(0) None,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_30,NaN,NaN,NaN
33862,0.0,(0) None,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_N,NaN,NaN,NaN
33863,1.0,(1) One,MUN_1_6,NaN,NaN,NaN,0.0,(0) None,NaN,NaN,NaN,NaN

In [16]:
transfer_point_code_check=[ 'tripfirstroutecode', 'tripsecondroutecode', 'tripthirdroutecode', 'tripfourthroutecode','tripnextroutecode', 'tripafterroutecode', 'trip3rdroutecode', 'triplast4thrtecode']
transfer_point_code=check_all_characters_present(pm_df,transfer_point_code_check)
transfer_point_code

['TRIP_FIRST_ROUTECode',
 'TRIP_SECOND_ROUTECode',
 'TRIP_THIRD_ROUTECode',
 'TRIP_FOURTH_ROUTECode',
 'TRIP_NEXT_ROUTECode',
 'TRIP_AFTER_ROUTECode',
 'TRIP_3RD_ROUTECode',
 'TRIP_LAST4TH_RTECode']

In [17]:
transfer_df=pm_df[['id',*transfer_route_code,*transfer_columns]]

In [18]:
transfer_df

,id,PREV_TRANSFERSCode,PREV_TRANSFERS,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,NEXT_TRANSFERSCode,NEXT_TRANSFERS,TRIP_NEXT_ROUTECode,...,NEXT_TRAN_2_OFF_BUS_LAT,NEXT_TRAN_2_OFF_BUS_LONG,NEXT_TRAN_3_ON_BUS_LAT,NEXT_TRAN_3_ON_BUS_LONG,NEXT_TRAN_3_OFF_BUS_LAT,NEXT_TRAN_3_OFF_BUS_LONG,NEXT_TRAN_4_ON_BUS_LAT,NEXT_TRAN_4_ON_BUS_LONG,NEXT_TRAN_4_OFF_BUS_LAT,NEXT_TRAN_4_OFF_BUS_LONG
45,6015,1.0,(1) One,BAX_1_Yellow-N,NaN,NaN,NaN,0.0,(0) None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,6069,0.0,(0) None,NaN,NaN,NaN,NaN,0.0,(0) None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,6071,0.0,(0) None,NaN,NaN,NaN,NaN,0.0,(0) None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,6073,0.0,(0) None,NaN,NaN,NaN,NaN,0.0,(0) None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,6074,1.0,(1) One,MUN_1_15,NaN,NaN,NaN,0.0,(0) None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33859,1003222,0.0,(0) None,NaN,NaN,NaN,NaN,0.0,(0) None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33860,1003223,1.0,(1) One,MUN_1_54,NaN,NaN,NaN,0.0,(0) None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33861,1003224,0.0,(0) None,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33862,1003225,0.0,(0) None,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33863,1003226,1.0,(1) One,MUN_1_6,NaN,NaN,NaN,0.0,(0) None,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
transfer_df['PREV_TRANSFERS'].replace('(0) None',np.nan,inplace=True)

In [20]:
transfer_df['NEXT_TRANSFERS'].replace('(0) None',np.nan,inplace=True)

In [21]:
transfer_df[['PREV_TRANSFERS','NEXT_TRANSFERS']]

      PREV_TRANSFERS NEXT_TRANSFERS
45           (1) One            NaN
49               NaN            NaN
50               NaN            NaN
52               NaN            NaN
53           (1) One            NaN
...              ...            ...
33859            NaN            NaN
33860        (1) One            NaN
33861            NaN        (1) One
33862            NaN        (1) One
33863        (1) One            NaN

[26175 rows x 2 columns]

In [22]:
transfer_df.dropna(subset=[*transfer_point_code,*transfer_columns],how='all',inplace=True)

In [23]:
transfer_df.head()

,id,PREV_TRANSFERSCode,PREV_TRANSFERS,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,NEXT_TRANSFERSCode,NEXT_TRANSFERS,TRIP_NEXT_ROUTECode,...,NEXT_TRAN_2_OFF_BUS_LAT,NEXT_TRAN_2_OFF_BUS_LONG,NEXT_TRAN_3_ON_BUS_LAT,NEXT_TRAN_3_ON_BUS_LONG,NEXT_TRAN_3_OFF_BUS_LAT,NEXT_TRAN_3_OFF_BUS_LONG,NEXT_TRAN_4_ON_BUS_LAT,NEXT_TRAN_4_ON_BUS_LONG,NEXT_TRAN_4_OFF_BUS_LAT,NEXT_TRAN_4_OFF_BUS_LONG
45,6015,1.0,(1) One,BAX_1_Yellow-N,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,6074,1.0,(1) One,MUN_1_15,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,6103,1.0,(1) One,MUN_1_22,NaN,NaN,NaN,1.0,(1) One,MUN_1_N,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,6113,1.0,(1) One,MUN_1_15,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,6141,0.0,NaN,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_30,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
transfer_df.columns

Index(['id', 'PREV_TRANSFERSCode', 'PREV_TRANSFERS', 'TRIP_FIRST_ROUTECode',
       'TRIP_SECOND_ROUTECode', 'TRIP_THIRD_ROUTECode',
       'TRIP_FOURTH_ROUTECode', 'NEXT_TRANSFERSCode', 'NEXT_TRANSFERS',
       'TRIP_NEXT_ROUTECode', 'TRIP_AFTER_ROUTECode', 'TRIP_3RD_ROUTECode',
       'TRIP_LAST4TH_RTECode', 'PREV_TRAN_1_ON_BUS_LAT',
       'PREV_TRAN_1_ON_BUS_LONG', 'PREV_TRAN_1_OFF_BUS_LAT',
       'PREV_TRAN_1_OFF_BUS_LONG', 'PREV_TRAN_2_ON_BUS_LAT',
       'PREV_TRAN_2_ON_BUS_LONG', 'PREV_TRAN_2_OFF_BUS_LAT',
       'PREV_TRAN_2_OFF_BUS_LONG', 'PREV_TRAN_3_ON_BUS_LAT',
       'PREV_TRAN_3_ON_BUS_LONG', 'PREV_TRAN_3_OFF_BUS_LAT',
       'PREV_TRAN_3_OFF_BUS_LONG', 'PREV_TRAN_4_ON_BUS_LAT',
       'PREV_TRAN_4_ON_BUS_LONG', 'PREV_TRAN_4_OFF_BUS_LAT',
       'PREV_TRAN_4_OFF_BUS_LONG', 'NEXT_TRAN_1_ON_BUS_LAT',
       'NEXT_TRAN_1_ON_BUS_LONG', 'NEXT_TRAN_1_OFF_BUS_LAT',
       'NEXT_TRAN_1_OFF_BUS_LONG', 'NEXT_TRAN_2_ON_BUS_LAT',
       'NEXT_TRAN_2_ON_BUS_LONG', 'NEXT_TRAN_2_OFF_BUS_LAT',
       'NEXT_TRAN_2_OFF_BUS_LONG', 'NEXT_TRAN_3_ON_BUS_LAT',
       'NEXT_TRAN_3_ON_BUS_LONG', 'NEXT_TRAN_3_OFF_BUS_LAT',
       'NEXT_TRAN_3_OFF_BUS_LONG', 'NEXT_TRAN_4_ON_BUS_LAT',
       'NEXT_TRAN_4_ON_BUS_LONG', 'NEXT_TRAN_4_OFF_BUS_LAT',
       'NEXT_TRAN_4_OFF_BUS_LONG'],
      dtype='object')

In [25]:
transfer_df[['PREV_TRANSFERS','TRIP_FIRST_ROUTECode','TRIP_SECOND_ROUTECode', 'TRIP_THIRD_ROUTECode','TRIP_FOURTH_ROUTECode','PREV_TRAN_1_ON_BUS_LAT','PREV_TRAN_1_ON_BUS_LONG', 'PREV_TRAN_1_OFF_BUS_LAT',
       'PREV_TRAN_1_OFF_BUS_LONG', 'PREV_TRAN_2_ON_BUS_LAT',
       'PREV_TRAN_2_ON_BUS_LONG', 'PREV_TRAN_2_OFF_BUS_LAT',
       'PREV_TRAN_2_OFF_BUS_LONG', 'PREV_TRAN_3_ON_BUS_LAT',
       'PREV_TRAN_3_ON_BUS_LONG', 'PREV_TRAN_3_OFF_BUS_LAT',
       'PREV_TRAN_3_OFF_BUS_LONG', 'PREV_TRAN_4_ON_BUS_LAT',
       'PREV_TRAN_4_ON_BUS_LONG', 'PREV_TRAN_4_OFF_BUS_LAT',
       'PREV_TRAN_4_OFF_BUS_LONG']]

,PREV_TRANSFERS,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,PREV_TRAN_1_ON_BUS_LAT,PREV_TRAN_1_ON_BUS_LONG,PREV_TRAN_1_OFF_BUS_LAT,PREV_TRAN_1_OFF_BUS_LONG,PREV_TRAN_2_ON_BUS_LAT,...,PREV_TRAN_2_OFF_BUS_LAT,PREV_TRAN_2_OFF_BUS_LONG,PREV_TRAN_3_ON_BUS_LAT,PREV_TRAN_3_ON_BUS_LONG,PREV_TRAN_3_OFF_BUS_LAT,PREV_TRAN_3_OFF_BUS_LONG,PREV_TRAN_4_ON_BUS_LAT,PREV_TRAN_4_ON_BUS_LONG,PREV_TRAN_4_OFF_BUS_LAT,PREV_TRAN_4_OFF_BUS_LONG
45,(1) One,BAX_1_Yellow-N,NaN,NaN,NaN,37.637720,-122.416384,37.706259,-122.468908,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,(1) One,MUN_1_15,NaN,NaN,NaN,37.760790,-122.388460,37.784227,-122.407880,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,(1) One,MUN_1_22,NaN,NaN,NaN,37.765400,-122.415428,37.772199,-122.430537,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,(1) One,MUN_1_15,NaN,NaN,NaN,37.731849,-122.387310,37.786373,-122.402110,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33858,(1) One,MUN_1_7,NaN,NaN,NaN,37.769170,-122.453075,37.771231,-122.436743,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33860,(1) One,MUN_1_54,NaN,NaN,NaN,37.737590,-122.384160,37.720952,-122.447379,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33862,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33863,(1) One,MUN_1_6,NaN,NaN,NaN,37.770152,-122.445384,37.771293,-122.437373,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
filtered_df = transfer_df[
    (transfer_df['TRIP_FIRST_ROUTECode'].notnull() |
    transfer_df['TRIP_SECOND_ROUTECode'].notnull() |
    transfer_df['TRIP_THIRD_ROUTECode'].notnull() |
    transfer_df['TRIP_FOURTH_ROUTECode'].notnull() )&
    transfer_df[['PREV_TRAN_1_ON_BUS_LAT', 'PREV_TRAN_1_ON_BUS_LONG', 'PREV_TRAN_1_OFF_BUS_LAT',
                 'PREV_TRAN_1_OFF_BUS_LONG', 'PREV_TRAN_2_ON_BUS_LAT', 'PREV_TRAN_2_ON_BUS_LONG',
                 'PREV_TRAN_2_OFF_BUS_LAT', 'PREV_TRAN_2_OFF_BUS_LONG', 'PREV_TRAN_3_ON_BUS_LAT',
                 'PREV_TRAN_3_ON_BUS_LONG', 'PREV_TRAN_3_OFF_BUS_LAT', 'PREV_TRAN_3_OFF_BUS_LONG',
                 'PREV_TRAN_4_ON_BUS_LAT', 'PREV_TRAN_4_ON_BUS_LONG', 'PREV_TRAN_4_OFF_BUS_LAT',
                 'PREV_TRAN_4_OFF_BUS_LONG']].isnull().all(axis=1)
]

In [27]:
filtered_df[['id','PREV_TRANSFERS','TRIP_FIRST_ROUTECode','TRIP_SECOND_ROUTECode', 'TRIP_THIRD_ROUTECode','TRIP_FOURTH_ROUTECode','PREV_TRAN_1_ON_BUS_LAT','PREV_TRAN_1_ON_BUS_LONG', 'PREV_TRAN_1_OFF_BUS_LAT',
       'PREV_TRAN_1_OFF_BUS_LONG', 'PREV_TRAN_2_ON_BUS_LAT',
       'PREV_TRAN_2_ON_BUS_LONG', 'PREV_TRAN_2_OFF_BUS_LAT',
       'PREV_TRAN_2_OFF_BUS_LONG', 'PREV_TRAN_3_ON_BUS_LAT',
       'PREV_TRAN_3_ON_BUS_LONG', 'PREV_TRAN_3_OFF_BUS_LAT',
       'PREV_TRAN_3_OFF_BUS_LONG', 'PREV_TRAN_4_ON_BUS_LAT',
       'PREV_TRAN_4_ON_BUS_LONG', 'PREV_TRAN_4_OFF_BUS_LAT',
       'PREV_TRAN_4_OFF_BUS_LONG']]

,id,PREV_TRANSFERS,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,PREV_TRAN_1_ON_BUS_LAT,PREV_TRAN_1_ON_BUS_LONG,PREV_TRAN_1_OFF_BUS_LAT,PREV_TRAN_1_OFF_BUS_LONG,...,PREV_TRAN_2_OFF_BUS_LAT,PREV_TRAN_2_OFF_BUS_LONG,PREV_TRAN_3_ON_BUS_LAT,PREV_TRAN_3_ON_BUS_LONG,PREV_TRAN_3_OFF_BUS_LAT,PREV_TRAN_3_OFF_BUS_LONG,PREV_TRAN_4_ON_BUS_LAT,PREV_TRAN_4_ON_BUS_LONG,PREV_TRAN_4_OFF_BUS_LAT,PREV_TRAN_4_OFF_BUS_LONG
31294,59376,(1) One,MUN_1_24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
filtered_df = transfer_df[
    (transfer_df['TRIP_NEXT_ROUTECode'].notnull() |
    transfer_df['TRIP_AFTER_ROUTECode'].notnull() |
    transfer_df['TRIP_3RD_ROUTECode'].notnull() |
    transfer_df['TRIP_LAST4TH_RTECode'].notnull() )&
    transfer_df[['NEXT_TRAN_1_ON_BUS_LAT','NEXT_TRAN_1_ON_BUS_LONG', 'NEXT_TRAN_1_OFF_BUS_LAT',
       'NEXT_TRAN_1_OFF_BUS_LONG', 'NEXT_TRAN_2_ON_BUS_LAT',
       'NEXT_TRAN_2_ON_BUS_LONG', 'NEXT_TRAN_2_OFF_BUS_LAT',
       'NEXT_TRAN_2_OFF_BUS_LONG', 'NEXT_TRAN_3_ON_BUS_LAT',
       'NEXT_TRAN_3_ON_BUS_LONG', 'NEXT_TRAN_3_OFF_BUS_LAT',
       'NEXT_TRAN_3_OFF_BUS_LONG', 'NEXT_TRAN_4_ON_BUS_LAT',
       'NEXT_TRAN_4_ON_BUS_LONG', 'NEXT_TRAN_4_OFF_BUS_LAT',
       'NEXT_TRAN_4_OFF_BUS_LONG']].isnull().all(axis=1)
]

In [29]:
filtered_df

,id,PREV_TRANSFERSCode,PREV_TRANSFERS,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,NEXT_TRANSFERSCode,NEXT_TRANSFERS,TRIP_NEXT_ROUTECode,...,NEXT_TRAN_2_OFF_BUS_LAT,NEXT_TRAN_2_OFF_BUS_LONG,NEXT_TRAN_3_ON_BUS_LAT,NEXT_TRAN_3_ON_BUS_LONG,NEXT_TRAN_3_OFF_BUS_LAT,NEXT_TRAN_3_OFF_BUS_LONG,NEXT_TRAN_4_ON_BUS_LAT,NEXT_TRAN_4_ON_BUS_LONG,NEXT_TRAN_4_OFF_BUS_LAT,NEXT_TRAN_4_OFF_BUS_LONG
10958,30872,0.0,NaN,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14299,35905,0.0,NaN,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16885,39695,0.0,NaN,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
condition1 = (
    (transfer_df['TRIP_NEXT_ROUTECode'].notnull() |
     transfer_df['TRIP_AFTER_ROUTECode'].notnull() |
     transfer_df['TRIP_3RD_ROUTECode'].notnull() |
     transfer_df['TRIP_LAST4TH_RTECode'].notnull()) &
    transfer_df[['NEXT_TRAN_1_ON_BUS_LAT', 'NEXT_TRAN_1_ON_BUS_LONG', 'NEXT_TRAN_1_OFF_BUS_LAT',
                 'NEXT_TRAN_1_OFF_BUS_LONG', 'NEXT_TRAN_2_ON_BUS_LAT', 'NEXT_TRAN_2_ON_BUS_LONG',
                 'NEXT_TRAN_2_OFF_BUS_LAT', 'NEXT_TRAN_2_OFF_BUS_LONG', 'NEXT_TRAN_3_ON_BUS_LAT',
                 'NEXT_TRAN_3_ON_BUS_LONG', 'NEXT_TRAN_3_OFF_BUS_LAT', 'NEXT_TRAN_3_OFF_BUS_LONG',
                 'NEXT_TRAN_4_ON_BUS_LAT', 'NEXT_TRAN_4_ON_BUS_LONG', 'NEXT_TRAN_4_OFF_BUS_LAT',
                 'NEXT_TRAN_4_OFF_BUS_LONG']].isnull().all(axis=1)
)

condition2 = (
    (transfer_df['TRIP_FIRST_ROUTECode'].notnull() |
     transfer_df['TRIP_SECOND_ROUTECode'].notnull() |
     transfer_df['TRIP_THIRD_ROUTECode'].notnull() |
     transfer_df['TRIP_FOURTH_ROUTECode'].notnull()) &
    transfer_df[['PREV_TRAN_1_ON_BUS_LAT', 'PREV_TRAN_1_ON_BUS_LONG', 'PREV_TRAN_1_OFF_BUS_LAT',
                 'PREV_TRAN_1_OFF_BUS_LONG', 'PREV_TRAN_2_ON_BUS_LAT', 'PREV_TRAN_2_ON_BUS_LONG',
                 'PREV_TRAN_2_OFF_BUS_LAT', 'PREV_TRAN_2_OFF_BUS_LONG', 'PREV_TRAN_3_ON_BUS_LAT',
                 'PREV_TRAN_3_ON_BUS_LONG', 'PREV_TRAN_3_OFF_BUS_LAT', 'PREV_TRAN_3_OFF_BUS_LONG',
                 'PREV_TRAN_4_ON_BUS_LAT', 'PREV_TRAN_4_ON_BUS_LONG', 'PREV_TRAN_4_OFF_BUS_LAT',
                 'PREV_TRAN_4_OFF_BUS_LONG']].isnull().all(axis=1)
)

# Combine conditions with | (logical OR)
combined_condition = condition1 | condition2

# Filter DataFrame
filtered_df = transfer_df[combined_condition]

In [31]:
# filtered_df.to_csv('All Records Transfer Values.csv',index=False)

In [32]:
filtered_df.head(3)

,id,PREV_TRANSFERSCode,PREV_TRANSFERS,TRIP_FIRST_ROUTECode,TRIP_SECOND_ROUTECode,TRIP_THIRD_ROUTECode,TRIP_FOURTH_ROUTECode,NEXT_TRANSFERSCode,NEXT_TRANSFERS,TRIP_NEXT_ROUTECode,...,NEXT_TRAN_2_OFF_BUS_LAT,NEXT_TRAN_2_OFF_BUS_LONG,NEXT_TRAN_3_ON_BUS_LAT,NEXT_TRAN_3_ON_BUS_LONG,NEXT_TRAN_3_OFF_BUS_LAT,NEXT_TRAN_3_OFF_BUS_LONG,NEXT_TRAN_4_ON_BUS_LAT,NEXT_TRAN_4_ON_BUS_LONG,NEXT_TRAN_4_OFF_BUS_LAT,NEXT_TRAN_4_OFF_BUS_LONG
10958,30872,0.0,NaN,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14299,35905,0.0,NaN,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16885,39695,0.0,NaN,NaN,NaN,NaN,NaN,1.0,(1) One,MUN_1_6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
origin_destin_column_check=['originaddresslat','originaddresslong','destinaddresslat', 'destinaddresslong']

In [55]:
origin_destin_column=check_all_characters_present(pm_df,origin_destin_column_check)
origin_destin_column.sort()
origin_destin_column

['DESTIN_ADDRESS_LAT',
 'DESTIN_ADDRESS_LONG',
 'ORIGIN_ADDRESS_LAT',
 'ORIGIN_ADDRESS_LONG']

In [35]:
# 44620: The origin, destination, and home are the same, indicating a round trip.
# 44699 & 44754: The origin to destination is less than 0.25 miles.

In [74]:
test_df=pm_df[(pm_df['id']==44620)|(pm_df['id']==44699)|(pm_df['id']==44754)|(pm_df['id']==60669)][['id',*origin_destin_column]]

In [75]:
test_df

,id,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG
20077,44620,37.792649,-122.426176,37.792649,-122.426176
20126,44699,37.762739,-122.435209,37.761076,-122.434195
20152,44754,37.782762,-122.424693,37.783440,-122.423135
31919,60669,37.433734,-122.401419,37.804351,-122.271163

In [61]:

def get_distance_between_coordinates(lat1, lon1, lat2, lon2):
    try:
        lat1 = float(lat1)
        lon1 = float(lon1)
        lat2 = float(lat2)
        lon2 = float(lon2)
        
        coords_1 = (lat1, lon1)
        coords_2 = (lat2, lon2)
        
        distance = geodesic(coords_1, coords_2).miles
        return distance
    except (ValueError, TypeError) as e:
        # Handle the exception here
        print(f"Error calculating distance: {e}")  # Change to the desired distance unit
        return np.NAN

In [76]:
'''
origin_destin_column=['DESTIN_ADDRESS_LAT',
 'DESTIN_ADDRESS_LONG',
 'ORIGIN_ADDRESS_LAT',
 'ORIGIN_ADDRESS_LONG']

'''

for _,row in test_df.iterrows():
    test_df.loc[row.name,'Distance']=get_distance_between_coordinates(row[origin_destin_column[2]],row[origin_destin_column[3]],row[origin_destin_column[0]],row[origin_destin_column[1]])

In [77]:
test_df

,id,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,Distance
20077,44620,37.792649,-122.426176,37.792649,-122.426176,0.000000
20126,44699,37.762739,-122.435209,37.761076,-122.434195,0.127423
20152,44754,37.782762,-122.424693,37.783440,-122.423135,0.097258
31919,60669,37.433734,-122.401419,37.804351,-122.271163,26.539815

In [78]:
test_df['Distance_Flag']=np.where(test_df['Distance']<0.25,1,0)

In [79]:
test_df

,id,DESTIN_ADDRESS_LAT,DESTIN_ADDRESS_LONG,ORIGIN_ADDRESS_LAT,ORIGIN_ADDRESS_LONG,Distance,Distance_Flag
20077,44620,37.792649,-122.426176,37.792649,-122.426176,0.000000,1
20126,44699,37.762739,-122.435209,37.761076,-122.434195,0.127423,1
20152,44754,37.782762,-122.424693,37.783440,-122.423135,0.097258,1
31919,60669,37.433734,-122.401419,37.804351,-122.271163,26.539815,0